// ─── Achievement Catalog ──────────────────────────────────────────────────────
// Hundreds of achievements: public, hidden (mysterious), and secret (invisible)
// Categories: partidas, torneios, evolução, social, economia, mercado, coleção, história, carreira, secreto, lendário

export const ACHIEVEMENT_CATALOG = [
  // ═══════════════ PARTIDAS — PÚBLICAS ═══════════════
  { name: 'Primeiro Passo', description: 'Jogue sua primeira partida oficial.', icon: 'Footprints', rarity: 'comum', category: 'partidas', visibility: 'publico', difficulty: 'facil', trigger_type: 'play_match', threshold: 1, xp_reward: 50, coins_reward: 100, points: 10 },
  { name: 'Estreante Dedicado', description: 'Jogue 10 partidas.', icon: 'Play', rarity: 'comum', category: 'partidas', visibility: 'publico', difficulty: 'facil', trigger_type: 'play_match', threshold: 10, xp_reward: 100, coins_reward: 200, points: 15 },
  { name: 'Veterano de Quadra', description: 'Jogue 50 partidas.', icon: 'Trophy', rarity: 'incomum', category: 'partidas', visibility: 'publico', difficulty: 'medio', trigger_type: 'play_match', threshold: 50, xp_reward: 300, coins_reward: 500, points: 25 },
  { name: 'Centurião', description: 'Jogue 100 partidas.', icon: 'Shield', rarity: 'raro', category: 'partidas', visibility: 'publico', difficulty: 'medio', trigger_type: 'play_match', threshold: 100, xp_reward: 500, coins_reward: 1000, points: 40 },
  { name: 'Maratonista', description: 'Jogue 250 partidas.', icon: 'Activity', rarity: 'épico', category: 'partidas', visibility: 'publico', difficulty: 'dificil', trigger_type: 'play_match', threshold: 250, xp_reward: 1500, coins_reward: 3000, points: 75 },
  { name: 'Lenda das Quadras', description: 'Jogue 500 partidas.', icon: 'Crown', rarity: 'lendário', category: 'partidas', visibility: 'publico', difficulty: 'extremo', trigger_type: 'play_match', threshold: 500, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Maratonista Eterno', points: 150 },
  { name: 'Imortal do Padel', description: 'Jogue 1000 partidas.', icon: 'Infinity', rarity: 'mitico', category: 'partidas', visibility: 'publico', difficulty: 'lendario', trigger_type: 'play_match', threshold: 1000, xp_reward: 20000, coins_reward: 50000, medal_reward: 'Imortal', title_reward: 'O Imortal', points: 500 },

  // Vitórias
  { name: 'Primeira Vitória', description: 'Vença sua primeira partida.', icon: 'Trophy', rarity: 'comum', category: 'partidas', visibility: 'publico', difficulty: 'facil', trigger_type: 'win_match', threshold: 1, xp_reward: 50, coins_reward: 100, points: 10 },
  { name: 'Em Sequência', description: 'Vença 5 partidas seguidas.', icon: 'Flame', rarity: 'incomum', category: 'partidas', visibility: 'publico', difficulty: 'medio', trigger_type: 'win_streak', threshold: 5, xp_reward: 200, coins_reward: 400, points: 20 },
  { name: 'Dominador', description: 'Vença 10 partidas seguidas.', icon: 'Swords', rarity: 'raro', category: 'partidas', visibility: 'publico', difficulty: 'dificil', trigger_type: 'win_streak', threshold: 10, xp_reward: 500, coins_reward: 1000, points: 40 },
  { name: 'Imparável', description: 'Vença 20 partidas seguidas.', icon: 'Zap', rarity: 'épico', category: 'partidas', visibility: 'publico', difficulty: 'extremo', trigger_type: 'win_streak', threshold: 20, xp_reward: 2000, coins_reward: 4000, points: 100 },
  { name: 'Máquina Implacável', description: 'Vença 50 partidas seguidas.', icon: 'Crown', rarity: 'mitico', category: 'partidas', visibility: 'publico', difficulty: 'lendario', trigger_type: 'win_streak', threshold: 50, xp_reward: 15000, coins_reward: 30000, medal_reward: 'Invencível', title_reward: 'O Invencível', points: 400 },

  // Vitórias totais
  { name: 'Vencedor Iniciante', description: 'Vença 25 partidas.', icon: 'Award', rarity: 'comum', category: 'partidas', visibility: 'publico', difficulty: 'facil', trigger_type: 'win_match', threshold: 25, xp_reward: 150, coins_reward: 300, points: 15 },
  { name: 'Competidor', description: 'Vença 100 partidas.', icon: 'Medal', rarity: 'incomum', category: 'partidas', visibility: 'publico', difficulty: 'medio', trigger_type: 'win_match', threshold: 100, xp_reward: 500, coins_reward: 1000, points: 30 },
  { name: 'Campeão Nato', description: 'Vença 250 partidas.', icon: 'Trophy', rarity: 'raro', category: 'partidas', visibility: 'publico', difficulty: 'dificil', trigger_type: 'win_match', threshold: 250, xp_reward: 1500, coins_reward: 3000, points: 60 },
  { name: 'Titan', description: 'Vença 500 partidas.', icon: 'Star', rarity: 'épico', category: 'partidas', visibility: 'publico', difficulty: 'extremo', trigger_type: 'win_match', threshold: 500, xp_reward: 5000, coins_reward: 10000, points: 120 },
  { name: 'Semideus', description: 'Vença 1000 partidas.', icon: 'Sparkles', rarity: 'lendário', category: 'partidas', visibility: 'publico', difficulty: 'lendario', trigger_type: 'win_match', threshold: 1000, xp_reward: 20000, coins_reward: 50000, medal_reward: 'Semideus do Padel', title_reward: 'Semideus', points: 500 },

  // ═══════════════ PARTIDAS — OCULTAS ═══════════════
  { name: 'Virada Épica', description: 'Vença uma partida após estar perdendo por 0-2 em sets.', icon: 'RotateCcw', rarity: 'raro', category: 'partidas', visibility: 'oculto', mystery_description: 'Quando tudo parece perdido, os verdadeiros campeões despertam...', difficulty: 'dificil', trigger_type: 'comeback', threshold: 1, xp_reward: 800, coins_reward: 1500, points: 50 },
  { name: 'Massacre Perfeito', description: 'Vença uma partida sem perder nenhum game (6-0, 6-0).', icon: 'Target', rarity: 'épico', category: 'partidas', visibility: 'oculto', mystery_description: 'Nem mesmo um game. Misericórdia não é uma palavra que existe no seu vocabulário.', difficulty: 'dificil', trigger_type: 'perfect_match', threshold: 1, xp_reward: 1000, coins_reward: 2000, points: 60 },
  { name: 'Resistência Sobre-humana', description: 'Vença uma partida que durou mais de 3 horas.', icon: 'Clock', rarity: 'épico', category: 'partidas', visibility: 'oculto', mystery_description: 'O relógio não é seu inimigo. É seu aliado.', difficulty: 'extremo', trigger_type: 'long_match_win', threshold: 1, xp_reward: 1200, coins_reward: 2500, points: 70 },
  { name: 'Rei do Tie-Break', description: 'Vença 10 tie-breaks.', icon: 'Swords', rarity: 'raro', category: 'partidas', visibility: 'oculto', mystery_description: 'Quando a pressão chega ao máximo, você floresce.', difficulty: 'medio', trigger_type: 'tiebreak_win', threshold: 10, xp_reward: 500, coins_reward: 1000, points: 35 },
  { name: 'Carrasco de Lendas', description: 'Vença uma partida contra um atleta top 10 do ranking.', icon: 'Skull', rarity: 'lendário', category: 'partidas', visibility: 'oculto', mystery_description: 'Os deuses do padel também sangram.', difficulty: 'extremo', trigger_type: 'beat_top10', threshold: 1, xp_reward: 3000, coins_reward: 6000, medal_reward: 'Carrasco', points: 100 },
  { name: 'Destruidor de #1', description: 'Vença uma partida contra o #1 do ranking mundial.', icon: 'Crosshair', rarity: 'mitico', category: 'partidas', visibility: 'oculto', mystery_description: 'O trono tem um novo pretendente.', difficulty: 'lendario', trigger_type: 'beat_rank1', threshold: 1, xp_reward: 10000, coins_reward: 20000, medal_reward: 'Destruidor de Reis', title_reward: 'Destruidor de Reis', points: 300 },
  { name: 'Apostador de Risco', description: 'Vença uma partida usando a tática mais arriscada disponível.', icon: 'Dices', rarity: 'raro', category: 'partidas', visibility: 'oculto', mystery_description: 'A sorte favorece os audazes... ou os destrói.', difficulty: 'dificil', trigger_type: 'risky_tactic_win', threshold: 1, xp_reward: 600, coins_reward: 1200, points: 40 },
  { name: 'Estrategista Silencioso', description: 'Vença 50 partidas sem mudar de tática.', icon: 'Brain', rarity: 'épico', category: 'partidas', visibility: 'oculto', mystery_description: 'A constância é a virtude dos imortais.', difficulty: 'extremo', trigger_type: 'consistent_tactic', threshold: 50, xp_reward: 2000, coins_reward: 4000, points: 80 },

  // ═══════════════ TORNEIOS — PÚBLICAS ═══════════════
  { name: 'Estreia em Torneios', description: 'Participe do seu primeiro torneio.', icon: 'Flag', rarity: 'comum', category: 'torneios', visibility: 'publico', difficulty: 'facil', trigger_type: 'join_tournament', threshold: 1, xp_reward: 100, coins_reward: 200, points: 10 },
  { name: 'Frequentador', description: 'Participe de 10 torneios.', icon: 'Calendar', rarity: 'comum', category: 'torneios', visibility: 'publico', difficulty: 'facil', trigger_type: 'join_tournament', threshold: 10, xp_reward: 300, coins_reward: 500, points: 20 },
  { name: 'Circuitista', description: 'Participe de 25 torneios.', icon: 'Route', rarity: 'incomum', category: 'torneios', visibility: 'publico', difficulty: 'medio', trigger_type: 'join_tournament', threshold: 25, xp_reward: 800, coins_reward: 1500, points: 35 },
  { name: 'Globetrotter', description: 'Participe de 50 torneios.', icon: 'Globe', rarity: 'raro', category: 'torneios', visibility: 'publico', difficulty: 'dificil', trigger_type: 'join_tournament', threshold: 50, xp_reward: 2000, coins_reward: 4000, points: 70 },
  { name: 'Nômade do Padel', description: 'Participe de 100 torneios.', icon: 'Compass', rarity: 'épico', category: 'torneios', visibility: 'publico', difficulty: 'extremo', trigger_type: 'join_tournament', threshold: 100, xp_reward: 5000, coins_reward: 10000, points: 120 },

  // Campeão
  { name: 'Primeiro Título', description: 'Vença seu primeiro torneio.', icon: 'Trophy', rarity: 'incomum', category: 'torneios', visibility: 'publico', difficulty: 'medio', trigger_type: 'win_tournament', threshold: 1, xp_reward: 500, coins_reward: 1000, medal_reward: 'Campeão Iniciante', points: 30 },
  { name: 'Bicampeão', description: 'Vença 2 torneios.', icon: 'Award', rarity: 'incomum', category: 'torneios', visibility: 'publico', difficulty: 'medio', trigger_type: 'win_tournament', threshold: 2, xp_reward: 800, coins_reward: 1500, points: 35 },
  { name: 'Tricampeão', description: 'Vença 3 torneios.', icon: 'Medal', rarity: 'raro', category: 'torneios', visibility: 'publico', difficulty: 'medio', trigger_type: 'win_tournament', threshold: 3, xp_reward: 1200, coins_reward: 2000, points: 45 },
  { name: 'Pentacampeão', description: 'Vença 5 torneios.', icon: 'Star', rarity: 'raro', category: 'torneios', visibility: 'publico', difficulty: 'dificil', trigger_type: 'win_tournament', threshold: 5, xp_reward: 2000, coins_reward: 4000, medal_reward: 'Pentacampeão', points: 60 },
  { name: 'Decacampeão', description: 'Vença 10 torneios.', icon: 'Crown', rarity: 'épico', category: 'torneios', visibility: 'publico', difficulty: 'dificil', trigger_type: 'win_tournament', threshold: 10, xp_reward: 4000, coins_reward: 8000, medal_reward: 'Decacampeão', title_reward: 'O Conquistador', points: 100 },
  { name: 'Vinte Vezes Campeão', description: 'Vença 20 torneios.', icon: 'Sparkles', rarity: 'lendário', category: 'torneios', visibility: 'publico', difficulty: 'extremo', trigger_type: 'win_tournament', threshold: 20, xp_reward: 8000, coins_reward: 16000, medal_reward: 'Lenda dos Torneios', title_reward: 'Lenda dos Torneios', points: 200 },
  { name: 'Imperador', description: 'Vença 50 torneios.', icon: 'Castle', rarity: 'mitico', category: 'torneios', visibility: 'publico', difficulty: 'lendario', trigger_type: 'win_tournament', threshold: 50, xp_reward: 25000, coins_reward: 50000, medal_reward: 'Imperador do Padel', title_reward: 'Imperador', points: 500 },

  // Por tier
  { name: 'Campeão P2', description: 'Vença um torneio tier P2.', icon: 'Award', rarity: 'incomum', category: 'torneios', visibility: 'publico', difficulty: 'medio', trigger_type: 'win_tournament_tier', threshold: 1, xp_reward: 500, coins_reward: 1000, points: 25 },
  { name: 'Campeão P1', description: 'Vença um torneio tier P1.', icon: 'Trophy', rarity: 'raro', category: 'torneios', visibility: 'publico', difficulty: 'dificil', trigger_type: 'win_tournament_tier', threshold: 2, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Campeão Major', description: 'Vença um torneio Major.', icon: 'Crown', rarity: 'épico', category: 'torneios', visibility: 'publico', difficulty: 'extremo', trigger_type: 'win_tournament_tier', threshold: 3, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Campeão Major', points: 120 },
  { name: 'Grão-Campeão', description: 'Vença torneios de todos os tiers (P2, P1 e Major).', icon: 'Castle', rarity: 'lendário', category: 'torneios', visibility: 'publico', difficulty: 'extremo', trigger_type: 'win_all_tiers', threshold: 1, xp_reward: 8000, coins_reward: 15000, medal_reward: 'Grão-Campeão', title_reward: 'Grão-Campeão', points: 200 },

  // ═══════════════ TORNEIOS — OCULTAS ═══════════════
  { name: 'Defesa de Trono', description: 'Vença o mesmo torneio duas vezes seguidas.', icon: 'Shield', rarity: 'épico', category: 'torneios', visibility: 'oculto', mystery_description: 'O trono não foi emprestado. Foi conquistado novamente.', difficulty: 'extremo', trigger_type: 'defend_title', threshold: 1, xp_reward: 3000, coins_reward: 6000, medal_reward: 'Defensor do Trono', points: 90 },
  { name: 'Tríplice Coroa', description: 'Vença 3 torneios Major consecutivos.', icon: 'Crown', rarity: 'mitico', category: 'torneios', visibility: 'oculto', mystery_description: 'Três coroas. Uma cabeça. Consegue suportar o peso?', difficulty: 'lendario', trigger_type: 'triple_major', threshold: 1, xp_reward: 15000, coins_reward: 30000, medal_reward: 'Tríplice Coroa', title_reward: 'Portador da Tríplice Coroa', points: 400 },
  { name: 'Cinderela', description: 'Vença um torneio partindo da última posição do bracket.', icon: 'Sparkles', rarity: 'lendário', category: 'torneios', visibility: 'oculto', mystery_description: 'De último a primeiro. Contos de fadas existem em quadra.', difficulty: 'extremo', trigger_type: 'cinderella_run', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Cinderela', points: 130 },
  { name: 'Dominio Absoluto', description: 'Vença um torneio sem perder nenhum set.', icon: 'Crosshair', rarity: 'lendário', category: 'torneios', visibility: 'oculto', mystery_description: 'Nenhum set cedido. Domínio absoluto.', difficulty: 'extremo', trigger_type: 'flawless_tournament', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Dominador Absoluto', points: 130 },
  { name: 'Gigante em Quadra', description: 'Vença um torneio Major sendo Iniciante.', icon: 'Baby', rarity: 'mitico', category: 'torneios', visibility: 'oculto', mystery_description: 'David venceu Golias. Mas você é mais novo que David.', difficulty: 'lendario', trigger_type: 'major_as_beginner', threshold: 1, xp_reward: 20000, coins_reward: 40000, medal_reward: 'Matador de Gigantes', title_reward: 'Matador de Gigantes', points: 500 },

  // ═══════════════ EVOLUÇÃO — PÚBLICAS ═══════════════
  { name: 'Primeiro Treino', description: 'Complete seu primeiro treino.', icon: 'Dumbbell', rarity: 'comum', category: 'evolução', visibility: 'publico', difficulty: 'facil', trigger_type: 'complete_training', threshold: 1, xp_reward: 50, coins_reward: 100, points: 10 },
  { name: 'Disciplina de Aço', description: 'Complete 50 treinos.', icon: 'Dumbbell', rarity: 'incomum', category: 'evolução', visibility: 'publico', difficulty: 'medio', trigger_type: 'complete_training', threshold: 50, xp_reward: 500, coins_reward: 1000, points: 25 },
  { name: 'Treinador Nato', description: 'Complete 200 treinos.', icon: 'Flame', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'complete_training', threshold: 200, xp_reward: 2000, coins_reward: 4000, points: 60 },
  { name: 'Obcecado', description: 'Complete 500 treinos.', icon: 'Brain', rarity: 'épico', category: 'evolução', visibility: 'publico', difficulty: 'extremo', trigger_type: 'complete_training', threshold: 500, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Obcecado por Treino', points: 120 },
  { name: 'Máquina de Treino', description: 'Complete 1000 treinos.', icon: 'Infinity', rarity: 'lendário', category: 'evolução', visibility: 'publico', difficulty: 'lendario', trigger_type: 'complete_training', threshold: 1000, xp_reward: 20000, coins_reward: 40000, medal_reward: 'Máquina de Treino', title_reward: 'A Máquina', points: 400 },

  // Atributos
  { name: 'Potência Pura', description: 'Alcance 100 em Smash.', icon: 'Zap', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Muralha', description: 'Alcance 100 em Defesa.', icon: 'Shield', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Veloz como o Vento', description: 'Alcance 100 em Agilidade.', icon: 'Wind', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Gênio Tático', description: 'Alcance 100 em Estratégia.', icon: 'Brain', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Coração de Gelo', description: 'Alcance 100 em Controle Emocional.', icon: 'Snowflake', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Saque Bomba', description: 'Alcance 100 em Saque.', icon: 'Rocket', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Direita Mortal', description: 'Alcance 100 em Forehand.', icon: 'Swords', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Esquerda Mágica', description: 'Alcance 100 em Backhand.', icon: 'Sparkles', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Voleador Perfeito', description: 'Alcance 100 em Volley.', icon: 'Target', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },
  { name: 'Mestre da Bandeja', description: 'Alcance 100 em Bandeja.', icon: 'Feather', rarity: 'raro', category: 'evolução', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_attribute', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 50 },

  // ═══════════════ EVOLUÇÃO — OCULTAS ═══════════════
  { name: 'Perfeição Absoluta', description: 'Alcance 100 em TODOS os atributos.', icon: 'Sparkles', rarity: 'mitico', category: 'evolução', visibility: 'oculto', mystery_description: 'A perfeição não é um destino. É você.', difficulty: 'lendario', trigger_type: 'all_max_attributes', threshold: 1, xp_reward: 50000, coins_reward: 100000, medal_reward: 'Perfeição Absoluta', title_reward: 'A Perfeição', exclusive_item: 'Coroa da Perfeição', points: 1000 },
  { name: 'Nível Lenda', description: 'Alcance o nível Lenda.', icon: 'Crown', rarity: 'lendário', category: 'evolução', visibility: 'oculto', mystery_description: 'Poucos chegam aqui. Menos ainda continuam.', difficulty: 'extremo', trigger_type: 'reach_level', threshold: 5, xp_reward: 10000, coins_reward: 20000, medal_reward: 'Lenda Viva', title_reward: 'Lenda Viva', points: 250 },
  { name: 'Ascensão Meteórica', description: 'Alcance o nível Competitivo em menos de 30 dias de carreira.', icon: 'Rocket', rarity: 'épico', category: 'evolução', visibility: 'oculto', mystery_description: 'Alguns nascem para a grandeza. Outros correm até ela.', difficulty: 'extremo', trigger_type: 'fast_level_up', threshold: 1, xp_reward: 3000, coins_reward: 6000, points: 80 },
  { name: 'Polivalente', description: 'Maximize atributos de ataque e defesa simultaneamente.', icon: 'Scale', rarity: 'épico', category: 'evolução', visibility: 'oculto', mystery_description: 'Equilíbrio entre espada e escudo. Raro é quem domina ambos.', difficulty: 'extremo', trigger_type: 'hybrid_max', threshold: 1, xp_reward: 2500, coins_reward: 5000, points: 70 },

  // ═══════════════ SOCIAL — PÚBLICAS ═══════════════
  { name: 'Social Butterfly', description: 'Faça 10 amigos no circuito.', icon: 'Users', rarity: 'comum', category: 'social', visibility: 'publico', difficulty: 'facil', trigger_type: 'make_friend', threshold: 10, xp_reward: 200, coins_reward: 400, points: 15 },
  { name: 'Popular', description: 'Faça 25 amigos.', icon: 'Heart', rarity: 'incomum', category: 'social', visibility: 'publico', difficulty: 'medio', trigger_type: 'make_friend', threshold: 25, xp_reward: 600, coins_reward: 1200, points: 30 },
  { name: 'Ímã de Pessoas', description: 'Faça 50 amigos.', icon: 'Sparkles', rarity: 'raro', category: 'social', visibility: 'publico', difficulty: 'dificil', trigger_type: 'make_friend', threshold: 50, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Rival Eterno', description: 'Desenvolva uma rivalidade intensa com outro atleta.', icon: 'Swords', rarity: 'incomum', category: 'social', visibility: 'publico', difficulty: 'medio', trigger_type: 'create_rivalry', threshold: 1, xp_reward: 400, coins_reward: 800, points: 25 },
  { name: 'Mentor', description: 'Torne-se mentor de um atleta mais jovem.', icon: 'GraduationCap', rarity: 'raro', category: 'social', visibility: 'publico', difficulty: 'dificil', trigger_type: 'become_mentor', threshold: 1, xp_reward: 800, coins_reward: 1500, points: 40 },
  { name: 'Química Perfeita', description: 'Alcance 100 de química com seu parceiro de dupla.', icon: 'Heart', rarity: 'épico', category: 'social', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_chemistry', threshold: 100, xp_reward: 2000, coins_reward: 4000, medal_reward: 'Dupla Perfeita', points: 80 },
  { name: 'Parceiro para a Vida', description: 'Mantenha o mesmo parceiro por 100 partidas.', icon: 'Handshake', rarity: 'lendário', category: 'social', visibility: 'publico', difficulty: 'extremo', trigger_type: 'long_partner', threshold: 100, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Parceiro Eterno', title_reward: 'Parceiro Eterno', points: 120 },

  // ═══════════════ SOCIAL — OCULTAS ═══════════════
  { name: 'Coração Partido', description: 'Termine uma parceria de longa data.', icon: 'HeartCrack', rarity: 'raro', category: 'social', visibility: 'oculto', mystery_description: 'Todas as grandes histórias têm um fim triste.', difficulty: 'medio', trigger_type: 'end_partnership', threshold: 1, xp_reward: 500, coins_reward: 1000, points: 30 },
  { name: 'Inimigo Íntimo', description: 'Tenha um relacionamento com score de -100 com um atleta.', icon: 'Skull', rarity: 'épico', category: 'social', visibility: 'oculto', mystery_description: 'Do ódio ao inimigo íntimo, há apenas um passo.', difficulty: 'dificil', trigger_type: 'max_hate', threshold: 1, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Pacificador', description: 'Transforme 5 inimigos em amigos.', icon: 'Bird', rarity: 'épico', category: 'social', visibility: 'oculto', mystery_description: 'A verdadeira força não está em vencer, mas em reconciliar.', difficulty: 'extremo', trigger_type: 'reconcile', threshold: 5, xp_reward: 2500, coins_reward: 5000, medal_reward: 'Pacificador', points: 80 },
  { name: 'Líder de Torcida', description: 'Tença uma torcida com mais de 1 milhão de torcedores.', icon: 'Megaphone', rarity: 'lendário', category: 'social', visibility: 'oculto', mystery_description: 'Multidões não seguem qualquer um. Seguem lendas.', difficulty: 'extremo', trigger_type: 'mega_fanbase', threshold: 1000000, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Líder de Multidões', points: 130 },
  { name: 'Viral', description: 'Tenha um post com mais de 100k curtidas.', icon: 'Flame', rarity: 'raro', category: 'social', visibility: 'oculto', mystery_description: 'O algoritmo escolheu você.', difficulty: 'dificil', trigger_type: 'viral_post', threshold: 100000, xp_reward: 1000, coins_reward: 2000, points: 40 },

  // ═══════════════ ECONOMIA — PÚBLICAS ═══════════════
  { name: 'Primeiro Lucro', description: 'Acumule 5.000 moedas.', icon: 'Coins', rarity: 'comum', category: 'economia', visibility: 'publico', difficulty: 'facil', trigger_type: 'reach_coins', threshold: 5000, xp_reward: 100, coins_reward: 0, points: 15 },
  { name: 'Confortável', description: 'Acumule 50.000 moedas.', icon: 'Wallet', rarity: 'incomum', category: 'economia', visibility: 'publico', difficulty: 'medio', trigger_type: 'reach_coins', threshold: 50000, xp_reward: 500, coins_reward: 0, points: 30 },
  { name: 'Rico', description: 'Acumule 250.000 moedas.', icon: 'Gem', rarity: 'raro', category: 'economia', visibility: 'publico', difficulty: 'dificil', trigger_type: 'reach_coins', threshold: 250000, xp_reward: 2000, coins_reward: 0, points: 60 },
  { name: 'Milionário', description: 'Acumule 1.000.000 de moedas.', icon: 'Landmark', rarity: 'épico', category: 'economia', visibility: 'publico', difficulty: 'extremo', trigger_type: 'reach_coins', threshold: 1000000, xp_reward: 10000, coins_reward: 0, medal_reward: 'Milionário', title_reward: 'Milionário', points: 150 },
  { name: 'Magnata', description: 'Acumule 5.000.000 de moedas.', icon: 'Crown', rarity: 'lendário', category: 'economia', visibility: 'publico', difficulty: 'lendario', trigger_type: 'reach_coins', threshold: 5000000, xp_reward: 50000, coins_reward: 0, medal_reward: 'Magnata do Padel', title_reward: 'Magnata', points: 400 },

  // Propriedades
  { name: 'Primeiro Imóvel', description: 'Compre sua primeira propriedade.', icon: 'Home', rarity: 'comum', category: 'economia', visibility: 'publico', difficulty: 'facil', trigger_type: 'buy_property', threshold: 1, xp_reward: 200, coins_reward: 500, points: 15 },
  { name: 'Empresário', description: 'Possua 5 propriedades.', icon: 'Building2', rarity: 'raro', category: 'economia', visibility: 'publico', difficulty: 'dificil', trigger_type: 'buy_property', threshold: 5, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Magnata Imobiliário', description: 'Possua 10 propriedades.', icon: 'Castle', rarity: 'épico', category: 'economia', visibility: 'publico', difficulty: 'extremo', trigger_type: 'buy_property', threshold: 10, xp_reward: 4000, coins_reward: 8000, medal_reward: 'Magnata Imobiliário', points: 100 },

  // Investimentos
  { name: 'Investidor', description: 'Faça seu primeiro investimento.', icon: 'TrendingUp', rarity: 'comum', category: 'economia', visibility: 'publico', difficulty: 'facil', trigger_type: 'make_investment', threshold: 1, xp_reward: 200, coins_reward: 300, points: 15 },
  { name: 'Especulador', description: 'Tenha 5 investimentos ativos.', icon: 'BarChart3', rarity: 'incomum', category: 'economia', visibility: 'publico', difficulty: 'medio', trigger_type: 'make_investment', threshold: 5, xp_reward: 800, coins_reward: 1500, points: 30 },
  { name: 'Wall Street do Padel', description: 'Tenha 10 investimentos ativos.', icon: 'LineChart', rarity: 'raro', category: 'economia', visibility: 'publico', difficulty: 'dificil', trigger_type: 'make_investment', threshold: 10, xp_reward: 2000, coins_reward: 4000, points: 50 },

  // Patrocinadores
  { name: 'Primeiro Patrocinador', description: 'Assine seu primeiro contrato de patrocínio.', icon: 'Star', rarity: 'comum', category: 'economia', visibility: 'publico', difficulty: 'facil', trigger_type: 'sign_sponsor', threshold: 1, xp_reward: 200, coins_reward: 500, points: 15 },
  { name: 'Cobiçado', description: 'Tenha 3 patrocinadores ativos simultaneamente.', icon: 'Award', rarity: 'raro', category: 'economia', visibility: 'publico', difficulty: 'dificil', trigger_type: 'multi_sponsor', threshold: 3, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Embaixador', description: 'Tenha um contrato com um patrocinador Ouro.', icon: 'Crown', rarity: 'épico', category: 'economia', visibility: 'publico', difficulty: 'extremo', trigger_type: 'gold_sponsor', threshold: 1, xp_reward: 3000, coins_reward: 6000, medal_reward: 'Embaixador de Marca', points: 80 },

  // ═══════════════ ECONOMIA — OCULTAS ═══════════════
  { name: 'Comprador Compulsivo', description: 'Gaste 500.000 moedas em um único dia.', icon: 'ShoppingBag', rarity: 'épico', category: 'economia', visibility: 'oculto', mystery_description: 'O dinheiro queima nos seus bolsos... e você adora isso.', difficulty: 'extremo', trigger_type: 'spending_spree', threshold: 500000, xp_reward: 3000, coins_reward: 0, points: 80 },
  { name: 'Negociador Implacável', description: 'Negocie um contrato com 50% de desconto.', icon: 'Handshake', rarity: 'raro', category: 'economia', visibility: 'oculto', mystery_description: 'O dinheiro fica com quem sabe pedir.', difficulty: 'dificil', trigger_type: 'great_deal', threshold: 50, xp_reward: 1000, coins_reward: 2000, points: 40 },
  { name: 'Falido e Renascido', description: 'Fique com 0 moedas e recupere para 100.000+.', icon: 'RotateCcw', rarity: 'épico', category: 'economia', visibility: 'oculto', mystery_description: 'Do fundo do poço ao topo. A história favorita de todos.', difficulty: 'extremo', trigger_type: 'bankruptcy_recovery', threshold: 1, xp_reward: 2500, coins_reward: 5000, medal_reward: 'Fênix Financeira', points: 80 },

  // ═══════════════ MERCADO — OCULTAS ═══════════════
  { name: 'Caçador de Barganhas', description: 'Compre 10 itens durante Flash Sales.', icon: 'Zap', rarity: 'incomum', category: 'mercado', visibility: 'oculto', mystery_description: 'Oportunidades surgem como relâmpagos. Apanhe-as.', difficulty: 'medio', trigger_type: 'buy_flash_sale', threshold: 10, xp_reward: 500, coins_reward: 1000, points: 25 },
  { name: 'Investidor de Mercado', description: 'Compre um item em baixa e venda com 200% de lucro.', icon: 'TrendingUp', rarity: 'raro', category: 'mercado', visibility: 'oculto', mystery_description: 'Compre na baixa, venda na alta. A regra eterna.', difficulty: 'dificil', trigger_type: 'market_profit', threshold: 200, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Colecionador de Relíquias', description: 'Compre um item histórico (Padel Heritage).', icon: 'Crown', rarity: 'lendário', category: 'mercado', visibility: 'oculto', mystery_description: 'Alguns itens carregam a alma do esporte.', difficulty: 'extremo', trigger_type: 'buy_historical', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Guardião da História', points: 120 },
  { name: 'Todos os Heritage', description: 'Possua todos os 10 itens históricos.', icon: 'Castle', rarity: 'mitico', category: 'mercado', visibility: 'oculto', mystery_description: 'Você não coleciona itens. Você protege a memória do padel.', difficulty: 'lendario', trigger_type: 'all_historical', threshold: 10, xp_reward: 50000, coins_reward: 100000, medal_reward: 'Guardião do Padel', title_reward: 'Guardião do Padel', exclusive_item: 'Manto do Guardião', points: 1000 },
  { name: 'Comprador de Pânico', description: 'Compre um item durante um evento de escassez.', icon: 'Flame', rarity: 'raro', category: 'mercado', visibility: 'oculto', mystery_description: 'Quando todos correm, você compra. Quando todos compram, você corre.', difficulty: 'dificil', trigger_type: 'buy_scarce', threshold: 1, xp_reward: 800, coins_reward: 1500, points: 35 },
  { name: 'Oportunista', description: 'Compre 5 itens com mais de 50% de desconto.', icon: 'Target', rarity: 'raro', category: 'mercado', visibility: 'oculto', mystery_description: 'O timing é tudo. E você tem o timing perfeito.', difficulty: 'dificil', trigger_type: 'buy_deep_discount', threshold: 5, xp_reward: 1000, coins_reward: 2000, points: 40 },

  // ═══════════════ COLEÇÃO — PÚBLICAS ═══════════════
  { name: 'Primeira Compra', description: 'Compre seu primeiro item na loja.', icon: 'ShoppingBag', rarity: 'comum', category: 'coleção', visibility: 'publico', difficulty: 'facil', trigger_type: 'buy_item', threshold: 1, xp_reward: 50, coins_reward: 100, points: 10 },
  { name: 'Colecionador', description: 'Possua 25 itens diferentes.', icon: 'Package', rarity: 'incomum', category: 'coleção', visibility: 'publico', difficulty: 'medio', trigger_type: 'own_items', threshold: 25, xp_reward: 500, coins_reward: 1000, points: 25 },
  { name: 'Acumulador', description: 'Possua 50 itens diferentes.', icon: 'Boxes', rarity: 'raro', category: 'coleção', visibility: 'publico', difficulty: 'dificil', trigger_type: 'own_items', threshold: 50, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Museu Pessoal', description: 'Possua 100 itens diferentes.', icon: 'Landmark', rarity: 'épico', category: 'coleção', visibility: 'publico', difficulty: 'extremo', trigger_type: 'own_items', threshold: 100, xp_reward: 4000, coins_reward: 8000, medal_reward: 'Colecionador Mestre', points: 100 },
  { name: 'Arsenal Completo', description: 'Possua 250 itens diferentes.', icon: 'Castle', rarity: 'lendário', category: 'coleção', visibility: 'publico', difficulty: 'lendario', trigger_type: 'own_items', threshold: 250, xp_reward: 15000, coins_reward: 30000, medal_reward: 'Arsenal Completo', title_reward: 'O Colecionador', points: 300 },

  // Por raridade
  { name: 'Toque de Midas', description: 'Possua 1 item lendário.', icon: 'Crown', rarity: 'raro', category: 'coleção', visibility: 'publico', difficulty: 'medio', trigger_type: 'own_legendary', threshold: 1, xp_reward: 500, coins_reward: 1000, points: 30 },
  { name: 'Rei Mida', description: 'Possua 10 itens lendários.', icon: 'Gem', rarity: 'épico', category: 'coleção', visibility: 'publico', difficulty: 'dificil', trigger_type: 'own_legendary', threshold: 10, xp_reward: 2500, coins_reward: 5000, points: 60 },
  { name: 'Mito Vivo', description: 'Possua 1 item mítico.', icon: 'Sparkles', rarity: 'lendário', category: 'coleção', visibility: 'publico', difficulty: 'extremo', trigger_type: 'own_mythic', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Portador de Mitos', points: 120 },
  { name: 'Exclusividade', description: 'Possua 1 item exclusivo.', icon: 'Diamond', rarity: 'lendário', category: 'coleção', visibility: 'publico', difficulty: 'extremo', trigger_type: 'own_exclusive', threshold: 1, xp_reward: 5000, coins_reward: 10000, points: 120 },

  // Por categoria
  { name: 'Armeiro', description: 'Possua 20 raquetes diferentes.', icon: 'Disc', rarity: 'raro', category: 'coleção', visibility: 'publico', difficulty: 'medio', trigger_type: 'own_rackets', threshold: 20, xp_reward: 800, coins_reward: 1500, points: 35 },
  { name: 'Sapateiro', description: 'Possua 10 pares de tênis diferentes.', icon: 'Footprints', rarity: 'incomum', category: 'coleção', visibility: 'publico', difficulty: 'medio', trigger_type: 'own_shoes', threshold: 10, xp_reward: 600, coins_reward: 1200, points: 30 },
  { name: 'Guarda-Roupa', description: 'Possua 15 peças de vestuário.', icon: 'Shirt', rarity: 'incomum', category: 'coleção', visibility: 'publico', difficulty: 'medio', trigger_type: 'own_apparel', threshold: 15, xp_reward: 600, coins_reward: 1200, points: 30 },
  { name: 'Tecnólogo', description: 'Possua 5 acessórios tecnológicos.', icon: 'Zap', rarity: 'raro', category: 'coleção', visibility: 'publico', difficulty: 'dificil', trigger_type: 'own_tech', threshold: 5, xp_reward: 1000, coins_reward: 2000, points: 40 },

  // ═══════════════ COLEÇÃO — OCULTAS ═══════════════
  { name: 'Fabricante Fiel', description: 'Possua 10 itens da mesma marca.', icon: 'Star', rarity: 'raro', category: 'coleção', visibility: 'oculto', mystery_description: 'Lealdade às marcas tem suas recompensas.', difficulty: 'medio', trigger_type: 'brand_loyalty', threshold: 10, xp_reward: 800, coins_reward: 1500, points: 35 },
  { name: 'Pau para Toda Obra', description: 'Possua pelo menos 1 item de cada categoria.', icon: 'Package', rarity: 'incomum', category: 'coleção', visibility: 'oculto', mystery_description: 'Versatilidade é o seu segundo nome.', difficulty: 'medio', trigger_type: 'all_categories', threshold: 1, xp_reward: 600, coins_reward: 1200, points: 30 },
  { name: 'Rainbow Collection', description: 'Possua 1 item de cada raridade.', icon: 'Rainbow', rarity: 'épico', category: 'coleção', visibility: 'oculto', mystery_description: 'Do comum ao exclusivo. O arco-íris completo.', difficulty: 'dificil', trigger_type: 'all_rarities', threshold: 1, xp_reward: 2000, coins_reward: 4000, medal_reward: 'Colecionador Arco-Íris', points: 70 },
  { name: 'Durabilidade Zero', description: 'Use um item até que sua durabilidade chegue a 0.', icon: 'Trash2', rarity: 'incomum', category: 'coleção', visibility: 'oculto', mystery_description: 'Você usou até a última gota. Literamente.', difficulty: 'medio', trigger_type: 'item_broken', threshold: 1, xp_reward: 300, coins_reward: 600, points: 20 },
  { name: 'Veterano de Equipamentos', description: 'Equipe o mesmo item por 100 partidas.', icon: 'Shield', rarity: 'raro', category: 'coleção', visibility: 'oculto', mystery_description: 'Há histórias gravadas nesse equipamento.', difficulty: 'dificil', trigger_type: 'long_equipped', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 40 },

  // ═══════════════ HISTÓRIA — PÚBLICAS ═══════════════
  { name: 'Estudante de História', description: 'Leia 10 entradas da história do padel.', icon: 'BookOpen', rarity: 'comum', category: 'história', visibility: 'publico', difficulty: 'facil', trigger_type: 'read_history', threshold: 10, xp_reward: 200, coins_reward: 400, points: 15 },
  { name: 'Historiador', description: 'Leia todas as entradas da história do padel.', icon: 'ScrollText', rarity: 'raro', category: 'história', visibility: 'publico', difficulty: 'medio', trigger_type: 'read_history', threshold: 39, xp_reward: 1000, coins_reward: 2000, points: 40 },
  { name: 'Visitante do Hall da Fama', description: 'Visite o Hall da Fama pela primeira vez.', icon: 'Star', rarity: 'comum', category: 'história', visibility: 'publico', difficulty: 'facil', trigger_type: 'visit_hof', threshold: 1, xp_reward: 100, coins_reward: 200, points: 10 },
  { name: 'Estudioso das Lendas', description: 'Leia a biografia de 5 lendas do Hall da Fama.', icon: 'Crown', rarity: 'incomum', category: 'história', visibility: 'publico', difficulty: 'medio', trigger_type: 'read_hof_bio', threshold: 5, xp_reward: 500, coins_reward: 1000, points: 25 },
  { name: 'Especialista em Lendas', description: 'Leia todas as biografias do Hall da Fama.', icon: 'Sparkles', rarity: 'raro', category: 'história', visibility: 'publico', difficulty: 'dificil', trigger_type: 'read_hof_bio', threshold: 20, xp_reward: 2000, coins_reward: 4000, points: 50 },

  // ═══════════════ HISTÓRIA — OCULTAS ═══════════════
  { name: 'Guardião da Memória', description: 'Possua todos os itens da coleção Padel Origins.', icon: 'Crown', rarity: 'mitico', category: 'história', visibility: 'oculto', mystery_description: 'Você não apenas joga padel. Você preserva sua alma.', difficulty: 'lendario', trigger_type: 'all_origins', threshold: 7, xp_reward: 30000, coins_reward: 60000, medal_reward: 'Guardião da Memória', title_reward: 'Guardião da Memória', points: 500 },
  { name: 'Conhece os Fundadores', description: 'Leia a entrada sobre Enrique Corcuera (1969).', icon: 'BookOpen', rarity: 'incomum', category: 'história', visibility: 'oculto', mystery_description: 'Tudo começa em algum lugar. Você sabe onde.', difficulty: 'facil', trigger_type: 'read_founder', threshold: 1, xp_reward: 300, coins_reward: 600, points: 20 },
  { name: 'Especialista em Décadas', description: 'Leia entradas de todas as décadas (1960-2020).', icon: 'Clock', rarity: 'raro', category: 'história', visibility: 'oculto', mystery_description: 'Sete décadas de história. Você conhece todas.', difficulty: 'medio', trigger_type: 'all_decades', threshold: 7, xp_reward: 1000, coins_reward: 2000, points: 40 },

  // ═══════════════ CARREIRA — PÚBLICAS ═══════════════
  { name: 'Nascido para Vencer', description: 'Crie seu perfil de jogador.', icon: 'User', rarity: 'comum', category: 'carreira', visibility: 'publico', difficulty: 'facil', trigger_type: 'create_profile', threshold: 1, xp_reward: 50, coins_reward: 100, points: 10 },
  { name: 'Primeiro Dia', description: 'Avance o dia pela primeira vez.', icon: 'Calendar', rarity: 'comum', category: 'carreira', visibility: 'publico', difficulty: 'facil', trigger_type: 'advance_day', threshold: 1, xp_reward: 50, coins_reward: 100, points: 10 },
  { name: 'Uma Semana', description: 'Avance 7 dias de carreira.', icon: 'Calendar', rarity: 'comum', category: 'carreira', visibility: 'publico', difficulty: 'facil', trigger_type: 'advance_day', threshold: 7, xp_reward: 100, coins_reward: 200, points: 15 },
  { name: 'Um Mês', description: 'Avance 30 dias de carreira.', icon: 'Calendar', rarity: 'incomum', category: 'carreira', visibility: 'publico', difficulty: 'facil', trigger_type: 'advance_day', threshold: 30, xp_reward: 300, coins_reward: 500, points: 25 },
  { name: 'Um Ano', description: 'Avance 365 dias de carreira.', icon: 'Calendar', rarity: 'raro', category: 'carreira', visibility: 'publico', difficulty: 'medio', trigger_type: 'advance_day', threshold: 365, xp_reward: 2000, coins_reward: 4000, points: 60 },
  { name: 'Meia Década', description: 'Avance 1825 dias (5 anos) de carreira.', icon: 'Clock', rarity: 'épico', category: 'carreira', visibility: 'publico', difficulty: 'dificil', trigger_type: 'advance_day', threshold: 1825, xp_reward: 8000, coins_reward: 16000, medal_reward: 'Veterano de 5 Anos', points: 150 },
  { name: 'Década de Carreira', description: 'Avance 3650 dias (10 anos) de carreira.', icon: 'Infinity', rarity: 'lendário', category: 'carreira', visibility: 'publico', difficulty: 'extremo', trigger_type: 'advance_day', threshold: 3650, xp_reward: 30000, coins_reward: 60000, medal_reward: 'Década de Dedicação', title_reward: 'Veterano de Década', points: 300 },

  // Idade
  { name: 'Auge', description: 'Alcance a idade de 28 anos (pico físico).', icon: 'Flame', rarity: 'incomum', category: 'carreira', visibility: 'publico', difficulty: 'medio', trigger_type: 'reach_age', threshold: 28, xp_reward: 500, coins_reward: 1000, points: 25 },
  { name: 'Veterano', description: 'Alcance a idade de 35 anos.', icon: 'Shield', rarity: 'raro', category: 'carreira', visibility: 'publico', difficulty: 'dificil', trigger_type: 'reach_age', threshold: 35, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Lenda Madura', description: 'Alcance a idade de 40 anos.', icon: 'Crown', rarity: 'épico', category: 'carreira', visibility: 'publico', difficulty: 'extremo', trigger_type: 'reach_age', threshold: 40, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Lenda Madura', points: 100 },

  // Rank
  { name: 'Top 100', description: 'Alcance o top 100 do ranking mundial.', icon: 'TrendingUp', rarity: 'incomum', category: 'carreira', visibility: 'publico', difficulty: 'medio', trigger_type: 'reach_rank', threshold: 100, xp_reward: 800, coins_reward: 1500, points: 30 },
  { name: 'Top 50', description: 'Alcance o top 50 do ranking mundial.', icon: 'TrendingUp', rarity: 'raro', category: 'carreira', visibility: 'publico', difficulty: 'dificil', trigger_type: 'reach_rank', threshold: 50, xp_reward: 2000, coins_reward: 4000, points: 50 },
  { name: 'Top 10', description: 'Alcance o top 10 do ranking mundial.', icon: 'Star', rarity: 'épico', category: 'carreira', visibility: 'publico', difficulty: 'extremo', trigger_type: 'reach_rank', threshold: 10, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Top 10 Mundial', title_reward: 'Top 10 Mundial', points: 120 },
  { name: 'Top 3', description: 'Alcance o top 3 do ranking mundial.', icon: 'Crown', rarity: 'lendário', category: 'carreira', visibility: 'publico', difficulty: 'extremo', trigger_type: 'reach_rank', threshold: 3, xp_reward: 10000, coins_reward: 20000, medal_reward: 'Pódio Mundial', title_reward: 'Pódio Mundial', points: 200 },
  { name: 'Número 1 do Mundo', description: 'Seja o #1 do ranking mundial.', icon: 'Castle', rarity: 'mitico', category: 'carreira', visibility: 'publico', difficulty: 'lendario', trigger_type: 'reach_rank', threshold: 1, xp_reward: 50000, coins_reward: 100000, medal_reward: '#1 do Mundo', title_reward: '#1 do Mundo', exclusive_item: 'Coroa de #1', points: 1000 },

  // Lesões
  { name: 'Indestrutível', description: 'Jogue 100 partidas sem se lesionar.', icon: 'Shield', rarity: 'raro', category: 'carreira', visibility: 'publico', difficulty: 'dificil', trigger_type: 'injury_free', threshold: 100, xp_reward: 1000, coins_reward: 2000, points: 40 },
  { name: 'Fênix', description: 'Recupere-se de 5 lesões diferentes.', icon: 'Flame', rarity: 'incomum', category: 'carreira', visibility: 'publico', difficulty: 'medio', trigger_type: 'recover_injury', threshold: 5, xp_reward: 500, coins_reward: 1000, points: 25 },

  // Energia
  { name: 'Maratonista de Energia', description: 'Mantenha 100% de energia por 7 dias seguidos.', icon: 'Battery', rarity: 'incomum', category: 'carreira', visibility: 'publico', difficulty: 'medio', trigger_type: 'full_energy_streak', threshold: 7, xp_reward: 500, coins_reward: 1000, points: 25 },

  // Treinador
  { name: 'Encontrou um Guia', description: 'Contrate seu primeiro treinador.', icon: 'GraduationCap', rarity: 'comum', category: 'carreira', visibility: 'publico', difficulty: 'facil', trigger_type: 'hire_coach', threshold: 1, xp_reward: 200, coins_reward: 400, points: 15 },
  { name: 'Relação de Confiança', description: 'Alcance 100 de afinidade com seu treinador.', icon: 'Heart', rarity: 'raro', category: 'carreira', visibility: 'publico', difficulty: 'dificil', trigger_type: 'max_coach_affinity', threshold: 100, xp_reward: 1500, coins_reward: 3000, points: 50 },
  { name: 'Mestre e Aprendiz', description: 'Mantenha o mesmo treinador por 500 dias.', icon: 'Handshake', rarity: 'épico', category: 'carreira', visibility: 'publico', difficulty: 'extremo', trigger_type: 'long_coach', threshold: 500, xp_reward: 4000, coins_reward: 8000, medal_reward: 'Dinastia de Treino', points: 100 },

  // Centro de Treino
  { name: 'Investidor em Infraestrutura', description: 'Faça o primeiro upgrade no centro de treino.', icon: 'Building2', rarity: 'comum', category: 'carreira', visibility: 'publico', difficulty: 'facil', trigger_type: 'upgrade_facility', threshold: 1, xp_reward: 200, coins_reward: 400, points: 15 },
  { name: 'Instalações de Elite', description: 'Eleve todas as instalações ao nível máximo.', icon: 'Castle', rarity: 'lendário', category: 'carreira', visibility: 'publico', difficulty: 'extremo', trigger_type: 'max_all_facilities', threshold: 1, xp_reward: 10000, coins_reward: 20000, medal_reward: 'Instalações de Elite', points: 200 },

  // ═══════════════ CARREIRA — OCULTAS ═══════════════
  { name: 'Geração de Legado', description: 'Aposente-se e inicie uma nova geração de carreira.', icon: 'RotateCcw', rarity: 'épico', category: 'carreira', visibility: 'oculto', mystery_description: 'O fim é apenas o começo de uma nova história.', difficulty: 'extremo', trigger_type: 'retire', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: 'Fundador de Dinastia', points: 120 },
  { name: 'Dinastia', description: 'Complete 3 gerações de carreira.', icon: 'Castle', rarity: 'lendário', category: 'carreira', visibility: 'oculto', mystery_description: 'Três gerações. Um legado eterno.', difficulty: 'lendario', trigger_type: 'generations', threshold: 3, xp_reward: 25000, coins_reward: 50000, medal_reward: 'Fundador de Dinastia', title_reward: 'Patriarca', points: 400 },
  { name: 'Legado Eterno', description: 'Complete 5 gerações de carreira.', icon: 'Infinity', rarity: 'mitico', category: 'carreira', visibility: 'oculto', mystery_description: 'Cinco vidas. Cinco histórias. Um nome imortal.', difficulty: 'lendario', trigger_type: 'generations', threshold: 5, xp_reward: 100000, coins_reward: 200000, medal_reward: 'Legado Eterno', title_reward: 'O Eterno', exclusive_item: 'Manto da Eternidade', points: 1000 },

  // ═══════════════ SECRETO — Totalmente invisíveis até desbloquear ═══════════════
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_1', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: '???', hint: 'Há algo escondido nas profundezas da loja...', is_revealed_hint: false, points: 200 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_2', threshold: 1, xp_reward: 5000, coins_reward: 10000, medal_reward: '???', hint: 'O Hall da Fama esconde segredos que poucos olhos podem ver...', is_revealed_hint: false, points: 200 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_3', threshold: 1, xp_reward: 8000, coins_reward: 15000, medal_reward: '???', hint: 'Há rivalidades que transcendem o tempo...', is_revealed_hint: false, points: 250 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_4', threshold: 1, xp_reward: 10000, coins_reward: 20000, medal_reward: '???', hint: 'O número 7 aparece em lugares inesperados...', is_revealed_hint: false, points: 300 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_5', threshold: 1, xp_reward: 15000, coins_reward: 30000, medal_reward: '???', hint: 'Talvez você precise perder tudo para encontrar algo...', is_revealed_hint: false, points: 350 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_6', threshold: 1, xp_reward: 20000, coins_reward: 40000, medal_reward: '???', hint: 'Existe um item que não está à venda... ou está?', is_revealed_hint: false, points: 400 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_7', threshold: 1, xp_reward: 50000, coins_reward: 100000, medal_reward: '???', title_reward: '???', exclusive_item: '???', hint: 'A perfeição absoluta abre portas que poucos sabem que existem...', is_revealed_hint: false, points: 1000 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_8', threshold: 1, xp_reward: 30000, coins_reward: 60000, medal_reward: '???', hint: 'A resposta está nos números. 1969, 1992, 2024...', is_revealed_hint: false, points: 600 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_9', threshold: 1, xp_reward: 10000, coins_reward: 20000, medal_reward: '???', hint: 'Às vezes, não fazer nada é a maior conquista de todas...', is_revealed_hint: false, points: 250 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_10', threshold: 1, xp_reward: 25000, coins_reward: 50000, medal_reward: '???', hint: 'Existe um jornalista que sabe mais do que deveria...', is_revealed_hint: false, points: 500 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_11', threshold: 1, xp_reward: 15000, coins_reward: 30000, medal_reward: '???', hint: 'Alguns traços de personalidade escondem poderes ocultos...', is_revealed_hint: false, points: 300 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_12', threshold: 1, xp_reward: 20000, coins_reward: 40000, medal_reward: '???', hint: 'O mercado tem memória. Ele lembra de quem o dominou...', is_revealed_hint: false, points: 400 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_13', threshold: 1, xp_reward: 12000, coins_reward: 25000, medal_reward: '???', hint: 'Há uma torcida que ninguém viu nascer, mas todos ouviram...', is_revealed_hint: false, points: 300 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_14', threshold: 1, xp_reward: 18000, coins_reward: 35000, medal_reward: '???', hint: '0-40. 0-40. Jogue. Pense. Existe um caminho...', is_revealed_hint: false, points: 350 },
  { name: '???', description: 'Desbloqueie para revelar.', icon: 'HelpCircle', rarity: 'exclusivo', category: 'secreto', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'secret_15', threshold: 1, xp_reward: 40000, coins_reward: 80000, medal_reward: '???', title_reward: '???', exclusive_item: '???', hint: 'A história se repete para quem não a estuda. Mas para quem a vive?', is_revealed_hint: false, points: 800 },

  // ═══════════════ LENDÁRIO — Conquistas extremas ═══════════════
  { name: 'Grande Slam do Padel', description: 'Vença 4 torneios Major em uma temporada.', icon: 'Crown', rarity: 'mitico', category: 'lendário', visibility: 'oculto', mystery_description: 'Quatro Majors. Uma temporada. Impossível? Para alguns.', difficulty: 'lendario', trigger_type: 'grand_slam', threshold: 1, xp_reward: 50000, coins_reward: 100000, medal_reward: 'Grande Slam', title_reward: 'Grande Slam', exclusive_item: 'Troféu Grande Slam', points: 1000 },
  { name: 'Temporada Perfeita', description: 'Vença todos os torneios de uma temporada.', icon: 'Sparkles', rarity: 'mitico', category: 'lendário', visibility: 'oculto', mystery_description: 'Derrotas? Nunca ouvi falar.', difficulty: 'lendario', trigger_type: 'perfect_season', threshold: 1, xp_reward: 100000, coins_reward: 200000, medal_reward: 'Temporada Perfeita', title_reward: 'A Perfeição', exclusive_item: 'Coroa da Perfeição', points: 1500 },
  { name: 'Rainha de Duplas', description: 'Vença 100 partidas com a mesma dupla sem perder.', icon: 'Heart', rarity: 'mitico', category: 'lendário', visibility: 'oculto', mystery_description: 'Duas mentes. Um coração. Cem vitórias.', difficulty: 'lendario', trigger_type: 'perfect_duo', threshold: 100, xp_reward: 50000, coins_reward: 100000, medal_reward: 'Dupla Lendária', title_reward: 'Dupla Lendária', points: 800 },
  { name: 'Imortal das Quadras', description: 'Alcance #1 do mundo aos 40 anos.', icon: 'Infinity', rarity: 'mitico', category: 'lendário', visibility: 'oculto', mystery_description: 'A idade é apenas um número. O ranking é a verdade.', difficulty: 'lendario', trigger_type: 'rank1_at_40', threshold: 1, xp_reward: 100000, coins_reward: 200000, medal_reward: 'Imortal', title_reward: 'O Imortal', exclusive_item: 'Manto do Imortal', points: 1500 },
  { name: 'Renascimento', description: 'Volte do #1000 ao #1 do ranking mundial.', icon: 'Flame', rarity: 'mitico', category: 'lendário', visibility: 'oculto', mystery_description: 'Do fundo do abismo ao topo do mundo.', difficulty: 'lendario', trigger_type: 'comeback_rank', threshold: 1, xp_reward: 80000, coins_reward: 160000, medal_reward: 'Fênix do Ranking', title_reward: 'Fênix do Ranking', points: 1200 },
  { name: 'Domínio de Uma Era', description: 'Mantenha o #1 do ranking por 365 dias consecutivos.', icon: 'Castle', rarity: 'mitico', category: 'lendário', visibility: 'oculto', mystery_description: 'Um ano. Sem contestação. O trono é seu.', difficulty: 'lendario', trigger_type: 'rank1_year', threshold: 365, xp_reward: 100000, coins_reward: 200000, medal_reward: 'Domínio de Uma Era', title_reward: 'O Dominador', exclusive_item: 'Cetro do Dominador', points: 1500 },
  { name: 'Multiverso do Padel', description: 'Complete 10 gerações de carreira com #1 em todas.', icon: 'Infinity', rarity: 'exclusivo', category: 'lendário', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'multi_generation_champ', threshold: 10, xp_reward: 500000, coins_reward: 1000000, medal_reward: 'O Eterno', title_reward: 'O Eterno', exclusive_item: 'Coroa da Eternidade', hint: '10 vidas. 10 coroas. Uma alma.', is_revealed_hint: false, points: 5000 },
  { name: 'O Inatingível', description: 'Desbloqueie TODAS as outras conquistas.', icon: 'Sparkles', rarity: 'exclusivo', category: 'lendário', visibility: 'secreto', difficulty: 'lendario', trigger_type: 'all_achievements', threshold: 1, xp_reward: 1000000, coins_reward: 2000000, medal_reward: 'O Inatingível', title_reward: 'O Inatingível', exclusive_item: 'Coroa do Inatingível', hint: 'A perfeição não é o fim. É o começo de algo maior.', is_revealed_hint: false, points: 10000 },
];

// ─── Stats ────────────────────────────────────────────────────────────────────

export const ACHIEVEMENT_STATS = {
  total: ACHIEVEMENT_CATALOG.length,
  byVisibility: {
    publico: ACHIEVEMENT_CATALOG.filter(a => a.visibility === 'publico').length,
    oculto: ACHIEVEMENT_CATALOG.filter(a => a.visibility === 'oculto').length,
    secreto: ACHIEVEMENT_CATALOG.filter(a => a.visibility === 'secreto').length,
  },
  byCategory: ACHIEVEMENT_CATALOG.reduce((acc, a) => {
    acc[a.category] = (acc[a.category] || 0) + 1;
    return acc;
  }, {}),
  byDifficulty: ACHIEVEMENT_CATALOG.reduce((acc, a) => {
    acc[a.difficulty] = (acc[a.difficulty] || 0) + 1;
    return acc;
  }, {}),
  totalPoints: ACHIEVEMENT_CATALOG.reduce((sum, a) => sum + (a.points || 0), 0),
};

// ─── Category Meta ─────────────────────────────────────────────────────────────

export const CATEGORY_META = {
  partidas: { label: 'Partidas', icon: 'Swords', color: 'red' },
  torneios: { label: 'Torneios', icon: 'Trophy', color: 'amber' },
  'evolução': { label: 'Evolução', icon: 'Dumbbell', color: 'primary' },
  social: { label: 'Social', icon: 'Users', color: 'cyan' },
  economia: { label: 'Economia', icon: 'Coins', color: 'amber' },
  mercado: { label: 'Mercado', icon: 'TrendingUp', color: 'green' },
  'coleção': { label: 'Coleção', icon: 'Package', color: 'purple' },
  'história': { label: 'História', icon: 'ScrollText', color: 'cyan' },
  carreira: { label: 'Carreira', icon: 'Gamepad2', color: 'primary' },
  secreto: { label: 'Secreto', icon: 'Lock', color: 'red' },
  'lendário': { label: 'Lendário', icon: 'Crown', color: 'amber' },
};

// ─── Difficulty Meta ──────────────────────────────────────────────────────────

export const DIFFICULTY_META = {
  facil: { label: 'Fácil', color: 'text-green-400', bg: 'bg-green-500/15', border: 'border-green-500/40' },
  medio: { label: 'Médio', color: 'text-cyan-400', bg: 'bg-cyan-500/15', border: 'border-cyan-500/40' },
  dificil: { label: 'Difícil', color: 'text-amber-400', bg: 'bg-amber-500/15', border: 'border-amber-500/40' },
  extremo: { label: 'Extremo', color: 'text-red-400', bg: 'bg-red-500/15', border: 'border-red-500/40' },
  lendario: { label: 'Lendário', color: 'text-purple-400', bg: 'bg-purple-500/15', border: 'border-purple-500/40' },
};