// ── Encyclopedia Seed Data ───────────────────────────────────────────────
// Comprehensive entries covering the full Padel Legacy universe.

export const ENCYCLOPEDIA_CATEGORIES = {
  atleta:        { label: 'Atletas',          icon: 'Users',      color: 'text-primary',  bg: 'bg-primary/10' },
  clube:         { label: 'Clubes',           icon: 'Building2',  color: 'text-cyan-400', bg: 'bg-cyan-500/10' },
  treinador:     { label: 'Treinadores',      icon: 'GraduationCap', color: 'text-amber-400', bg: 'bg-amber-500/10' },
  patrocinador:  { label: 'Patrocinadores',   icon: 'Handshake',  color: 'text-green-400', bg: 'bg-green-500/10' },
  equipamento:   { label: 'Equipamentos',    icon: 'Package',    color: 'text-purple-400', bg: 'bg-purple-500/10' },
  regra:         { label: 'Regras',           icon: 'ScrollText', color: 'text-blue-400', bg: 'bg-blue-500/10' },
  torneio:       { label: 'Torneios',        icon: 'Trophy',     color: 'text-yellow-400', bg: 'bg-yellow-500/10' },
  pais:          { label: 'Países',          icon: 'Globe',      color: 'text-red-400', bg: 'bg-red-500/10' },
  cidade:        { label: 'Cidades',          icon: 'MapPin',     color: 'text-teal-400', bg: 'bg-teal-500/10' },
  estatistica:   { label: 'Estatísticas',     icon: 'BarChart3',  color: 'text-indigo-400', bg: 'bg-indigo-500/10' },
  recorde:       { label: 'Recordes',         icon: 'Medal',      color: 'text-orange-400', bg: 'bg-orange-500/10' },
  termo_tecnico: { label: 'Termos Técnicos',  icon: 'BookOpen',   color: 'text-pink-400', bg: 'bg-pink-500/10' },
  historia:      { label: 'História',         icon: 'Clock',      color: 'text-slate-400', bg: 'bg-slate-500/10' },
  tecnica:       { label: 'Técnicas',         icon: 'Zap',        color: 'text-lime-400', bg: 'bg-lime-500/10' },
  quadra:        { label: 'Quadra',           icon: 'LayoutGrid', color: 'text-sky-400', bg: 'bg-sky-500/10' },
};

export const ENCYCLOPEDIA_ENTRIES = [
  // ═══════════ HISTÓRIA ═══════════
  {
    name: 'Origens do Padel',
    category: 'historia',
    summary: 'Como o padel nasceu no México e conquistou o mundo',
    content: 'O padel foi inventado em 1969 por Enrique Corcuera, um empresário mexicano que adaptou sua quadra de squash em Acapulco para permitir rebatidas após quique na parede. A modalidade chegou à Espanha em 1974 pelas mãos de Alfonso de Hohenlohe, que construiu as primeiras quadras em Marbella. O esporte rapidamente ganhou popularidade na Argentina, que se tornou uma potência mundial. Hoje, o padel é praticado em mais de 90 países, com mais de 25 milhões de jogadores ativos. A Federação Internacional de Padel (FIP) foi fundada em 1991 para regulamentar o esporte globalmente.',
    tags: ['origem', 'méxico', 'corcuera', 'hohenlohe', '1991', 'FIP'],
    year: 1969,
    country: 'México',
    icon: 'Clock',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    related_entries: ['Enrique Corcuera', 'Federação Internacional de Padel', 'Académico (Estilo de Jogo)'],
  },
  {
    name: 'Evolução Profissional do Padel',
    category: 'historia',
    summary: 'Do amadorismo ao circuito profissional mundial',
    content: 'O padel profissional moderno começou a tomar forma nos anos 1990 com o circuito Padel Pro Tour (PPT), que depois evoluiu para o World Padel Tour (WPT) em 2013. Em 2022, a FIP lançou o Premier Padel, circuito premium em parceria com a Qatar Sports Investments, elevando o esporte a um novo patamar. A fusão dos circuitos em 2024 unificou o calendário profissional sob o guarda-chuva FIP. Hoje, mais de 50 torneios profissionais acontecem anualmente em 4 continentes, com premiações que ultrapassam 50 milhões de euros por temporada.',
    tags: ['WPT', 'Premier Padel', 'FIP', 'circuito', 'profissional'],
    year: 2013,
    icon: 'Clock',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    related_entries: ['World Padel Tour', 'Premier Padel', 'Federação Internacional de Padel'],
  },
  {
    name: 'O Padel no Brasil',
    category: 'historia',
    summary: 'O crescimento explosivo do padel no Brasil',
    content: 'O padel chegou ao Brasil nos anos 1990 trazido por imigrantes argentinos e uruguaios, inicialmente no Sul do país. A Confederação Brasileira de Padel (CBP) foi fundada para organizar a modalidade nacionalmente. A partir de 2018, o padel viveu um boom sem precedentes no Brasil, com a construção de centenas de quadras em todo o país. Atualmente, o Brasil possui mais de 5.000 quadras e 300.000 jogadores ativos, sendo um dos mercados que mais cresce no mundo. Cidades como São Paulo, Rio de Janeiro e Florianópolis se tornaram polos do esporte.',
    tags: ['brasil', 'CBP', 'crescimento', 'américa do sul'],
    country: 'Brasil',
    year: 1990,
    icon: 'Clock',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    related_entries: ['São Paulo', 'Confederação Brasileira de Padel'],
  },

  // ═══════════ ATLETAS ═══════════
  {
    name: 'Ale Galán',
    category: 'atleta',
    subcategory: 'masculino',
    summary: 'Número 1 mundial, conhecido pelo smash devastador',
    content: 'Alejandro "Ale" Galán (Madrid, 1995) é um dos maiores jogadores de padel da história. Estreou no circuito profissional em 2015 e rapidamente subiu ao topo do ranking mundial. Conhecido por seu smash potente e jogo agressivo, Galán conquistou múltiplos títulos de Grand Slam. Formou duplas históricas com Pablo Lima e posteriormente com Juan Lebrón. Seu estilo de jogo combina potência física impressionante com refinamento técnico, sendo considerado o jogador mais completo da nova geração.',
    tags: ['galán', 'madrid', 'espanha', 'número 1', 'smash'],
    country: 'Espanha',
    year: 1995,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'esquerda', play_style: 'Agressivo', best_ranking: 1, grand_slams: 12 },
    related_entries: ['Juan Lebrón', 'Pablo Lima', 'Madrid'],
  },
  {
    name: 'Juan Lebrón',
    category: 'atleta',
    subcategory: 'masculino',
    summary: 'El Lobo, o primeiro espanhol a chegar ao #1 mundial',
    content: 'Juan Lebrón Chincoa (El Puerto de Santa María, 1989) fez história ao se tornar o primeiro jogador espanhol a alcançar o número 1 do ranking mundial do World Padel Tour. Conhecido como "El Lobo", Lebrón é famoso por sua intensidade em quadra, velocidade impressionante e capacidade de virar jogos impossíveis. Sua parceria com Ale Galán formou uma das duplas mais temidas da história do padel. Com origem humilde, Lebrón é um ícone de superação no esporte.',
    tags: ['lebrón', 'el lobo', 'espanha', 'número 1'],
    country: 'Espanha',
    year: 1989,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'direita', play_style: 'Agressivo', best_ranking: 1, grand_slams: 8 },
    related_entries: ['Ale Galán', 'Espanha'],
  },
  {
    name: 'Fernando Belasteguín',
    category: 'atleta',
    subcategory: 'masculino',
    summary: 'Bela, 16 anos consecutivos como #1 do mundo',
    content: 'Fernando Belasteguín (Pehuajó, Argentina, 1979) é amplamente considerado o maior jogador de padel de todos os tempos. Permaneceu como número 1 do mundo por impressionantes 16 anos consecutivos (2002-2018), um recorde que dificilmente será superado. Conhecido por sua consistência, leitura de jogo e defesa impecável, Bela conquistou mais de 200 títulos profissionais em sua carreira. Sua longevidade no esporte é atribuída à disciplina física e mental excepcional. Mesmo após os 40 anos, continuou competindo em alto nível.',
    tags: ['bela', 'belasteguín', 'argentina', 'lenda', 'número 1', 'recorde'],
    country: 'Argentina',
    year: 1979,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    metadata: { position: 'direita', play_style: 'Defensivo', best_ranking: 1, years_at_1: 16, titles: 200 },
    related_entries: ['Argentina', 'Pablo Lima'],
  },
  {
    name: 'Pablo Lima',
    category: 'atleta',
    subcategory: 'masculino',
    summary: 'Lenda uruguaia-brasileira, múltiplo campeão mundial',
    content: 'Pablo Lima (Montevidéu, Uruguai, 1980) é um dos jogadores mais técnicos e consistentes da história do padel. Mudou-se para o Brasil ainda jovem e adotou nacionalidade brasileira. Formou com Belasteguín a dupla mais dominante da década de 2010, conquistando o mundo com um jogo de inteligência e precisão. Lima é conhecido por sua bandeja perfeita e capacidade de ler o jogo de forma excepcional. Após se separar de Bela, formou com Galán e continuou vencendo títulos.',
    tags: ['lima', 'uruguai', 'brasil', 'lenda', 'bandeja'],
    country: 'Uruguai',
    year: 1980,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'esquerda', play_style: 'Tático', best_ranking: 1, grand_slams: 15 },
    related_entries: ['Fernando Belasteguín', 'Ale Galán', 'Uruguai'],
  },
  {
    name: 'Agustín Tapia',
    category: 'atleta',
    subcategory: 'masculino',
    summary: 'El Mozart de Catamarca, prodígio argentino',
    content: 'Agustín Tapia (Catamarca, Argentina, 1999) é o prodígio do padel mundial. Apelidado de "El Mozart de Catamarca", Tapia impressionou o mundo ao se tornar o jogador mais jovem a entrar no top 10 do ranking mundial. Seu estilo é caracterizado por uma velocidade sobre-humana, reflexos felinos e uma capacidade de cobrir a quadra que desafia a lógica. Formou com Arturo Coello uma das duplas mais explosivas da história. Tapia representa a nova geração que está redefinindo o esporte.',
    tags: ['tapia', 'mozart', 'catamarca', 'argentina', 'prodígio'],
    country: 'Argentina',
    year: 1999,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'esquerda', play_style: 'Agressivo', best_ranking: 1, grand_slams: 6 },
    related_entries: ['Arturo Coello', 'Argentina'],
  },
  {
    name: 'Arturo Coello',
    category: 'atleta',
    subcategory: 'masculino',
    summary: 'Jovem espanhol, número 1 mundial aos 22 anos',
    content: 'Arturo Coello (Valladolid, Espanha, 2002) é a maior promessa do padel mundial. Aos 22 anos, tornou-se o jogador mais jovem a alcançar o número 1 do ranking mundial. Coello combina altura (1,93m), potência e técnica refinada em um package que dominou o circuito. Sua parceria com Agustín Tapia formou uma das duplas mais vitoriosas da história recente. Coello é conhecido por seu smash de x (smash por três), um golpe que se tornou sua marca registrada.',
    tags: ['coello', 'valladolid', 'espanha', 'número 1', 'jovem'],
    country: 'Espanha',
    year: 2002,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'direita', play_style: 'Potência', best_ranking: 1, grand_slams: 7 },
    related_entries: ['Agustín Tapia', 'Espanha'],
  },
  {
    name: 'Gemma Triay',
    category: 'atleta',
    subcategory: 'feminino',
    summary: 'Número 1 do circuito feminino, multicampeã',
    content: 'Gemma Triay (Santander, Espanha, 1992) é uma das maiores jogadoras do padel feminino. Conquistou o número 1 do ranking mundial e múltiplos títulos de Grand Slam. Triay é conhecida por seu jogo completo, combinando potência e inteligência tática. Sua parceria com Ale Salazar foi uma das mais dominantes do circuito feminino. Triay é uma embaixadora do padel feminino, ajudando a crescer a visibilidade e profissionalização da modalidade para mulheres.',
    tags: ['triaу', 'feminino', 'espanha', 'número 1'],
    country: 'Espanha',
    year: 1992,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'esquerda', play_style: 'Equilibrado', best_ranking: 1, grand_slams: 5 },
    related_entries: ['Espanha', 'Alejandra Salazar'],
  },
  {
    name: 'Alejandra Salazar',
    category: 'atleta',
    subcategory: 'feminino',
    summary: 'Lenda feminina, 4 vezes #1 do mundo',
    content: 'Alejandra Salazar (Madrid, Espanha, 1985) é uma das maiores jogadoras da história do padel feminino. Conquistou o número 1 do mundo em quatro ocasiões diferentes, demonstrando uma longevidade e consistência impressionantes. Conhecida como "A Maga", Salazar é famosa por sua visão de jogo excepcional e capacidade de executar jogadas impossíveis. Mesmo após lesões sérias, sempre voltou ao topo. É uma referência para gerações de jogadoras em todo o mundo.',
    tags: ['salazar', 'a maga', 'feminino', 'espanha', 'número 1'],
    country: 'Espanha',
    year: 1985,
    icon: 'Users',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { position: 'direita', play_style: 'Tático', best_ranking: 1, times_at_1: 4, grand_slams: 9 },
    related_entries: ['Gemma Triay', 'Espanha'],
  },

  // ═══════════ CLUBE ═══════════
  {
    name: 'Real Padel Club Madrid',
    category: 'clube',
    summary: 'Um dos clubes mais tradicionais de padel do mundo',
    content: 'O Real Padel Club Madrid é um dos clubes mais históricos do padel mundial, sediado na capital espanhola. Fundado nos anos 1990, o clube já sediou múltiplas etapas do World Padel Tour e é conhecido por suas instalações de elite. Possui mais de 20 quadras cobertas e ao ar livre, centro de treinamento de alta performance e academia. É um ponto de encontro para os melhores jogadores do mundo, que frequentemente treinam em suas instalações.',
    tags: ['madrid', 'espanha', 'tradicional', 'WPT'],
    country: 'Espanha',
    icon: 'Building2',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { courts: 20, founded: 1995, type: 'premium' },
    related_entries: ['Madrid', 'Espanha'],
  },
  {
    name: 'Padel Club Barcelona',
    category: 'clube',
    summary: 'Centro de excelência no coração da Catalunha',
    content: 'O Padel Club Barcelona é referência em formação de talentos no padel mundial. Localizado na capital catalã, o clube é conhecido por seu programa de base, que já revelou dezenas de jogadores profissionais. Possui quadras de última geração, centro de biomecânica e equipe técnica especializada. O clube organiza torneios internacionais anualmente e mantém parcerias com marcas de equipamentos de elite.',
    tags: ['barcelona', 'catalunha', 'espanha', 'formação'],
    country: 'Espanha',
    icon: 'Building2',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { courts: 15, founded: 1998, type: 'performance' },
    related_entries: ['Barcelona', 'Espanha'],
  },
  {
    name: 'Club Padel Buenos Aires',
    category: 'clube',
    summary: 'Templo do padel argentino',
    content: 'O Club Padel Buenos Aires é o coração do padel na Argentina, país com uma das maiores tradições no esporte. O clube possui mais de 30 quadras e é um dos maiores complexos de padel da América do Sul. Sedia regularmente etapas do circuito profissional e é conhecido pela paixão de sua torcida. O clube formou inúmeros campeões mundiais, incluindo Fernando Belasteguín e Agustín Tapia.',
    tags: ['buenos aires', 'argentina', 'américa do sul'],
    country: 'Argentina',
    icon: 'Building2',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { courts: 30, founded: 1992, type: 'mega' },
    related_entries: ['Buenos Aires', 'Argentina', 'Fernando Belasteguín'],
  },

  // ═══════════ TREINADOR ═══════════
  {
    name: 'Nito Drehmer',
    category: 'treinador',
    summary: 'Treinador lendário, formador de campeões',
    content: 'Nito Drehmer é um dos treinadores mais respeitados do padel mundial. Argentino radicado na Espanha, Drehmer formou inúmeros jogadores de topo, incluindo vários números 1 do mundo. Sua metodologia combina análise técnica detalhada com preparação psicológica. É conhecido por sua capacidade de identificar talentos jovens e desenvolvê-los até o nível profissional. Drehmer escreveu livros sobre técnica de padel que são referência no esporte.',
    tags: ['drehmer', 'treinador', 'argentina', 'espanha'],
    country: 'Argentina',
    icon: 'GraduationCap',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { specialty: 'tecnico', tier: 'lendario', athletes_coached: 50 },
    related_entries: ['Argentina', 'Espanha'],
  },
  {
    name: 'Marcello Ferrari',
    category: 'treinador',
    summary: 'Estrategista italiano do padel moderno',
    content: 'Marcello Ferrari é um dos treinadores mais inovadores do padel contemporâneo. Italiano, trouxe uma abordagem analítica ao esporte, usando dados e estatísticas para otimizar o desempenho. Ferrari é pioneiro no uso de tecnologia de vídeo-análise em tempo real durante treinos. Trabalhou com diversas duplas de elite e é conhecido por transformar jogadores medianos em contendores ao topo.',
    tags: ['ferrari', 'treinador', 'itália', 'inovador'],
    country: 'Itália',
    icon: 'GraduationCap',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { specialty: 'estratega', tier: 'profissional', style: 'inovador' },
    related_entries: ['Itália'],
  },

  // ═══════════ PATROCINADOR ═══════════
  {
    name: 'Bullpadel',
    category: 'patrocinador',
    summary: 'Marca líder mundial em equipamentos de padel',
    content: 'Bullpadel é a marca número 1 do mundo em equipamentos de padel. Fundada na Espanha em 1995, a Bullpadel revolucionou o design de raquetes de padel, introduzindo tecnologias como o núcleo de EVA e os perfis moldados. Patrocina os melhores jogadores do mundo, incluindo Ale Galán e Gemma Triay. A empresa investe pesadamente em P&D, com laboratórios próprios de biomecânica. Suas raquetes são referência em qualidade e inovação no esporte.',
    tags: ['bullpadel', 'marca', 'espanha', 'raquetes'],
    country: 'Espanha',
    year: 1995,
    icon: 'Handshake',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { industry: 'equipamentos', tier: 'Ouro', founded: 1995 },
    related_entries: ['Ale Galán', 'Gemma Triay', 'Espanha'],
  },
  {
    name: 'Head Padel',
    category: 'patrocinador',
    summary: 'Marca austríaca com forte presença no padel',
    content: 'Head é uma marca austríaca com décadas de tradição em tênis que expandiu para o padel com grande sucesso. Head Padel patrocina alguns dos melhores jogadores do mundo, incluindo Arturo Coello e Sanyo Gutiérrez. Suas raquetes da linha Delta e Alpha são conhecidas por combinar potência e controle. A marca investe em tecnologia de materiais avançados, como grafeno, para criar raquetes mais leves e duráveis.',
    tags: ['head', 'marca', 'áustria', 'raquetes', 'grafeno'],
    country: 'Áustria',
    icon: 'Handshake',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { industry: 'equipamentos', tier: 'Ouro', founded: 1950 },
    related_entries: ['Arturo Coello', 'Sanyo Gutiérrez'],
  },
  {
    name: 'Babolat',
    category: 'patrocinador',
    summary: 'Marca francesa histórica no esporte de raquetes',
    content: 'Babolat é uma marca francesa fundada em 1875, originalmente especializada em cordas de raquete. Entrou no mercado de padel em 2014 e rapidamente se tornou uma das marcas mais respeitadas. Babolat patrocina Juan Lebrón e é conhecida por sua linha Viper de raquetes, que oferece potência extrema. A marca combina sua experiência centenária em tênis com inovações específicas para o padel, criando produtos de alta performance.',
    tags: ['babolat', 'marca', 'frança', 'raquetes', 'viper'],
    country: 'França',
    year: 1875,
    icon: 'Handshake',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { industry: 'equipamentos', tier: 'Ouro', founded: 1875 },
    related_entries: ['Juan Lebrón', 'França'],
  },
  {
    name: 'Adidas Padel',
    category: 'patrocinador',
    summary: 'Gigante alemão no mercado de padel',
    content: 'Adidas entrou no mercado de padel trazendo sua expertise em materiais esportivos de alta performance. A marca alemã patrocina Ale Galán e oferece linhas de raquetes como Metalbone e Adipower. Adidas é conhecida por investir em pesquisa de materiais e por seu design moderno. Sua entrada no padel ajudou a trazer visibilidade global para o esporte, aproveitando o reconhecimento mundial da marca.',
    tags: ['adidas', 'marca', 'alemanha', 'metalbone'],
    country: 'Alemanha',
    icon: 'Handshake',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { industry: 'equipamentos', tier: 'Ouro', founded: 1949 },
    related_entries: ['Ale Galán'],
  },

  // ═══════════ EQUIPAMENTO ═══════════
  {
    name: 'Raquete de Padel',
    category: 'equipamento',
    subcategory: 'raquete',
    summary: 'O equipamento central do padel - formas, materiais e tecnologias',
    content: 'A raquete de padel é o equipamento mais importante do esporte. Diferente das raquetes de tênis, não tem cordas: a superfície de batida é perfurada com furos e feita de fibra de vidro, carbono ou kevlar. Existem três formatos principais: REDONDA (controle, ideal para iniciantes e defensores), LÁGRIMA (equilíbrio entre controle e potência, versátil) e DIAMANTE (potência máxima, para jogadores avançados e agressivos). O núcleo interno é geralmente de EVA (espuma) em diferentes densidades: soft (conforto e potência) ou hard (controle e precisão). O peso varia entre 350-385g, e o balanceamento (baixo, médio ou alto) afeta o estilo de jogo.',
    tags: ['raquete', 'formatos', 'redonda', 'lágrima', 'diamante', 'carbono', 'EVA'],
    icon: 'Package',
    is_featured: true,
    reading_time_min: 5,
    source: 'mundo_real',
    metadata: { weight_range: '350-385g', shapes: ['redonda', 'lágrima', 'diamante'], materials: ['fibra de vidro', 'carbono', 'kevlar', 'EVA'] },
    related_entries: ['Formato Redondo', 'Formato Lágrima', 'Formato Diamante'],
  },
  {
    name: 'Bola de Padel',
    category: 'equipamento',
    subcategory: 'bola',
    summary: 'Similar à de tênis, mas com menor pressão interna',
    content: 'A bola de padel é similar à bola de tênis, mas com diferenças importantes: tem menor pressão interna (cerca de 11 psi vs 14 psi do tênis) e é ligeiramente menor. Isso resulta em menor quique e velocidade, adequado ao espaço reduzido da quadra. As bolas oficiais devem atender às normas da FIP. A cor é sempre amarela fluorescente ou branca. A durabilidade de uma bola de padel é de aproximadamente 2-3 partidas intensas. Em altitudes acima de 1.500m, usam-se bolas de alta altitude (Tipo 2) com diferente pressurização.',
    tags: ['bola', 'pressão', 'FIP', 'amarela'],
    icon: 'Package',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { pressure_psi: 11, color: 'amarela', diameter_mm: '63-68' },
    related_entries: ['Federação Internacional de Padel', 'Raquete de Padel'],
  },
  {
    name: 'Formato Redondo',
    category: 'equipamento',
    subcategory: 'forma_raquete',
    summary: 'Máximo controle, ideal para iniciantes e defensores',
    content: 'A raquete de formato redondo é a mais indicada para iniciantes e jogadores defensivos. Seu centro de peso (balanceamento) fica mais próximo da mão, oferecendo maior controle e maneabilidade. O sweet spot (área ideal de batida) é maior e localizado no centro da raquete. Este formato reduz o risco de lesões como epicondilite (cotovelo de tenista). Recomendado para jogadores que valorizam precisão e consistência sobre potência bruta.',
    tags: ['redonda', 'controle', 'iniciante', 'defensivo', 'balanceamento baixo'],
    icon: 'Package',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { balance: 'baixo', play_style: 'Defensivo', difficulty: 'iniciante' },
    related_entries: ['Raquete de Padel', 'Formato Lágrima', 'Formato Diamante'],
  },
  {
    name: 'Formato Lágrima',
    category: 'equipamento',
    subcategory: 'forma_raquete',
    summary: 'Equilíbrio perfeito entre controle e potência',
    content: 'A raquete formato lágrima (ou gota) é a mais versátil do padel. Combina elementos dos formatos redondo e diamante, oferecendo um equilíbrio entre controle e potência. O balanceamento é médio, o sweet spot é intermediário. É a escolha preferida da maioria dos jogadores profissionais que jogam a rede. Indicada para jogadores de nível intermediário a avançado que buscam um jogo completo sem sacrificar nem controle nem potência.',
    tags: ['lágrima', 'gota', 'versátil', 'equilíbrio', 'balanceamento médio'],
    icon: 'Package',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { balance: 'médio', play_style: 'Equilibrado', difficulty: 'intermediário' },
    related_entries: ['Raquete de Padel', 'Formato Redondo', 'Formato Diamante'],
  },
  {
    name: 'Formato Diamante',
    category: 'equipamento',
    subcategory: 'forma_raquete',
    summary: 'Potência máxima para jogadores avançados e agressivos',
    content: 'A raquete formato diamante é a mais potente do padel. Seu balanceamento é alto (peso concentrado na ponta), o que gera mais força nos golpes de ataque como smash e bandeja. O sweet spot é menor e localizado na parte superior da raquete, exigindo técnica apurada. Indicada apenas para jogadores avançados e agressivos, pois é mais difícil de controlar e aumenta o risco de lesões se usada incorretamente. É a escolha de jogadores como Juan Lebrón e Ale Galán.',
    tags: ['diamante', 'potência', 'avançado', 'agressivo', 'balanceamento alto'],
    icon: 'Package',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { balance: 'alto', play_style: 'Agressivo', difficulty: 'avançado' },
    related_entries: ['Raquete de Padel', 'Formato Redondo', 'Formato Lágrima', 'Juan Lebrón'],
  },

  // ═══════════ REGRA ═══════════
  {
    name: 'Regras Básicas do Padel',
    category: 'regra',
    summary: 'Como funciona o padel: pontuação, saque e quadra',
    content: 'O padel é jogado em duplas (2 vs 2) em uma quadra fechada por paredes de vidro e metal. A pontuação segue o sistema do tênis: 15, 30, 40, game. Um set é vencido por quem fizer 6 games com 2 de diferença. As partidas são em melhor de 3 sets. O saque deve ser executado por baixo (a raquete abaixo da cintura), e a bola deve quicar na quadra antes de bater na parede. Após o quique, a bola pode bater nas paredes antes de ser devolvida. A bola pode ser rebatida diretamente (de primeira) ou após bater na parede própria. Se a bola bater na parede do adversário e voltar para sua quadra, pode ser rebatida após o quique.',
    tags: ['regras', 'pontuação', 'saque', 'básico', 'duplas'],
    icon: 'ScrollText',
    is_featured: true,
    reading_time_min: 5,
    source: 'mundo_real',
    related_entries: ['Saque', 'Regras de Parede', 'Sistema de Pontuação'],
  },
  {
    name: 'Saque',
    category: 'regra',
    summary: 'O saque no padel: execução, regras e erros comuns',
    content: 'O saque no padel deve ser executado por baixo, com a raquete abaixo do nível da cintura no momento do contato. O jogador saca da linha de fundo, alternando lados a cada ponto. A bola deve quicar na quadra do adversário diagonalmente. Se a bola quicar na rede e cair na quadra válida, há "let" (repetição do saque). Dois faults resultam em perda do ponto. O saque pode atingir a parede do adversário após o quique. Não é permitido saltar durante o saque, e os pés não podem tocar a linha de fundo.',
    tags: ['saque', 'service', 'regras', 'por baixo'],
    icon: 'ScrollText',
    reading_time_min: 3,
    source: 'mundo_real',
    related_entries: ['Regras Básicas do Padel'],
  },
  {
    name: 'Regras de Parede',
    category: 'regra',
    summary: 'Como as paredes funcionam no padel',
    content: 'As paredes são elemento central do padel. A bola pode bater na parede própria (do lado de quem rebate) antes ou depois do quique na quadra. Após o saque, a bola pode bater na parede do adversário, que pode rebate-la antes ou após quicar. A bola NÃO pode bater em duas paredes seguidas do lado adversário antes de quicar (seria "dois paredões", ponto perdido). A bola que bate na malha metálica antes da parede é considerada inválida. As paredes de vidro são consideradas parte da quadra para todos os efeitos.',
    tags: ['parede', 'vidro', 'malha', 'paredão', 'regras'],
    icon: 'ScrollText',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    related_entries: ['Regras Básicas do Padel', 'Quadra de Padel'],
  },
  {
    name: 'Regra do Golden Point',
    category: 'regra',
    summary: 'No empate em 40-40, o próximo ponto decide o game',
    content: 'A regra do Golden Point (ou Ponto de Ouro) foi introduzida no padel profissional para acelerar o jogo. Quando o placar chega a 40-40 (deuce), não há mais vantagem: o próximo ponto decide o game. A dupla que recebe escolhe de que lado quer receber o ponto decisivo. Esta regra tornou as partidas mais dinâmicas e imprevisíveis, sendo adotada em todos os torneios profissionais desde 2020.',
    tags: ['golden point', 'ponto de ouro', 'deuce', '40-40', 'regra moderna'],
    year: 2020,
    icon: 'ScrollText',
    reading_time_min: 2,
    source: 'mundo_real',
    related_entries: ['Regras Básicas do Padel'],
  },

  // ═══════════ TORNEIO ═══════════
  {
    name: 'Premier Padel',
    category: 'torneio',
    summary: 'Circuito premium da FIP com torneios em 4 continentes',
    content: 'Premier Padel é o circuito de elite do padel mundial, lançado em 2022 pela FIP em parceria com a Qatar Sports Investments. Oferece as maiores premiações da história do padel e organiza torneios em quatro continentes. Os torneios Premier Padel são classificados em categorias: Major (mais alto nível), P1 e P2. Os Majors oferecem 500 pontos de ranking ao campeão e premiações superiores a 500.000 euros. O circuito unificou o padel profissional global em 2024, absorvendo o antigo World Padel Tour.',
    tags: ['premier padel', 'FIP', 'major', 'circuito', 'qatar'],
    year: 2022,
    icon: 'Trophy',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    metadata: { tier: 'Major', points_champion: 500, prize_pool: '€500K+' },
    related_entries: ['World Padel Tour', 'Federação Internacional de Padel'],
  },
  {
    name: 'World Padel Tour',
    category: 'torneio',
    summary: 'Circuito histórico que dominou o padel de 2013 a 2023',
    content: 'O World Padel Tour (WPT) foi o principal circuito profissional de padel de 2013 a 2023. Organizava mais de 20 torneios anuais em diversos países, sendo responsável pela profissionalização e globalização do padel. Em 2024, o WPT foi integrado ao circuito Premier Padel da FIP, unificando o calendário profissional. O WPT foi pioneiro em transmissões de TV, prêmios milionários e estrutura profissional para os jogadores. Seu legado inclui o estabelecimento do padel como esporte de elite.',
    tags: ['WPT', 'world padel tour', 'circuito', 'histórico'],
    year: 2013,
    icon: 'Trophy',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { tier: 'P1', active_years: '2013-2023' },
    related_entries: ['Premier Padel', 'Federação Internacional de Padel'],
  },
  {
    name: 'Campeonato Mundial de Padel',
    category: 'torneio',
    summary: 'Competição de seleções nacionais, organizada pela FIP',
    content: 'O Campeonato Mundial de Padel é a principal competição entre seleções nacionais, organizada pela FIP a cada dois anos. Disputado desde 1992, o mundial reúne as melhores seleções do planeta em formato de grupos e mata-mata. Espanha e Argentina dominam historicamente o torneio, com Portugal, Itália e Brasil crescendo em competitividade. O mundial é o único torneio onde jogadores representam seus países em vez de suas duplas habituais, criando rivalidades únicas.',
    tags: ['mundial', 'FIP', 'seleções', 'espanha', 'argentina'],
    year: 1992,
    icon: 'Trophy',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { tier: 'Major', frequency: 'bianual', format: 'seleções' },
    related_entries: ['Federação Internacional de Padel', 'Espanha', 'Argentina'],
  },

  // ═══════════ PAÍS ═══════════
  {
    name: 'Espanha',
    category: 'pais',
    summary: 'Berço moderno do padel, maior potência mundial',
    content: 'A Espanha é a potência absoluta do padel mundial. O esporte chegou ao país em 1974 e se transformou no esporte de raquete de maior crescimento do país. Com mais de 4 milhões de jogadores e 12.000 quadras, a Espanha possui a maior infraestrutura de padel do mundo. Praticamente todos os números 1 mundiais da história são espanhóis ou treinam em solo espanhol. Madri, Barcelona e Málaga são os polos mais importantes. A Real Federação Espanhola de Padel (FEP) é uma das mais organizadas do esporte.',
    tags: ['espanha', 'potência', 'número 1', 'FEP'],
    icon: 'Globe',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { players: '4M', courts: 12000, world_titles: 12 },
    related_entries: ['Madrid', 'Barcelona', 'Ale Galán', 'Juan Lebrón', 'Arturo Coello'],
  },
  {
    name: 'Argentina',
    category: 'pais',
    summary: 'Terra de lendas como Belasteguín e Tapia',
    content: 'A Argentina é a segunda maior potência do padel mundial e uma das pioneiras no esporte. Com mais de 2 milhões de jogadores, o país formou lendas como Fernando Belasteguín (16 anos como #1), Sanyo Gutiérrez e Agustín Tapia. O padel argentino é conhecido por sua paixão, criatividade e estilo de jogo característico. Buenos Aires, Córdoba e Catamarca são polos do esporte. A Associação Argentina de Pádel (AAP) é uma das mais antigas do mundo, fundada em 1989.',
    tags: ['argentina', 'bela', 'tapia', 'sanyo', 'AAP'],
    icon: 'Globe',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { players: '2M', world_titles: 8 },
    related_entries: ['Fernando Belasteguín', 'Agustín Tapia', 'Buenos Aires'],
  },
  {
    name: 'Itália',
    category: 'pais',
    summary: 'O país que mais cresce no padel europeu',
    content: 'A Itália é o país que mais cresce no padel na Europa. Em poucos anos, passou de poucas centenas de quadras para mais de 5.000, com mais de 1 milhão de jogadores. A Federação Italiana de Padel (FIP Italia) investiu massivamente na profissionalização do esporte. Roma, Milão e Bologna são os principais polos. A Itália já tem jogadores no top 50 mundial e sedia torneios do circuito Premier Padel. O governo italiano reconheceu o padel como esporte de interesse nacional em 2023.',
    tags: ['itália', 'crescimento', 'europa', 'roma'],
    icon: 'Globe',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { players: '1M', courts: 5000 },
    related_entries: ['Roma', 'Itália'],
  },
  {
    name: 'Suécia',
    category: 'pais',
    summary: 'Potência nórdica com investimento massivo no padel',
    content: 'A Suécia vivenciou um boom sem precedentes no padel a partir de 2018. Em três anos, o país passou de quase zero quadras para mais de 3.000, tornando-se um dos mercados mais importantes da Europa. Estocolmo é o epicentro do padel sueco. Empresários suecos investiram milhões em clubes e infraestrutura. A Federação Sueca de Padel cresceu exponencialmente e o país já sedia torneios profissionais. O padel sueco é conhecido por sua cultura social e acessibilidade.',
    tags: ['suécia', 'estocolmo', 'boom', 'nórdico'],
    icon: 'Globe',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { players: '500K', courts: 3000 },
    related_entries: ['Estocolmo'],
  },
  {
    name: 'Brasil',
    category: 'pais',
    summary: 'Mercado em explosão, futuro do padel mundial',
    content: 'O Brasil é um dos mercados que mais cresce no padel mundial. Com origem nos anos 1990 trazido por argentinos, o padel brasileiro explodiu a partir de 2018. Hoje possui mais de 5.000 quadras e 300.000 jogadores, com São Paulo, Rio de Janeiro e Florianópolis como principais polos. A Confederação Brasileira de Padel (CBP) organiza circuitos nacionais e internacionais. O Brasil tem jogadores no circuito profissional e é visto como o futuro do padel pela dimensão continental e paixão esportiva do país.',
    tags: ['brasil', 'CBP', 'crescimento', 'américa do sul', 'são paulo'],
    icon: 'Globe',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { players: '300K', courts: 5000 },
    related_entries: ['São Paulo', 'O Padel no Brasil'],
  },

  // ═══════════ CIDADE ═══════════
  {
    name: 'Madrid',
    category: 'cidade',
    summary: 'Capital mundial do padel, sede dos maiores torneios',
    content: 'Madrid é a capital mundial do padel. A cidade espanhola possui mais de 1.500 quadras e é sede dos torneios mais importantes do calendário, incluindo o Madrid Premier Padel Major. Madri formou e revelou alguns dos maiores jogadores da história, como Ale Galán, Juan Lebrón (que se mudou jovem) e Alejandra Salazar. A cidade respira padel, com clubes em praticamente todos os bairros. O clima continental de Madrid, com verões quentes e invernos frios, influencia o estilo de jogo e as condições das quadras.',
    tags: ['madrid', 'capital', 'espanha', 'torneios'],
    country: 'Espanha',
    icon: 'MapPin',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { courts: 1500, climate: 'continental' },
    related_entries: ['Espanha', 'Ale Galán', 'Alejandra Salazar', 'Real Padel Club Madrid'],
  },
  {
    name: 'Buenos Aires',
    category: 'cidade',
    summary: 'Coração do padel argentino, terra de campeões',
    content: 'Buenos Aires é o coração do padel argentino. A cidade e sua região metropolitana possuem milhares de quadras e uma cultura de padel profundamente enraizada. É terra de lendas como Fernando Belasteguín, que aprendeu a jogar nas quadras portenhas. Buenos Aires sedia regularmente etapas do circuito profissional e é conhecida pela paixão de sua torcida, considerada uma das mais barulhentas e conhecedoras do mundo. O estilo de jogo argentino, criativo e aguerrido, foi forjado nas quadras portenhas.',
    tags: ['buenos aires', 'argentina', 'portenho', 'paixão'],
    country: 'Argentina',
    icon: 'MapPin',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { climate: 'subtropical' },
    related_entries: ['Argentina', 'Fernando Belasteguín', 'Club Padel Buenos Aires'],
  },
  {
    name: 'Barcelona',
    category: 'cidade',
    summary: 'Polo catalão de formação de talentos',
    content: 'Barcelona é um dos polos mais importantes do padel europeu. A capital catalã possui uma cena de padel vibrante, com clubes de alta qualidade e programas de formação de talentos reconhecidos mundialmente. Barcelona sedia torneios do circuito profissional e é conhecida por sua cultura esportiva. O clima mediterrâneo da cidade oferece condições ideais para padel ao ar livre durante a maior parte do ano. Muitos jogadores profissionais escolhem Barcelona como base de treinamento.',
    tags: ['barcelona', 'catalunha', 'espanha', 'mediterrâneo'],
    country: 'Espanha',
    icon: 'MapPin',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { climate: 'mediterrâneo' },
    related_entries: ['Espanha', 'Padel Club Barcelona'],
  },
  {
    name: 'São Paulo',
    category: 'cidade',
    summary: 'Maior polo do padel brasileiro',
    content: 'São Paulo é o maior polo de padel do Brasil. A cidade possui centenas de quadras espalhadas por todos os bairros, com clubes premium e estruturas de alta qualidade. São Paulo sedia etapas do circuito brasileiro e internacional de padel. A cidade tem clima subtropical úmido, com verões quentes e úmidos que influenciam as condições de jogo. A cultura de padel paulistana cresce exponencialmente, com jogadores de todas as idades e níveis. É considerada a capital do padel na América do Sul fora de Buenos Aires.',
    tags: ['são paulo', 'brasil', 'polo', 'subtropical'],
    country: 'Brasil',
    icon: 'MapPin',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { climate: 'subtropical úmido' },
    related_entries: ['Brasil', 'O Padel no Brasil'],
  },
  {
    name: 'Estocolmo',
    category: 'cidade',
    summary: 'Capital nórdica que abraçou o padel',
    content: 'Estocolmo é o epicentro do boom do padel na Suécia. A cidade passou de poucas quadras em 2018 para mais de 800 em poucos anos. Estocolmo possui alguns dos clubes mais modernos do mundo, com investimentos milionários em infraestrutura. O clima nórdico, com invernos longos e escuros, fez do padel um esporte indoor extremamente popular entre os suecos. A cidade sedia torneios do circuito profissional e possui uma cena social vibrante em torno do padel.',
    tags: ['estocolmo', 'suécia', 'nórdico', 'indoor'],
    country: 'Suécia',
    icon: 'MapPin',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { courts: 800, climate: 'temperado frio' },
    related_entries: ['Suécia'],
  },
  {
    name: 'Doha',
    category: 'cidade',
    summary: 'Sede da Premier Padel e capital do padel no Oriente Médio',
    content: 'Doha, capital do Catar, tornou-se uma das cidades mais importantes do padel mundial. Sedia o Qatar Major, um dos torneios mais prestigiosos do calendário Premier Padel. A Qatar Sports Investments é parceira da FIP no circuito Premier Padel, trazendo investimentos recordes para o esporte. Doha possui infraestrutura de elite e clima desértico extremo, com temperaturas que chegam a 45°C no verão. Os torneios em Doha são jogados em quadras cobertas climatizadas durante os meses mais quentes.',
    tags: ['doha', 'qatar', 'oriente médio', 'major'],
    country: 'Catar',
    icon: 'MapPin',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { climate: 'desértico', avg_temp: 32 },
    related_entries: ['Premier Padel'],
  },

  // ═══════════ ESTATÍSTICA ═══════════
  {
    name: 'Jogadores de Padel no Mundo',
    category: 'estatistica',
    summary: 'Mais de 25 milhões de jogadores ativos globalmente',
    content: 'O padel ultrapassou a marca de 25 milhões de jogadores ativos em mais de 90 países. A Espanha lidera com aproximadamente 4 milhões, seguida por Argentina (2M), Itália (1M), Suécia (500K) e Brasil (300K). O crescimento médio anual de novos jogadores é de 25% em mercados estabelecidos e mais de 100% em mercados emergentes. Estima-se que até 2030 o padel tenha 50 milhões de jogadores globais. O perfil médio do jogador de padel é de 30-45 anos, com divisão de gênero aproximada de 70% masculino e 30% feminino.',
    tags: ['estatística', 'jogadores', 'crescimento', 'global'],
    icon: 'BarChart3',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { total_players: '25M', countries: 90, growth_rate: '25%' },
    related_entries: ['Espanha', 'Argentina', 'Itália', 'Suécia', 'Brasil'],
  },
  {
    name: 'Quadras de Padel no Mundo',
    category: 'estatistica',
    summary: 'Mais de 70.000 quadras espalhadas pelo planeta',
    content: 'Existem aproximadamente 70.000 quadras de padel no mundo, concentradas principalmente na Europa e América do Sul. A Espanha possui cerca de 12.000 quadras, Argentina 8.000, Itália 5.000, Suécia 3.000 e Brasil 5.000. A construção de quadras cresce 30% ao ano em mercados emergentes. Uma quadra de padel padrão mede 20m x 10m e custa entre 15.000 e 40.000 euros para construir. A tendência é de quadras cobertas com climatização, especialmente em países com climas extremos.',
    tags: ['estatística', 'quadras', 'infraestrutura', 'crescimento'],
    icon: 'BarChart3',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { total_courts: '70K', spain: 12000, argentina: 8000, italy: 5000 },
    related_entries: ['Quadra de Padel', 'Jogadores de Padel no Mundo'],
  },

  // ═══════════ RECORDE ═══════════
  {
    name: 'Mais Tempo como #1 Mundial',
    category: 'recorde',
    summary: 'Fernando Belasteguín: 16 anos consecutivos no topo',
    content: 'O recorde de mais tempo como número 1 do mundo pertence a Fernando Belasteguín, que permaneceu no topo do ranking por 16 anos consecutivos (2002-2018). Este recorde é considerado praticamente inquebrável, dada a competitividade atual do circuito. Bela alcançou o #1 aos 23 anos e só deixou o topo aos 39. Durante seu reinado, venceu mais de 200 torneios profissionais. Este recorde supera qualquer marca em esportes de raquete, incluindo tênis.',
    tags: ['recorde', 'bela', 'número 1', '16 anos'],
    year: 2018,
    icon: 'Medal',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { record_holder: 'Fernando Belasteguín', value: '16 anos', period: '2002-2018' },
    related_entries: ['Fernando Belasteguín'],
  },
  {
    name: 'Jogador Mais Jovem #1 Mundial',
    category: 'recorde',
    summary: 'Arturo Coello alcançou o #1 aos 22 anos',
    content: 'Arturo Coello tornou-se o jogador mais jovem a alcançar o número 1 do ranking mundial de padel, aos 22 anos de idade. Este recorde quebrou a marca anterior de Ale Galán, que havia chegado ao topo aos 24 anos. Coello combinou altura (1,93m), potência física e técnica refinada para dominar o circuito em ritmo recorde. Sua ascensão meteórica é considerada uma das mais impressionantes da história do esporte de raquete.',
    tags: ['recorde', 'coello', 'jovem', 'número 1', '22 anos'],
    year: 2024,
    icon: 'Medal',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { record_holder: 'Arturo Coello', value: '22 anos', year: 2024 },
    related_entries: ['Arturo Coello'],
  },
  {
    name: 'Maior Premiação da História',
    category: 'recorde',
    summary: 'Premier Padel Major: mais de 500.000 euros em premiação',
    content: 'O recorde de maior premiação em um torneio de padel pertence aos Majors do Premier Padel, que oferecem mais de 500.000 euros em premiação total. O campeão de um Major recebe aproximadamente 100.000 euros e 500 pontos de ranking. Este valor representa um aumento de mais de 500% em relação às premiações do início do WPT em 2013. O crescimento das premiações reflete a profissionalização e globalização do esporte, com investidores como a Qatar Sports Investments injetando recursos recordes.',
    tags: ['recorde', 'premiação', 'major', '500 mil', 'premier padel'],
    year: 2023,
    icon: 'Medal',
    is_featured: true,
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { record: '€500K+', event: 'Premier Padel Major', year: 2023 },
    related_entries: ['Premier Padel'],
  },

  // ═══════════ TERMO TÉCNICO ═══════════
  {
    name: 'Bandeja',
    category: 'termo_tecnico',
    summary: 'Golpe icônico do padel: smash controlado e cortado',
    content: 'A bandeja é o golpe mais característico do padel. Trata-se de um smash controlado em que a bola é cortada com a raquete levemente inclinada, dando um efeito que faz a bola quicar na quadra adversária e "morrer" após bater na parede. A bandeja é executada com a raquete acima da cabeça, mas com um movimento mais horizontal que o smash tradicional. É usada para manter pressão sem perder o controle da rede. Dominar a bandeja é essencial para qualquer jogador de nível intermediário ou superior.',
    tags: ['bandeja', 'golpe', 'smash', 'cortado', 'técnica'],
    icon: 'BookOpen',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { type: 'ataque', difficulty: 'intermediário', effect: 'cortado' },
    related_entries: ['Víbora', 'Smash', 'Golpe de Padel (Técnicas)'],
  },
  {
    name: 'Víbora',
    category: 'termo_tecnico',
    summary: 'Variante avançada da bandeja com efeito lateral',
    content: 'A víbora é uma evolução da bandeja, executada com a raquete mais vertical e com um movimento de "chicotada" lateral. O resultado é uma bola com efeito lateral (top-spin) que quica na quadra adversária e acelera em direção à parede lateral, saindo em ângulo imprevisível. A víbora é mais agressiva que a bandeja mas requer mais técnica e controle. É considerada um golpe de nível avançado, usado para finalizar pontos ou colocar pressão máxima no adversário. Jogadores como Sanyo Gutiérrez são mestres da víbora.',
    tags: ['víbora', 'golpe', 'avançado', 'efeito lateral', 'técnica'],
    icon: 'BookOpen',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { type: 'ataque', difficulty: 'avançado', effect: 'lateral' },
    related_entries: ['Bandeja', 'Smash', 'Golpe de Padel (Técnicas)'],
  },
  {
    name: 'Smash',
    category: 'termo_tecnico',
    summary: 'Golpe de potência máxima por cima da cabeça',
    content: 'O smash no padel é um golpe de potência executado por cima da cabeça, similar ao do tênis mas adaptado às paredes. Existem variações: smash por 3 (a bola bate na parede do adversário e sai pela porta dos fundos), smash por 4 (bate na parede e volta para a quadra de origem), e smash plano (potência direta). O smash por 3 é o mais espetacular e decisivo do padel, sendo a marca registrada de jogadores como Arturo Coello. A execução perfeita do smash exige timing, potência e posicionamento ideais.',
    tags: ['smash', 'potência', 'por 3', 'por 4', 'técnica'],
    icon: 'BookOpen',
    is_featured: true,
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { type: 'ataque', difficulty: 'avançado', variants: ['por 3', 'por 4', 'plano'] },
    related_entries: ['Bandeja', 'Víbora', 'Arturo Coello'],
  },
  {
    name: 'Chiquita',
    category: 'termo_tecnico',
    summary: 'Bola curta e lenta para desestabilizar o adversário na rede',
    content: 'A chiquita é um golpe defensivo-estratégico do padel: uma bola curta, lenta e baixa executada quando o adversário está na rede. O objetivo é forçar o adversário a recuar ou a executar uma bola difícil de baixo para cima. A chiquita é jogada com pouco backswing, usando a raquete quase como "bloqueio" direcionado. É uma jogada de inteligência tática, usada para quebrar o ritmo do adversário e recuperar a iniciativa do ponto. Requer leitura de jogo e timing precisos.',
    tags: ['chiquita', 'curta', 'lenta', 'tática', 'defensiva'],
    icon: 'BookOpen',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { type: 'tática', difficulty: 'intermediário' },
    related_entries: ['Bandeja', 'Golpe de Padel (Técnicas)'],
  },
  {
    name: 'Globo',
    category: 'termo_tecnico',
    summary: 'Bola alta para passar o adversário na rede',
    content: 'O globo (ou golpe alto) é uma bola lançada alta e profunda, passando por cima do adversário que está na rede. O objetivo é forçar o adversário a recuar para a linha de fundo ou executar uma bandeja/smash difícil. O globo é fundamental no padel: um bom globo profundo é uma das jogadas mais eficazes contra duplas agressivas na rede. A profundidade e altura do globo determinam sua eficácia. Globo curto ou baixo é facilmente atacado pelo adversário.',
    tags: ['globo', 'alto', 'profundo', 'tática', 'rede'],
    icon: 'BookOpen',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { type: 'tática', difficulty: 'básico' },
    related_entries: ['Bandeja', 'Smash', 'Golpe de Padel (Técnicas)'],
  },
  {
    name: 'Dormilona',
    category: 'termo_tecnico',
    summary: 'Bola "dorminhoca" com efeito que engana após o quique',
    content: 'A dormilona é um golpe com efeito cortado extremo que faz a bola quase parar após o quique na quadra adversária, "dormindo" perto da rede. É uma jogada enganosa que surpreende o adversário esperando uma bola com mais ritmo. A dormilona é executada com um movimento de baixo para cima, "fatiando" a bola. É uma arma poderosa para jogadores táticos que usam a variação de ritmo para desestabilizar adversários agressivos.',
    tags: ['dormilona', 'cortado', 'enganação', 'efeito', 'tática'],
    icon: 'BookOpen',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { type: 'tática', difficulty: 'avançado', effect: 'cortado' },
    related_entries: ['Bandeja', 'Chiquita'],
  },

  // ═══════════ TÉCNICA ═══════════
  {
    name: 'Golpe de Padel (Técnicas)',
    category: 'tecnica',
    summary: 'Panorama dos principais golpes e quando usar cada um',
    content: 'O padel possui uma rica variedade de golpes, cada um com função específica: DIREITA (forehand) e ESQUERDA (backhand) são os golpes básicos de troca de bola. BANDEJA é o smash controlado para manter pressão na rede. VÍBORA é a variante agressiva com efeito lateral. SMASH é o golpe de potência máxima para finalizar pontos. GLOBO é a bola alta para recuar o adversário. CHIQUITA é a bola curta para desestabilizar. DORMILONA é o corte com efeito que para após o quique. A escolha do golpe depende da posição na quadra, da bola recebida e da estratégia do ponto.',
    tags: ['golpes', 'técnicas', 'panorama', 'direita', 'esquerda'],
    icon: 'Zap',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    related_entries: ['Bandeja', 'Víbora', 'Smash', 'Globo', 'Chiquita', 'Dormilona'],
  },
  {
    name: 'Posicionamento em Quadra',
    category: 'tecnica',
    summary: 'Estratégia de posicionamento: rede vs fundo',
    content: 'O posicionamento no padel divide-se em duas zonas principais: REDE (posição agressiva, próximos à rede) e FUNDO (posição defensiva, na linha de fundo). A dupla idealmente se move junta: quando ambos estão na rede, têm vantagem ofensiva; quando ambos estão no fundo, estão em defesa. A transição entre fundo e rede é crucial: após um globo profundo, os jogadores avançam para a rede; após uma chiquita do adversário, podem recuar. O jogador da DIREITA (right side) geralmente é mais controlador, e o da ESQUERDA (left side) é mais agressivo, especialmente em jogadores destros.',
    tags: ['posicionamento', 'rede', 'fundo', 'estratégia', 'dupla'],
    icon: 'Zap',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    related_entries: ['Golpe de Padel (Técnicas)', 'Globo', 'Chiquita'],
  },
  {
    name: 'Transição de Ataque',
    category: 'tecnica',
    summary: 'Como passar do fundo para a rede efetivamente',
    content: 'A transição de ataque no padel é o momento crítico em que uma dupla passa da defesa (fundo) para o ataque (rede). A transição deve ser feita após uma bola que coloca o adversário em dificuldade: um globo profundo, uma chiquita bem executada ou um erro do adversário. A regra de ouro é: nunca subir sozinho. Ambos os jogadores devem avançar juntos para a rede, mantendo a sincronia. A subida deve ser em diagonal ou reta, nunca cruzando. O primeiro golpe após chegar à rede é decisivo: deve ser agressivo para consolidar a posição.',
    tags: ['transição', 'ataque', 'subida', 'rede', 'estratégia'],
    icon: 'Zap',
    reading_time_min: 3,
    source: 'mundo_real',
    related_entries: ['Posicionamento em Quadra', 'Globo'],
  },

  // ═══════════ QUADRA ═══════════
  {
    name: 'Quadra de Padel',
    category: 'quadra',
    summary: 'Dimensões, estrutura e materiais da quadra oficial',
    content: 'A quadra de padel oficial mede 20 metros de comprimento por 10 metros de largura, dividida ao meio por uma rede com 0,88m de altura central. As paredes posteriores têm 3m de altura e são compostas por vidro temperado (parte inferior) e malha metálica (parte superior). As paredes laterais têm 3m na extremidade posterior e 2m na extremidade da rede, com um degrau de transição. O piso pode ser de grama sintética, cimento ou resina, sendo a grama sintética a mais usada profissionalmente. A cor tradicional é azul ou verde para o piso, com linhas brancas.',
    tags: ['quadra', 'dimensões', 'vidro', 'malha', 'grama sintética'],
    icon: 'LayoutGrid',
    is_featured: true,
    reading_time_min: 4,
    source: 'mundo_real',
    metadata: { length_m: 20, width_m: 10, net_height_m: 0.88, wall_height_m: 3 },
    related_entries: ['Regras de Parede', 'Regras Básicas do Padel'],
  },
  {
    name: 'Superfícies de Jogo',
    category: 'quadra',
    summary: 'Grama sintética, cimento e resina: prós e contras',
    content: 'O padel é jogado em diferentes superfícies, cada uma afetando o jogo: GRAMA SINTÉTICA (profissional, permite jogo rápido e quique consistente, exige manutenção regular), CIMENTO (superfície dura, quique alto e rápido, comum em clubes públicos), RESINA/POLIURETANO (superfície uniforme e durável, boa para indoor). A grama sintética pode ter diferentes velocidades dependendo da granulometria da areia. Superfícies mais lentas favorecem jogadores defensivos, enquanto superfícies rápidas beneficiam jogadores de ataque. A FIP regulamenta as superfícies para torneios oficiais.',
    tags: ['superfície', 'grama', 'cimento', 'resina', 'velocidade'],
    icon: 'LayoutGrid',
    reading_time_min: 3,
    source: 'mundo_real',
    metadata: { surfaces: ['grama sintética', 'cimento', 'resina'] },
    related_entries: ['Quadra de Padel'],
  },
  {
    name: 'Paredes de Vidro',
    category: 'quadra',
    summary: 'O vidro temperado que define o esporte',
    content: 'As paredes de vidro são o elemento que torna o padel único. Feitas de vidro temperado de 10-12mm de espessura, suportam o impacto da bola em alta velocidade. O vidro permite que a bola rebata com previsibilidade, possibilitando jogadas de parede. A transparência também permite que espectadores assistam ao jogo de fora da quadra. O vidro deve ser mantido limpo para visibilidade ideal. Em torneios profissionais, as paredes são revisadas antes de cada partida para garantir que não haja trincas ou danos.',
    tags: ['vidro', 'temperado', 'parede', 'estrutura'],
    icon: 'LayoutGrid',
    reading_time_min: 2,
    source: 'mundo_real',
    metadata: { thickness_mm: 10, type: 'temperado' },
    related_entries: ['Quadra de Padel', 'Regras de Parede'],
  },
];