export const HOF_CRITERIA = {
  atleta: [
    { id: 'titles', label: 'Títulos Profissionais', min: 15, weight: 30, description: 'Mínimo de 15 títulos em circuitos profissionais' },
    { id: 'years_pro', label: 'Anos como Profissional', min: 8, weight: 15, description: 'Mínimo de 8 anos no circuito profissional' },
    { id: 'ranking_peak', label: 'Pico de Ranking', min: 5, weight: 25, description: 'Top 5 do ranking mundial em algum momento' },
    { id: 'wins', label: 'Vitórias em Carreira', min: 200, weight: 20, description: 'Mínimo de 200 vitórias profissionais' },
    { id: 'impact', label: 'Impacto no Esporte', min: 1, weight: 10, description: 'Contribuição histórica para o desenvolvimento do padel' },
  ],
  treinador: [
    { id: 'titles_coached', label: 'Títulos como Treinador', min: 10, weight: 35, description: 'Mínimo de 10 títulos com atletas treinados' },
    { id: 'years_coaching', label: 'Anos como Treinador', min: 10, weight: 20, description: 'Mínimo de 10 anos no comando técnico' },
    { id: 'athletes_developed', label: 'Atletas Formados', min: 3, weight: 25, description: 'Mínimo de 3 atletas profissionais formados' },
    { id: 'innovation', label: 'Inovação Tática', min: 1, weight: 20, description: 'Contribuição tática ou técnica reconhecida' },
  ],
  dupla: [
    { id: 'titles_together', label: 'Títulos em Dupla', min: 20, weight: 40, description: 'Mínimo de 20 títulos conquistados juntos' },
    { id: 'years_together', label: 'Anos em Parceria', min: 4, weight: 20, description: 'Mínimo de 4 anos como parceiros' },
    { id: 'chemistry', label: 'Química de Jogo', min: 85, weight: 20, description: 'Nível de entrosamento excepcional' },
    { id: 'dominance', label: 'Período de Dominância', min: 1, weight: 20, description: 'Pelo menos 1 ano como dupla #1 do mundo' },
  ],
  clube: [
    { id: 'titles', label: 'Títulos do Clube', min: 20, weight: 30, description: 'Mínimo de 20 títulos conquistados' },
    { id: 'years_active', label: 'Anos de Atividade', min: 15, weight: 20, description: 'Mínimo de 15 anos no circuito' },
    { id: 'champions_formed', label: 'Campeões Formados', min: 5, weight: 25, description: 'Mínimo de 5 campeões revelados' },
    { id: 'reputation', label: 'Reputação Histórica', min: 80, weight: 25, description: 'Reputação mínima de 80/100' },
  ],
};

export const HOF_LEGENDS = [
  {
    name: 'Fernando Belasteguín',
    entity_type: 'atleta',
    category: 'lendario',
    induction_year: 2024,
    nationality: 'Argentina',
    rating: 98,
    bio: 'Belasteguín é amplamente considerado o maior jogador de padel de todos os tempos. Permaneceu como número 1 do ranking mundial por 16 anos consecutivos (2007-2023), um recorde que dificilmente será igualado. Sua parceria com Juan Martín Díaz dominou o circuito por mais de uma década, conquistando mais de 200 títulos juntos. Conhecido por sua consistência sob pressão e liderança em quadra, "Bela" redefiniu o padrão de excelência no padel profissional.',
    career_stats: { titles: 213, wins: 1247, losses: 198, years_pro: 19, ranking_peak: 1, win_rate: 86.3, majors: 47 },
    trophies: [
      { name: 'Mundial de Padel', year: 2010, type: 'selecao', description: 'Campeão mundial com a Seleção Argentina' },
      { name: 'World Padel Tour - Geral', year: 2014, type: 'circuito', description: 'Campeão geral do WPT' },
      { name: 'World Padel Tour - Geral', year: 2015, type: 'circuito', description: 'Bicampeão geral do WPT' },
      { name: 'Premier Padel Major', year: 2023, type: 'major', description: 'Campeão do Premier Padel Major de Roma' },
      { name: 'Premier Padel Major', year: 2024, type: 'major', description: 'Bicampeão do Major de Roma' },
    ],
    career_timeline: [
      { year: 2005, event: 'Estreia Profissional', description: 'Inicia carreira profissional no circuito argentino aos 16 anos' },
      { year: 2007, event: 'Número 1 do Mundo', description: 'Alcança o número 1 do ranking mundial pela primeira vez' },
      { year: 2008, event: 'Parceria com Díaz', description: 'Inicia parceria histórica com Juan Martín Díaz' },
      { year: 2013, event: 'Era WPT', description: 'Domina o recém-criado World Padel Tour' },
      { year: 2020, event: '10 Anos como #1', description: 'Completa uma década como número 1 ininterrupto' },
      { year: 2023, event: '16 Anos como #1', description: 'Recorde histórico de 16 anos no topo do ranking' },
      { year: 2024, event: 'Indução ao Hall da Fama', description: 'Induzido ao Hall da Fama do Padel' },
    ],
    career_records: [
      { record: 'Mais anos como #1', value: '16 anos', year: 2023 },
      { record: 'Mais títulos em dupla', value: '213 títulos', year: 2024 },
      { record: 'Maior taxa de vitórias', value: '86.3%', year: 2024 },
      { record: 'Mais Majors conquistados', value: '47 Majors', year: 2024 },
    ],
    videos: [
      { title: 'Os 10 Melhores Pontos da Carreira', description: 'Compilação dos pontos mais espetaculares de Belasteguín', duration: '12:34', views: 4200000, thumbnail_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400' },
      { title: 'Final Histórica vs Galán', description: 'A final épic do WPT 2018 que definiu uma geração', duration: '45:12', views: 8900000, thumbnail_url: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400' },
      { title: 'Técnica de Bandeja Perfeita', description: 'Análise técnica da bandeja de Bela, considerada a melhor do mundo', duration: '08:22', views: 2100000, thumbnail_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400' },
    ],
    highlights: [
      '16 anos consecutivos como número 1 do mundo',
      '213 títulos profissionais conquistados',
      '86.3% de taxa de vitórias em carreira',
      '47 Majors conquistados',
      'Parceria mais dominante da história com Díaz',
      'Campeão mundial com a Seleção Argentina',
    ],
    comparison_stats: { titles: 213, winRate: 86.3, yearsPro: 19, rankingPeak: 1, majors: 47 },
  },
  {
    name: 'Juan Martín Díaz',
    entity_type: 'atleta',
    category: 'lendario',
    induction_year: 2024,
    nationality: 'Argentina',
    rating: 96,
    bio: 'Juan Martín Díaz formou a dupla mais dominante da história do padel ao lado de Belasteguín. Esquerda canhoto de poder explosivo, Díaz era conhecido por seu smash devastador e capacidade de virar jogos impossíveis. Conquistou mais de 200 títulos em carreira e foi peça fundamental na hegemonia argentina no esporte.',
    career_stats: { titles: 205, wins: 1189, losses: 215, years_pro: 18, ranking_peak: 1, win_rate: 84.7, majors: 43 },
    trophies: [
      { name: 'Mundial de Padel', year: 2010, type: 'selecao', description: 'Campeão mundial com a Argentina' },
      { name: 'World Padel Tour - Geral', year: 2014, type: 'circuito', description: 'Campeão geral do WPT' },
      { name: 'World Padel Tour - Geral', year: 2015, type: 'circuito', description: 'Bicampeão geral do WPT' },
      { name: 'Premier Padel Major', year: 2023, type: 'major', description: 'Major de Roma' },
    ],
    career_timeline: [
      { year: 2006, event: 'Estreia Profissional', description: 'Inicia no circuito argentino' },
      { year: 2008, event: 'Parceria com Bela', description: 'Forma dupla com Belasteguín' },
      { year: 2014, event: 'Domínio do WPT', description: 'Conquista o título geral do WPT' },
      { year: 2023, event: '200 Títulos', description: 'Alcança 200 títulos em dupla com Bela' },
      { year: 2024, event: 'Indução ao Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: 'Mais títulos em dupla (juntos)', value: '200 títulos', year: 2023 },
      { record: 'Smash mais potente medido', value: '132 km/h', year: 2019 },
    ],
    videos: [
      { title: 'Smash Devastador de Díaz', description: 'Os smashes mais potentes da carreira', duration: '07:45', views: 3500000, thumbnail_url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400' },
      { title: 'A Dupla Perfeita', description: 'Documentário sobre a parceria Díaz-Bela', duration: '28:30', views: 6200000, thumbnail_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400' },
    ],
    highlights: [
      '200+ títulos em carreira',
      'Parceiro da dupla mais dominante da história',
      'Smash mais potente já medido no padel',
      'Campeão mundial com Argentina',
    ],
    comparison_stats: { titles: 205, winRate: 84.7, yearsPro: 18, rankingPeak: 1, majors: 43 },
  },
  {
    name: 'Alejandro Galán',
    entity_type: 'atleta',
    category: 'lendario',
    induction_year: 2025,
    nationality: 'Espanha',
    rating: 95,
    bio: 'Alejandro Galán liderou a transição geracional do padel mundial, tornando-se o novo número 1 após o fim do reinado de Belasteguín. Seu estilo de jogo completo, com potência e precisão, redefiniu o padrão técnico da nova geração. Formou com Juan Lebrón uma das duplas mais espetaculares do circuito.',
    career_stats: { titles: 87, wins: 642, losses: 148, years_pro: 9, ranking_peak: 1, win_rate: 81.3, majors: 18 },
    trophies: [
      { name: 'Premier Padel Major', year: 2024, type: 'major', description: 'Major de Doha' },
      { name: 'World Padel Tour - Geral', year: 2021, type: 'circuito', description: 'Campeão geral do WPT' },
      { name: 'Mundial de Padel', year: 2022, type: 'selecao', description: 'Campeão com a Espanha' },
    ],
    career_timeline: [
      { year: 2016, event: 'Estreia Profissional', description: 'Inicia no circuito WPT' },
      { year: 2018, event: 'Rivalidade com Bela', description: 'Desafia o reinado de Belasteguín' },
      { year: 2020, event: 'Número 1 do Mundo', description: 'Alcança o topo do ranking' },
      { year: 2022, event: 'Campeão Mundial', description: 'Conquista o mundial com a Espanha' },
      { year: 2025, event: 'Indução ao Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: 'Jogador mais jovem #1', value: '24 anos', year: 2020 },
      { record: 'Mais Majors em uma temporada', value: '8 Majors', year: 2024 },
    ],
    videos: [
      { title: 'Galán vs Bela: A Guerra', description: 'Os melhores confrontos da maior rivalidade do padel', duration: '18:20', views: 7200000, thumbnail_url: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=400' },
      { title: 'Voleio Mágico de Galán', description: 'Análise da técnica de voleio de Galán', duration: '09:15', views: 1800000, thumbnail_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400' },
    ],
    highlights: [
      'Jogador mais jovem a alcançar o #1',
      '18 Majors conquistados',
      'Líder da transição geracional',
      'Campeão mundial com a Espanha',
    ],
    comparison_stats: { titles: 87, winRate: 81.3, yearsPro: 9, rankingPeak: 1, majors: 18 },
  },
  {
    name: 'Arturo Coello',
    entity_type: 'atleta',
    category: 'lendario',
    induction_year: 2026,
    nationality: 'Espanha',
    rating: 97,
    bio: 'Arturo Coello é o nome mais dominante da era moderna do padel. Em parceria com Agustín Tapia, formou a dupla mais temida do circuito Premier Padel. Seu estilo agressivo e potência física redefiniram o jogo, e tornou-se o número 1 mais jovem da história do esporte. Considerado o futuro herdeiro de todos os grandes recordes.',
    career_stats: { titles: 65, wins: 498, losses: 92, years_pro: 5, ranking_peak: 1, win_rate: 84.4, majors: 14 },
    trophies: [
      { name: 'Premier Padel Major', year: 2024, type: 'major', description: 'Major de Roma' },
      { name: 'Premier Padel Major', year: 2025, type: 'major', description: 'Major de Doha' },
      { name: 'Premier Padel Major', year: 2026, type: 'major', description: 'Major de Paris' },
    ],
    career_timeline: [
      { year: 2021, event: 'Estreia Profissional', description: 'Inicia no circuito WPT' },
      { year: 2023, event: 'Parceria com Tapia', description: 'Forma dupla dominante com Tapia' },
      { year: 2024, event: 'Número 1 do Mundo', description: 'Torna-se o #1 mais jovem da história' },
      { year: 2026, event: 'Indução ao Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: '#1 mais jovem da história', value: '22 anos', year: 2024 },
      { record: 'Mais Majors em 2 anos', value: '14 Majors', year: 2026 },
    ],
    videos: [
      { title: 'Coello: O Fenômeno', description: 'Documentário sobre a ascensão meteórica de Coello', duration: '22:10', views: 5800000, thumbnail_url: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400' },
      { title: 'Coello-Tapia: A Nova Era', description: 'A dupla que dominou o Premier Padel', duration: '15:40', views: 3400000, thumbnail_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400' },
    ],
    highlights: [
      'Número 1 mais jovem da história do padel',
      '14 Majors em apenas 2 anos',
      '84.4% de taxa de vitórias',
      'Líder da era Coello-Tapia',
    ],
    comparison_stats: { titles: 65, winRate: 84.4, yearsPro: 5, rankingPeak: 1, majors: 14 },
  },
  {
    name: 'Belasteguín - Díaz',
    entity_type: 'dupla',
    category: 'lendario',
    induction_year: 2024,
    nationality: 'Argentina',
    partner_name: 'Fernando Belasteguín & Juan Martín Díaz',
    rating: 99,
    bio: 'A dupla mais dominante da história do padel. Belasteguín e Díaz formaram uma parceria que conquistou mais de 200 títulos juntos, dominando o circuito por mais de uma década. Sua química em quadra era perfeita: Belasteguín com sua consistência e liderança, Díaz com seu smash devastador. Juntos, redefiniram o que significa ser uma dupla de padel.',
    career_stats: { titles_together: 213, years_together: 16, chemistry: 98, dominance: 10, win_rate: 86.3 },
    trophies: [
      { name: '200+ Títulos em Dupla', year: 2023, type: 'recorde', description: 'Recorde de títulos em parceria' },
      { name: 'WPT Geral (5x)', year: 2015, type: 'circuito', description: '5 títulos gerais do WPT consecutivos' },
      { name: 'Premier Padel Major', year: 2023, type: 'major', description: 'Major de Roma' },
    ],
    career_timeline: [
      { year: 2008, event: 'Formação da Dupla', description: 'Belasteguín e Díaz começam a jogar juntos' },
      { year: 2013, event: 'Domínio do WPT', description: 'Iniciam sequência de 5 títulos gerais do WPT' },
      { year: 2023, event: '200 Títulos', description: 'Alcançam 200 títulos em parceria' },
      { year: 2024, event: 'Indução ao Hall da Fama', description: 'Induzidos como maior dupla da história' },
    ],
    career_records: [
      { record: 'Mais títulos em parceria', value: '213 títulos', year: 2023 },
      { record: 'Mais anos como #1 em dupla', value: '14 anos', year: 2023 },
      { record: 'Maior taxa de vitórias em dupla', value: '86.3%', year: 2023 },
    ],
    videos: [
      { title: 'A Dupla do Século', description: 'Documentário completo sobre Bela-Díaz', duration: '45:00', views: 12000000, thumbnail_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400' },
      { title: 'Os 20 Melhores Pontos', description: 'Os pontos mais espetaculares da dupla', duration: '14:22', views: 6500000, thumbnail_url: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=400' },
    ],
    highlights: [
      '213 títulos conquistados juntos',
      '14 anos como dupla #1 do mundo',
      '86.3% de taxa de vitórias em parceria',
      'Domínio absoluto por mais de uma década',
    ],
    comparison_stats: { titles: 213, winRate: 86.3, yearsPro: 16, rankingPeak: 1, majors: 47 },
  },
  {
    name: 'Agustín Tapia',
    entity_type: 'atleta',
    category: 'lendario',
    induction_year: 2026,
    nationality: 'Argentina',
    rating: 95,
    bio: 'Agustín Tapia é o parceiro perfeito de Coello na dupla mais temida do circuito atual. Canhoto com toque mágico e criatividade sem limites, Tapia é conhecido como "El Mago" por suas jogadas impossíveis. Sua visão de jogo e capacidade de criar ângulos únicos o tornam um dos jogadores mais espetaculares de se assistir.',
    career_stats: { titles: 58, wins: 452, losses: 98, years_pro: 6, ranking_peak: 2, win_rate: 82.2, majors: 14 },
    trophies: [
      { name: 'Premier Padel Major', year: 2024, type: 'major', description: 'Major de Roma' },
      { name: 'Premier Padel Major', year: 2025, type: 'major', description: 'Major de Doha' },
    ],
    career_timeline: [
      { year: 2020, event: 'Estreia', description: 'Inicia no circuito profissional' },
      { year: 2023, event: 'Parceria com Coello', description: 'Forma dupla dominante' },
      { year: 2026, event: 'Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: 'Toque de bola mais preciso', value: '98% precisão', year: 2025 },
    ],
    videos: [
      { title: 'El Mago: Jogadas Impossíveis', description: 'As jogadas mais mágicas de Tapia', duration: '11:30', views: 4100000, thumbnail_url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400' },
    ],
    highlights: [
      '"El Mago" do padel moderno',
      '14 Majors conquistados',
      'Parceiro de Coello na dupla dominante',
      '82.2% de taxa de vitórias',
    ],
    comparison_stats: { titles: 58, winRate: 82.2, yearsPro: 6, rankingPeak: 2, majors: 14 },
  },
  {
    name: 'Alejandro Lasaigues',
    entity_type: 'atleta',
    category: 'lendario',
    induction_year: 2015,
    nationality: 'Argentina',
    rating: 93,
    bio: 'Alejandro Lasaigues foi o primeiro grande ídolo mundial do padel. Na década de 1990, dominou o circuito com seu estilo agressivo e potência incomparável para a época. Foi o responsável por elevar o nível técnico do esporte e inspirar gerações futuras de jogadores argentinos.',
    career_stats: { titles: 124, wins: 786, losses: 245, years_pro: 14, ranking_peak: 1, win_rate: 76.2, majors: 22 },
    trophies: [
      { name: 'Mundial de Padel', year: 1992, type: 'selecao', description: 'Primeiro mundial com Argentina' },
      { name: 'Circuito Argentino (8x)', year: 2000, type: 'circuito', description: '8 títulos do circuito argentino' },
    ],
    career_timeline: [
      { year: 1988, event: 'Estreia Profissional', description: 'Inicia no circuito argentino' },
      { year: 1992, event: 'Campeão Mundial', description: 'Conquista o primeiro mundial' },
      { year: 2002, event: 'Aposentadoria', description: 'Aposenta-se como lenda' },
      { year: 2015, event: 'Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: 'Primeiro #1 do ranking mundial', value: '1992', year: 1992 },
      { record: 'Mais títulos da década de 90', value: '78 títulos', year: 2000 },
    ],
    videos: [
      { title: 'Lasaigues: O Pioneiro', description: 'Documentário sobre o primeiro ídolo do padel', duration: '32:15', views: 2800000, thumbnail_url: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400' },
    ],
    highlights: [
      'Primeiro grande ídolo mundial do padel',
      'Campeão do primeiro mundial (1992)',
      '124 títulos em carreira',
      'Pioneiro que elevou o nível técnico do esporte',
    ],
    comparison_stats: { titles: 124, winRate: 76.2, yearsPro: 14, rankingPeak: 1, majors: 22 },
  },
  {
    name: 'Real Club Puerta de Hierro',
    entity_type: 'clube',
    category: 'lendario',
    induction_year: 2020,
    nationality: 'Espanha',
    rating: 96,
    bio: 'O Real Club de Puerta de Hierro em Madrid é o templo histórico do padel mundial. Fundado em 1970, foi o primeiro clube europeu a adotar o esporte. Revelou dezenas de campeões mundiais e suas quadras são consideradas patrimônio do padel. O clube foi palco dos primeiros torneios oficiais e da fundação da FIP.',
    career_stats: { titles: 187, years_active: 56, champions_formed: 34, reputation: 98, members: 3200 },
    trophies: [
      { name: 'Primeiro Clube de Padel da Europa', year: 1970, type: 'histórico', description: 'Título histórico de pioneirismo' },
      { name: 'Mais Campeões Formados', year: 2020, type: 'recorde', description: '34 campeões mundiais revelados' },
    ],
    career_timeline: [
      { year: 1970, event: 'Fundação', description: 'Primeiro clube europeu de padel' },
      { year: 1974, event: 'Primeiro Torneio', description: 'Palco do primeiro torneio oficial' },
      { year: 1991, event: 'Sede da FIP', description: 'Sede da fundação da FIP' },
      { year: 2020, event: 'Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: 'Mais campeões formados', value: '34 campeões', year: 2020 },
      { record: 'Clube mais antigo de padel', value: '56 anos', year: 2026 },
    ],
    videos: [
      { title: 'Puerta de Hierro: O Templo', description: 'Documentário sobre o clube mais histórico do padel', duration: '38:00', views: 1900000, thumbnail_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400' },
    ],
    highlights: [
      'Primeiro clube de padel da Europa (1970)',
      '34 campeões mundiais revelados',
      'Sede da fundação da FIP (1991)',
      'Palco dos primeiros torneios oficiais',
      '187 títulos conquistados por atletas do clube',
    ],
    comparison_stats: { titles: 187, winRate: 0, yearsPro: 56, rankingPeak: 1, majors: 0 },
  },
  {
    name: 'Nito Berta',
    entity_type: 'treinador',
    category: 'lendario',
    induction_year: 2022,
    nationality: 'Argentina',
    rating: 94,
    bio: 'Nito Berta é considerado o treinador mais influente da história do padel. Formou múltiplos campeões mundiais, incluindo Belasteguín e Díaz, e revolucionou a metodologia de treinamento do esporte. Sua abordagem científica e tática redefiniu como o padel é ensinado e praticado em todo o mundo.',
    career_stats: { titles_coached: 156, years_coaching: 28, athletes_developed: 12, innovation: 5 },
    trophies: [
      { name: 'Treinador do Ano (5x)', year: 2020, type: 'individual', description: '5 vezes eleito o melhor treinador do ano' },
      { name: 'Formador de Campeões', year: 2022, type: 'histórico', description: 'Formou 12 atletas profissionais' },
    ],
    career_timeline: [
      { year: 1995, event: 'Início da Carreira', description: 'Inicia como treinador na Argentina' },
      { year: 2008, event: 'Treina Bela-Díaz', description: 'Torna-se treinador da dupla dominante' },
      { year: 2015, event: 'Metodologia Revolucionária', description: 'Publica método de treinamento adotado mundialmente' },
      { year: 2022, event: 'Hall da Fama', description: 'Induzido ao Hall da Fama' },
    ],
    career_records: [
      { record: 'Mais títulos como treinador', value: '156 títulos', year: 2022 },
      { record: 'Mais atletas formados', value: '12 profissionais', year: 2022 },
    ],
    videos: [
      { title: 'O Método Berta', description: 'Documentário sobre a metodologia revolucionária', duration: '25:00', views: 1500000, thumbnail_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400' },
    ],
    highlights: [
      'Treinador de Belasteguín e Díaz',
      '156 títulos como treinador',
      '12 atletas profissionais formados',
      'Revolucionou a metodologia de treinamento',
    ],
    comparison_stats: { titles: 156, winRate: 0, yearsPro: 28, rankingPeak: 1, majors: 0 },
  },
];

export const HOF_CATEGORY_CONFIG = {
  lendario: { label: 'Lenda', color: 'text-amber-400', bg: 'bg-amber-500/15', border: 'border-amber-500/30', glow: 'glow-primary' },
  epico: { label: 'Épico', color: 'text-purple-400', bg: 'bg-purple-500/15', border: 'border-purple-500/30', glow: '' },
  destaque: { label: 'Destaque', color: 'text-cyan-400', bg: 'bg-cyan-500/15', border: 'border-cyan-500/30', glow: '' },
};

export const HOF_TYPE_CONFIG = {
  atleta: { label: 'Atleta', icon: 'Crown', color: 'amber' },
  treinador: { label: 'Treinador', icon: 'Whistle', color: 'primary' },
  dupla: { label: 'Dupla', icon: 'Handshake', color: 'cyan' },
  clube: { label: 'Clube', icon: 'Building2', color: 'green' },
};