const confidence=(sample,persistence,threshold)=>{const score=Math.min(1,(sample/threshold)*.55+(persistence/Math.max(2,threshold/2))*.45);return{score:Math.round(score*100)/100,label:score>=.78?'high':score>=.52?'medium':'low'};};
export class PatternChangeDetector {
  detect(analytics,{teamId='A',coachLevel=1,initialPlan,currentPoint}){const window=analytics.window('last_5_points');if(window.length<Math.max(3,6-Math.min(3,coachLevel)))return[];const opponent=teamId==='A'?'B':'A',shots=window.flatMap(p=>p.shots),opponentShots=shots.filter(s=>s.team===opponent),teamShots=shots.filter(s=>s.team===teamId),patterns=[];
    const add=(patternId,category,evidence,sample,persistence,adjustment,priority='recommendation')=>{const calibrated=confidence(sample,persistence,coachLevel>=3?5:7);patterns.push({patternId,category,evidence,sampleSize:sample,persistence,confidence:calibrated.label,confidenceScore:calibrated.score,firstDetectedAt:`point-${Math.max(1,currentPoint-window.length+1)}`,lastDetectedAt:`point-${currentPoint}`,adjustment,priority});};
    const targets={};opponentShots.forEach(s=>{if(s.targetPlayerId)targets[s.targetPlayerId]=(targets[s.targetPlayerId]||0)+1;});const targeted=Object.entries(targets).sort((a,b)=>b[1]-a[1])[0];if(targeted&&targeted[1]>=4&&targeted[1]/Math.max(1,opponentShots.length)>=.6)add('opponent_targeting_player','opponent',`${targeted[1]} de ${opponentShots.length} bolas foram dirigidas ao mesmo jogador.`,opponentShots.length,targeted[1],{tacticId:'defensivo',components:{safeWeight:1.15}});
    const opponentLobs=opponentShots.filter(s=>s.shot==='lob').length;if(opponentLobs>=4)add('opponent_more_lobs','defensive',`O adversário usou ${opponentLobs} lobs na janela recente.`,opponentShots.length,opponentLobs,{tacticId:'tatico',components:{positioning:'recover_after_lob'}});
    const volleyErrors=window.filter(p=>p.result==='error'&&p.shot==='volley'&&p.shots.at(-1)?.team===teamId).length;if(volleyErrors>=3)add('volley_errors','technical',`${volleyErrors} erros de voleio nos últimos ${window.length} pontos.`,window.length,volleyErrors,{tacticId:'defensivo',components:{riskModifier:.9}});
    const energy=Math.min(...Object.values(window.at(-1)?.energies||{none:100}));if(energy<=35)add('critical_energy','physical',`Energia mínima da dupla em ${Math.round(energy)}.`,window.length,window.filter(p=>Math.min(...Object.values(p.energies))<=40).length,{tacticId:'defensivo',components:{pace:'slow',energyModifier:.9}},'urgent');
    const planned=initialPlan?.id;const aggressiveShots=teamShots.filter(s=>['smash','volley','drive'].includes(s.shot)).length;if(planned==='agressivo'&&teamShots.length>=8&&aggressiveShots/teamShots.length<.3)add('plan_not_executed','plan',`Apenas ${Math.round(aggressiveShots/teamShots.length*100)}% dos golpes seguiram o plano ofensivo.`,teamShots.length,teamShots.length-aggressiveShots,{tacticId:'tatico',components:{attackWeight:1.1}});
    return patterns.sort((a,b)=>b.confidenceScore-a.confidenceScore);
  }
}
