import { drawFallbackSprite } from './SpriteFallbackRenderer.js';
export class PlayerSpriteRenderer {
  constructor(pack) { this.pack = pack; }
  draw(ctx, player, profile, sprite, options = {}) { const scale = options.scale || 1; if (!sprite || !this.pack?.procedural) { drawFallbackSprite(ctx, player, profile, scale); return; } const jumpStates = ['smash', 'bandeja', 'stretched_defense']; const jump = jumpStates.includes(sprite.name) ? Math.sin(Math.PI * Math.min(1, sprite.frameIndex / Math.max(1, sprite.config.frames.length - 1))) * (sprite.name === 'smash' ? 9 : 5) : 0; const stride = ['run', 'walk', 'shuffle', 'backpedal', 'moving'].includes(sprite.name) ? Math.sin(sprite.frameIndex * Math.PI) * 3 : 0; const strike = ['serve', 'forehand', 'backhand', 'volley_forehand', 'volley_backhand', 'lob', 'bandeja', 'smash', 'wall_return'].includes(sprite.name); const strikeProgress = sprite.frameIndex / Math.max(1, sprite.config.frames.length - 1); const armAngle = strike ? -1.5 + strikeProgress * 2.8 : -.5 + stride * .06; const bodyWidth = profile.body_type === 'athletic' ? 13 : profile.body_type === 'slim' ? 9 : 11;
    ctx.save(); ctx.translate(0, -jump); if (sprite.mirrored) ctx.scale(-1, 1); ctx.globalAlpha = options.blend == null ? 1 : .75 + options.blend * .25;
    ctx.strokeStyle = 'rgba(0,0,0,.35)'; ctx.lineWidth = 4 * scale; ctx.beginPath(); ctx.moveTo(-3 * scale, 12 * scale); ctx.lineTo((-4 - stride) * scale, 22 * scale); ctx.moveTo(3 * scale, 12 * scale); ctx.lineTo((4 + stride) * scale, 22 * scale); ctx.stroke();
    ctx.fillStyle = profile.shorts_color; ctx.fillRect(-bodyWidth / 2 * scale, 7 * scale, bodyWidth * scale, 8 * scale); ctx.fillStyle = profile.shirt_primary; ctx.beginPath(); ctx.roundRect(-bodyWidth / 2 * scale, -8 * scale, bodyWidth * scale, 18 * scale, 4 * scale); ctx.fill(); ctx.fillStyle = profile.shirt_secondary; ctx.fillRect(-bodyWidth / 2 * scale, 1 * scale, bodyWidth * scale, 3 * scale);
    ctx.strokeStyle = profile.skin_tone; ctx.lineWidth = 4 * scale; ctx.beginPath(); ctx.moveTo(-bodyWidth / 2 * scale, -4 * scale); ctx.lineTo((-10 - stride) * scale, 4 * scale); ctx.moveTo(bodyWidth / 2 * scale, -4 * scale); ctx.lineTo((7 + Math.cos(armAngle) * 10) * scale, (-2 + Math.sin(armAngle) * 10) * scale); ctx.stroke();
    const handX = (7 + Math.cos(armAngle) * 10) * scale; const handY = (-2 + Math.sin(armAngle) * 10) * scale; ctx.strokeStyle = '#334155'; ctx.lineWidth = 2 * scale; ctx.beginPath(); ctx.moveTo(handX, handY); ctx.lineTo(handX + Math.cos(armAngle) * 9 * scale, handY + Math.sin(armAngle) * 9 * scale); ctx.stroke(); ctx.beginPath(); ctx.ellipse(handX + Math.cos(armAngle) * 13 * scale, handY + Math.sin(armAngle) * 13 * scale, 4 * scale, 6 * scale, armAngle, 0, Math.PI * 2); ctx.stroke();
    ctx.fillStyle = profile.skin_tone; ctx.beginPath(); ctx.arc(0, -14 * scale, 6 * scale, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = profile.hair_color; ctx.beginPath(); ctx.arc(0, -16 * scale, 6 * scale, Math.PI, 0); ctx.fill();
    if (sprite.name === 'celebration') { ctx.strokeStyle = profile.skin_tone; ctx.beginPath(); ctx.moveTo(-4, -5); ctx.lineTo(-9, -18); ctx.moveTo(4, -5); ctx.lineTo(9, -18); ctx.stroke(); } if (sprite.name === 'frustration') { ctx.rotate(.1); }
    if (options.debug) { ctx.strokeStyle = '#ff00ff'; ctx.lineWidth = 1; ctx.strokeRect(-32, -58, 64, 80); ctx.fillStyle = '#00ffff'; ctx.fillRect(-2, sprite.pivot.y - 2, 4, 4); ctx.fillStyle = '#fff'; ctx.font = '9px monospace'; ctx.fillText(`${sprite.name} f${sprite.frameIndex} ${sprite.direction}`, -30, -62); }
    ctx.restore(); return { jump, racketPoint: { x: handX, y: handY }, impact: sprite.impact };
  }
}
