import { resolveReplayScene } from './ReplayScene.js';
import { CAMERA_MODES, COURT_RENDER_CONFIG, DEFAULT_VISUAL_OPTIONS } from './ReplayVisualConfig.js';
import { SpriteSystem } from './sprites/SpriteSystem.js';

export class Match2DRenderer {
  constructor(canvas, options = {}) { this.canvas = canvas; this.ctx = canvas.getContext('2d'); this.options = { ...DEFAULT_VISUAL_OPTIONS, ...options }; this.viewport = null; this.camera = { x: 5, y: 10, zoom: 1 }; this.sprites = new SpriteSystem(); this.sprites.preload(); }
  setOptions(options) { Object.assign(this.options, options); }
  resize() { const rect = this.canvas.getBoundingClientRect(); const ratio = typeof window === 'undefined' ? 1 : window.devicePixelRatio || 1; if (this.canvas.width !== Math.round(rect.width * ratio) || this.canvas.height !== Math.round(rect.height * ratio)) { this.canvas.width = Math.round(rect.width * ratio); this.canvas.height = Math.round(rect.height * ratio); } this.ctx.setTransform(ratio, 0, 0, ratio, 0, 0); this.viewport = { width: rect.width, height: rect.height, padding: COURT_RENDER_CONFIG.padding, courtW: rect.width - COURT_RENDER_CONFIG.padding * 2, courtH: rect.height - COURT_RENDER_CONFIG.padding * 2 }; }
  worldToScreen(position = {}) { const v = this.viewport; const zoom = this.camera.zoom; const baseX = v.padding + position.x / COURT_RENDER_CONFIG.widthMeters * v.courtW; const baseY = v.padding + position.y / COURT_RENDER_CONFIG.lengthMeters * v.courtH - (position.z || 0) * 4; const centerX = v.width / 2; const centerY = v.height / 2; const focusX = v.padding + this.camera.x / 10 * v.courtW; const focusY = v.padding + this.camera.y / 20 * v.courtH; return { x: centerX + (baseX - focusX) * zoom, y: centerY + (baseY - focusY) * zoom }; }
  screenToWorld(position) { const v = this.viewport; const centerX = v.width / 2; const centerY = v.height / 2; const focusX = v.padding + this.camera.x / 10 * v.courtW; const focusY = v.padding + this.camera.y / 20 * v.courtH; const baseX = focusX + (position.x - centerX) / this.camera.zoom; const baseY = focusY + (position.y - centerY) / this.camera.zoom; return { x: (baseX - v.padding) / v.courtW * 10, y: (baseY - v.padding) / v.courtH * 20 } ; }
  updateCamera(scene) { const mode = CAMERA_MODES.includes(this.options.cameraMode) ? this.options.cameraMode : 'full_court'; let target = { x: 5, y: 10, zoom: 1 }; if (mode === 'follow_ball') target = { x: scene.ball.x, y: scene.ball.y, zoom: 1.12 }; if (mode === 'follow_player') { const player = scene.players.find((item) => item.id === this.options.followedPlayerId) || scene.players[0]; target = { x: player.position.x, y: player.position.y, zoom: 1.1 }; } if (mode === 'auto' && ['volley', 'smash'].includes(scene.shot?.type)) target = { x: scene.ball.x, y: scene.ball.y, zoom: scene.shot.type === 'smash' ? 1.16 : 1.1 }; const amount = this.options.enableCameraMotion && !this.options.reducedMotion ? .12 : 1; this.camera.x += (target.x - this.camera.x) * amount; this.camera.y += (target.y - this.camera.y) * amount; this.camera.zoom += (target.zoom - this.camera.zoom) * amount; }
  drawCourt() { const { ctx } = this; const p0 = this.worldToScreen({ x: 0, y: 0 }); const p1 = this.worldToScreen({ x: 10, y: 20 }); const high = this.options.highContrast; ctx.fillStyle = high ? '#071a12' : '#10251e'; ctx.fillRect(0, 0, this.viewport.width, this.viewport.height); ctx.fillStyle = high ? '#087f5b' : '#27785d'; ctx.fillRect(p0.x, p0.y, p1.x - p0.x, p1.y - p0.y); ctx.strokeStyle = '#eafff7'; ctx.lineWidth = 1.5; ctx.strokeRect(p0.x, p0.y, p1.x - p0.x, p1.y - p0.y);
    const line = (a, b, width = 1) => { const start = this.worldToScreen(a); const end = this.worldToScreen(b); ctx.lineWidth = width; ctx.beginPath(); ctx.moveTo(start.x, start.y); ctx.lineTo(end.x, end.y); ctx.stroke(); }; line({ x: 0, y: 10 }, { x: 10, y: 10 }, 3); line({ x: 0, y: 7 }, { x: 10, y: 7 }); line({ x: 0, y: 13 }, { x: 10, y: 13 }); line({ x: 5, y: 0 }, { x: 5, y: 7 }); line({ x: 5, y: 13 }, { x: 5, y: 20 });
    ctx.strokeStyle = high ? '#fffb00' : '#8ed1c0'; ctx.lineWidth = 5; line({ x: 0, y: 0 }, { x: 10, y: 0 }, 5); line({ x: 0, y: 20 }, { x: 10, y: 20 }, 5); ctx.lineWidth = 3; line({ x: 0, y: 0 }, { x: 0, y: 7 }, 3); line({ x: 10, y: 0 }, { x: 10, y: 7 }, 3); line({ x: 0, y: 13 }, { x: 0, y: 20 }, 3); line({ x: 10, y: 13 }, { x: 10, y: 20 }, 3);
    ctx.fillStyle = 'rgba(255,255,255,.55)'; ctx.font = '10px sans-serif'; ctx.textAlign = 'center'; const top = this.worldToScreen({ x: 5, y: 1 }); const bottom = this.worldToScreen({ x: 5, y: 19 }); ctx.fillText('DUPLA B', top.x, top.y); ctx.fillText('DUPLA A', bottom.x, bottom.y); }
  drawScene(scene) { const { ctx } = this; if (this.options.showTrails && scene.trail.length > 1) { ctx.strokeStyle = 'rgba(235,255,80,.45)'; ctx.lineWidth = 2; ctx.beginPath(); scene.trail.forEach((item, index) => { const p = this.worldToScreen(item); index ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y); }); ctx.stroke(); }
    if (this.options.showBounceMarks) scene.impacts.forEach((impact) => { const p = this.worldToScreen(impact.position); ctx.strokeStyle = impact.type === 'net_contact' ? '#fff' : '#f97316'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(p.x, p.y, 5 + impact.progress * 10, 0, Math.PI * 2); ctx.stroke(); });
    scene.players.forEach((player) => { const p = this.worldToScreen(player.position); if (this.options.quality !== 'low') { ctx.fillStyle = 'rgba(0,0,0,.25)'; ctx.beginPath(); ctx.ellipse(p.x, p.y + 4, 11 * this.options.playerScale, 4 * this.options.playerScale, 0, 0, Math.PI * 2); ctx.fill(); } ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(player.angle); this.sprites.drawPlayer(ctx, player, this.currentTime, this.currentReplay.seed, { scale: this.options.playerScale, quality: this.options.reducedMotion ? 'low' : this.options.quality, debugSprites: this.options.debugSprites }); ctx.restore(); if (this.options.showNames) { const profile = this.sprites.profile(player, player.teamIndex, this.currentReplay.seed); ctx.fillStyle = '#fff'; ctx.font = '11px sans-serif'; ctx.textAlign = 'center'; ctx.fillText(`${profile.marker_shape === 'triangle' ? '▲' : '●'} ${player.name?.split(' ')[0] || player.id}`, p.x, p.y - 30 * this.options.playerScale); } });
    const shadow = this.worldToScreen({ x: scene.ball.x, y: scene.ball.y, z: 0 }); ctx.fillStyle = `rgba(0,0,0,${Math.max(.08, .3 - scene.ball.z * .035)})`; ctx.beginPath(); ctx.ellipse(shadow.x, shadow.y, 5 + scene.ball.z, 2.5, 0, 0, Math.PI * 2); ctx.fill(); const ball = this.worldToScreen(scene.ball); ctx.fillStyle = '#efff48'; ctx.strokeStyle = '#111'; ctx.lineWidth = 1; ctx.beginPath(); ctx.arc(ball.x, ball.y, 4.5 * this.options.ballScale * scene.ball.scale, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); this.sprites.emitForScene(ctx, scene, (position) => this.worldToScreen(position), this.currentTime, this.options.quality, this.options.reducedMotion); }
  drawHud(replay, scene) { const { ctx } = this; ctx.fillStyle = 'rgba(0,0,0,.76)'; ctx.fillRect(8, 8, this.viewport.width - 16, 42); ctx.fillStyle = '#fff'; ctx.textAlign = 'left'; ctx.font = 'bold 12px sans-serif'; const a = replay.teams[0]?.players.map((p) => p.name.split(' ')[0]).join(' / '); const b = replay.teams[1]?.players.map((p) => p.name.split(' ')[0]).join(' / '); ctx.fillText(`${a}  ×  ${b}`, 16, 23); ctx.font = '11px sans-serif'; ctx.fillText(`${scene.score.sets.join('-')} sets · ${scene.score.games.join('-')} games · ${scene.score.points.join('-')} pontos`, 16, 40); ctx.textAlign = 'right'; ctx.fillText(`${scene.shot?.type || 'ready'} · ${scene.shot?.speed || 0} km/h · ${scene.rallyShots} golpes`, this.viewport.width - 16, 40); }
  render(replay, time) { this.currentReplay = replay; this.currentTime = time; this.resize(); const scene = resolveReplayScene(replay, time, this.options); this.updateCamera(scene); this.ctx.clearRect(0, 0, this.viewport.width, this.viewport.height); this.drawCourt(); this.drawScene(scene); this.drawHud(replay, scene); this.lastScene = scene; return scene; }
}
