import { eventProgress } from './ReplayTimeline.js';
import { DEFAULT_SHOT_SPEED, easeMovement, trajectoryHeight } from './ReplayVisualConfig.js';
import { narrationAt } from './ReplayNarration.js';

const lerp = (a, b, amount) => a + (b - a) * amount;
const interpolate = (from = {}, to = {}, amount) => ({ x: lerp(from.x ?? 5, to.x ?? 5, amount), y: lerp(from.y ?? 10, to.y ?? 10, amount), z: lerp(from.z || 0, to.z || 0, amount) });
export function resolveReplayScene(replay, time, options = {}) {
  const players = new Map(); replay.teams.flatMap((team, teamIndex) => team.players.map((player) => ({ ...player, teamIndex }))).forEach((player) => players.set(player.id, { id: player.id, name: player.name, teamIndex: player.teamIndex, position: player.initial_position || { x: player.court_side === 'left' ? 7 : 3, y: player.teamIndex ? 4 : 16 }, state: 'ready', angle: player.teamIndex ? Math.PI / 2 : -Math.PI / 2 }));
  let ball = { x: 5, y: 10, z: 1, scale: 1 }; let score = replay.initial_score || { sets: [0, 0], games: [0, 0], points: ['0', '0'] }; let shot = null; let servingPlayerId = null; const impacts = []; const trail = [];
  for (const event of replay.events) { if (event.t > time) break; const active = time <= event.t + event.duration; const progress = eventProgress(event, time); const actor = players.get(event.actor_id);
    if (event.type === 'player_move' && actor) { const eased = easeMovement(progress, event.data?.movement, options.reducedMotion); actor.position = interpolate(event.data?.from || actor.position, event.data?.to || actor.position, eased); actor.state = active ? 'moving' : 'ready'; actor.angle = Math.atan2((event.data?.to?.y ?? actor.position.y) - (event.data?.from?.y ?? actor.position.y), (event.data?.to?.x ?? actor.position.x) - (event.data?.from?.x ?? actor.position.x)); }
    if (event.type === 'serve') { servingPlayerId = event.actor_id; if (actor) { actor.state = active ? 'serving' : 'ready'; actor.position = event.data?.origin || actor.position; actor.angle = Math.atan2((event.data?.target?.y ?? 10) - actor.position.y, (event.data?.target?.x ?? 5) - actor.position.x); } const base = interpolate({ ...(event.data?.origin || actor?.position || ball), z: 1.5 }, { ...(event.data?.target || ball), z: 0 }, progress); ball = { ...base, z: trajectoryHeight('serve', progress, base.z), scale: 1 }; }
    if (event.type === 'shot') { shot = { type: event.data?.shot_type || 'drive', speed: event.data?.ball_speed_kmh ?? DEFAULT_SHOT_SPEED[event.data?.shot_type] ?? 60, actorId: event.actor_id }; if (actor) { actor.state = active ? (shot.type === 'drive' ? 'forehand' : shot.type) : 'ready'; const origin = event.data?.origin; if (origin) { const distance = Math.hypot(actor.position.x - origin.x, actor.position.y - origin.y); if (distance <= 3) actor.position = interpolate(actor.position, origin, Math.min(1, progress * 2)); } actor.angle = Math.atan2((event.data?.target?.y ?? ball.y) - actor.position.y, (event.data?.target?.x ?? ball.x) - actor.position.x); } }
    if (event.type === 'ball_move') { const from = event.data?.from || ball; const to = event.data?.to || ball; const base = interpolate(from, to, progress); const profile = event.data?.trajectory || shot?.type || 'arc'; ball = { ...base, z: trajectoryHeight(profile, progress, base.z), scale: 1 }; trail.push(interpolate(from, to, Math.max(0, progress - .2)), ball); }
    if (['bounce', 'wall_contact', 'side_wall_contact', 'back_wall_contact', 'double_wall_contact', 'net_contact'].includes(event.type)) { const position = event.data?.position || ball; if (active) { ball = { ...position, scale: .7 + .3 * progress }; impacts.push({ type: event.type, position, progress }); } }
    if (event.type === 'winner' && actor) actor.state = active ? 'celebrating' : actor.state; if (event.type === 'error' && actor) actor.state = active ? 'frustrated' : actor.state; if (event.type === 'celebration') players.forEach((player) => { if (replay.teams[player.teamIndex]?.id.endsWith(String(event.data?.team || '').toLowerCase())) player.state = 'celebrating'; }); if (event.type === 'score_update') score = event.data;
  }
  return { players: [...players.values()], ball, score, shot, servingPlayerId, impacts, trail: trail.slice(-20), narration: narrationAt(replay, time), rallyShots: replay.events.filter((event) => event.t <= time && event.type === 'shot').length };
}
