import { Volume2, VolumeX, Radio, Trophy, SkipForward } from 'lucide-react';
import { BROADCAST_PRESETS } from '@/gameplay/replay/broadcast/BroadcastSettings.js';
const clock = (ms = 0) => `${Math.floor(ms / 60000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`;
export default function BroadcastHUD({ replay, model, settings, onSettings, onSkipIntro, replaying }) { if (!model) return null; const teams = replay.teams || []; const special = model.point?.reasons?.includes('match_point') ? 'MATCH POINT' : model.point?.reasons?.includes('set_point') ? 'SET POINT' : model.point?.reasons?.includes('break_or_game_point') ? 'BREAK POINT' : '';
  return <><div className="pointer-events-none absolute left-3 right-3 top-3 z-10 flex items-start justify-between gap-3" style={{ fontSize: `${settings.textScale || 1}em` }}><div className={`rounded-lg border px-3 py-2 shadow-xl ${settings.highContrast ? 'bg-black border-yellow-300 text-yellow-100' : 'bg-slate-950/90 border-white/20 text-white'}`}><div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-red-400"><Radio className="h-3 w-3"/> Ao vivo <span className="text-white/60">{clock(model.elapsed)}</span></div>{teams.map((team,index)=><div key={team.id} className="grid grid-cols-[1fr_2rem_2rem_3rem] gap-2 items-center text-xs mt-1"><span className="font-bold truncate">{index ? '●' : '▲'} {team.players.map((p)=>p.name.split(' ').at(-1)).join(' / ')}</span><span>{model.score.sets[index]}</span><span>{model.score.games[index]}</span><span className="text-lg font-black">{model.score.points[index]}</span></div>)}{special && <div className="mt-1 text-center rounded bg-red-600 px-2 py-0.5 text-[10px] font-black">{special}</div>}</div><div className="rounded-lg bg-black/70 px-2 py-1 text-xs text-white">{model.crowd.state.replace('_',' ')} · {model.stats.longestRally} golpes</div></div>
    {replaying && <div className="pointer-events-none absolute inset-x-0 top-20 z-10 text-center"><span className="rounded bg-red-600 px-4 py-1 text-sm font-black tracking-[.3em] text-white">REPLAY</span></div>}
    {model.phase === 'intro' && <div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-950/90 text-white"><div className="text-center space-y-3"><p className="text-xs uppercase tracking-[.35em] text-red-400">Padel Legacy Broadcast</p><h2 className="text-2xl font-black">{teams[0]?.players.map(p=>p.name).join(' & ')}</h2><p className="text-white/50">contra</p><h2 className="text-2xl font-black">{teams[1]?.players.map(p=>p.name).join(' & ')}</h2><button onClick={onSkipIntro} className="rounded bg-white/10 px-3 py-2 text-xs"><SkipForward className="inline h-4 w-4"/> Pular introdução</button></div></div>}
    {model.phase === 'set_break' && <div className="pointer-events-none absolute inset-x-12 bottom-20 z-10 rounded-xl bg-black/85 p-4 text-center text-white"><b>Intervalo de set</b><p className="text-xs mt-1">{model.score.sets.join('–')} sets · {model.stats.winners} winners · {model.stats.errors} erros · rally mais longo {model.stats.longestRally}</p></div>}
    {model.phase === 'post_match' && <div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-950/90 text-white"><div className="text-center space-y-3"><Trophy className="mx-auto h-10 w-10 text-yellow-300"/><h2 className="text-2xl font-black">Fim de partida</h2><p>{model.score.sets.join('–')} sets · máxima {model.stats.maxSpeed} km/h · rally {model.stats.longestRally}</p><p className="text-xs">{model.highlightPackage.highlight_ids.length} destaques disponíveis</p></div></div>}
    <div className="flex flex-wrap gap-2 rounded-lg bg-secondary/40 p-2 text-xs"><select value={settings.broadcastPreset} onChange={(e)=>onSettings('preset',e.target.value)} className="rounded bg-secondary p-1">{Object.keys(BROADCAST_PRESETS).map((name)=><option key={name}>{name}</option>)}</select><select value={settings.automaticReplays} onChange={(e)=>onSettings('automaticReplays',e.target.value)} className="rounded bg-secondary p-1"><option value="off">Replays desligados</option><option value="important">Só importantes</option><option value="frequent">Frequentes</option></select><button onClick={()=>onSettings('muted',!settings.muted)} className="rounded bg-secondary p-1">{settings.muted?<VolumeX className="h-4 w-4"/>:<Volume2 className="h-4 w-4"/>}</button>{[['masterVolume','Geral'],['effectsVolume','Efeitos'],['crowdVolume','Torcida'],['refereeVolume','Árbitro']].map(([key,label])=><label key={key}>{label}<input type="range" min="0" max="1" step=".1" value={settings[key]} onChange={(e)=>onSettings(key,+e.target.value)} className="w-20 align-middle ml-1"/></label>)}</div></>;
}
