import { useEffect, useRef, useState } from 'react';
import { Play, Pause, RotateCcw, StepBack, StepForward, Download, SkipForward, Flag } from 'lucide-react';
import { ReplayPlayer } from '@/gameplay/replay/ReplayPlayer.js'; import { Match2DRenderer } from '@/gameplay/replay/Match2DRenderer.js'; import { ReplayStorage } from '@/gameplay/replay/ReplayStorage.js'; import { ReplayPreferences } from '@/gameplay/replay/ReplayPreferences.js'; import { CAMERA_MODES, DEFAULT_VISUAL_OPTIONS } from '@/gameplay/replay/ReplayVisualConfig.js'; import { groupReplayPoints } from '@/gameplay/replay/ReplayImportantPoints.js';
import { BroadcastDirector } from '@/gameplay/replay/broadcast/BroadcastDirector.js'; import { MatchPresentationController } from '@/gameplay/replay/broadcast/MatchPresentationController.js'; import { BroadcastSettings, DEFAULT_BROADCAST_SETTINGS } from '@/gameplay/replay/broadcast/BroadcastSettings.js'; import BroadcastHUD from './BroadcastHUD.jsx';
const formatTime = (ms) => `${Math.floor(ms / 60000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`; const button = 'p-2 rounded-lg bg-secondary hover:bg-secondary/80';
export default function ReplayPanel({ replay, live = false }) {
  const canvasRef = useRef(null); const playerRef = useRef(null); const rendererRef = useRef(null); const directorRef = useRef(null); const lastUi = useRef(0); const [state,setState] = useState({status:'idle',currentTime:0,duration:replay.duration||0,speed:1}); const [options,setOptions] = useState(DEFAULT_VISUAL_OPTIONS); const [broadcast,setBroadcast] = useState(DEFAULT_BROADCAST_SETTINGS); const [model,setModel] = useState(null); const [replaying,setReplaying] = useState(false); const [narration,setNarration] = useState('Jogadores em posição.');
  useEffect(()=>{ ReplayPreferences.load().then((saved)=>{setOptions(saved);playerRef.current?.setSpeed(saved.replaySpeed||1);}); BroadcastSettings.load().then(setBroadcast); },[]);
  useEffect(()=>{ const player=new ReplayPlayer({allowIncomplete:live}); const renderer=new Match2DRenderer(canvasRef.current,options); const director=new BroadcastDirector(replay,broadcast); const controller=new MatchPresentationController(player,director); playerRef.current=player;rendererRef.current=renderer;directorRef.current=director;player.load(replay);if(live)player.seek(replay.events.findLast((e)=>e.type==='point_start')?.t||0); const unsubscribe=player.subscribe((next)=>{const scene=renderer.render(replay,next.currentTime);const broadcastModel=director.update(next);const action=controller.onFrame(next,broadcastModel);if(action==='start_replay')setReplaying(true);if(action==='resume_live')setReplaying(false);renderer.setOptions({cameraMode:broadcastModel.cameraMode});const now=performance.now();if(next.status!=='playing'||now-lastUi.current>100){lastUi.current=now;setState(next);setNarration(scene.narration.text);setModel(broadcastModel);}});if(live)player.play();const blur=()=>{if(broadcast.pauseOnBlur)player.pause();director.audio.duck();};const focus=()=>director.audio.resume();window.addEventListener('blur',blur);window.addEventListener('focus',focus);return()=>{window.removeEventListener('blur',blur);window.removeEventListener('focus',focus);unsubscribe();director.destroy();player.destroy();};},[replay,live]);
  useEffect(()=>{rendererRef.current?.setOptions(options);rendererRef.current?.render(replay,playerRef.current?.state.currentTime||0);ReplayPreferences.save({...options,replaySpeed:state.speed});},[options]);
  useEffect(()=>{directorRef.current?.setSettings(broadcast);BroadcastSettings.save(broadcast);setOptions((current)=>({...current,cameraMode:broadcast.cameraMode,reducedMotion:broadcast.reducedMotion,highContrast:broadcast.highContrast,quality:broadcast.quality,enableCameraMotion:broadcast.cameraMotion}));},[broadcast]);
  const update=(key,value)=>setOptions((current)=>({...current,[key]:value})); const updateBroadcast=(key,value)=>setBroadcast((current)=>key==='preset'?BroadcastSettings.applyPreset(value,current):{...current,[key]:value}); const nextImportant=()=>{const point=groupReplayPoints(replay).find((item)=>item.important&&item.start>playerRef.current.state.currentTime);playerRef.current.seek(point?.start??playerRef.current.state.duration);}; const exportReplay=()=>{const blob=new Blob([ReplayStorage.export(replay)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${replay.replay_id}.json`;anchor.click();URL.revokeObjectURL(url);}; const skipIntro=()=>playerRef.current.seek(replay.events.find((event)=>event.type==='point_start')?.t||0);
  return <div className="space-y-3"><div className="relative"><canvas ref={canvasRef} className="w-full h-[440px] rounded-xl border border-border" aria-label="Replay 2D da partida"/><BroadcastHUD replay={replay} model={model} settings={broadcast} onSettings={updateBroadcast} onSkipIntro={skipIntro} replaying={replaying}/></div><div aria-live="polite" className="rounded-lg bg-secondary/50 px-3 py-2 text-sm min-h-9">{broadcast.captionsEnabled?narration:''}</div><input aria-label="Progresso" type="range" min="0" max={state.duration} value={state.currentTime} onChange={(e)=>playerRef.current.seek(+e.target.value)} className="w-full"/>
    <div className="flex flex-wrap items-center gap-2"><button className={button} onClick={()=>state.status==='playing'?playerRef.current.pause():playerRef.current.play()}>{state.status==='playing'?<Pause size={16}/>:<Play size={16}/>}</button><button className={button} onClick={()=>playerRef.current.restartPoint()}><RotateCcw size={16}/></button><button className={button} onClick={()=>playerRef.current.stepBackward()}><StepBack size={16}/></button><button className={button} onClick={()=>playerRef.current.stepForward()}><StepForward size={16}/></button><button className={button} onClick={()=>playerRef.current.nextPoint()}><SkipForward size={16}/></button><button className={button} onClick={()=>playerRef.current.nextGame()}><Flag size={16}/></button><button className={button} onClick={nextImportant}>Importante</button><select value={state.speed} onChange={(e)=>{const speed=+e.target.value;playerRef.current.setSpeed(speed);ReplayPreferences.save({replaySpeed:speed});}} className="bg-secondary rounded-lg px-2 py-1 text-xs">{[.5,1,1.5,2,4].map((speed)=><option key={speed}>{speed}</option>)}</select><span className="text-xs">{formatTime(state.currentTime)} / {formatTime(state.duration)}</span><button className={button} onClick={exportReplay}><Download size={16}/></button></div>
    <div className="grid grid-cols-2 md:grid-cols-5 gap-2 text-xs"><label>Câmera<select value={options.cameraMode} onChange={(e)=>update('cameraMode',e.target.value)} className="block w-full bg-secondary rounded p-1">{CAMERA_MODES.map((mode)=><option key={mode}>{mode}</option>)}</select></label><label>Jogador<select value={options.followedPlayerId||''} onChange={(e)=>update('followedPlayerId',e.target.value)} className="block w-full bg-secondary rounded p-1"><option value="">Automático</option>{replay.teams.flatMap((team)=>team.players).map((player)=><option key={player.id} value={player.id}>{player.name}</option>)}</select></label><label>Qualidade<select value={options.quality} onChange={(e)=>update('quality',e.target.value)} className="block w-full bg-secondary rounded p-1"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label><label>Bola<input type="range" min="1" max="2" step=".25" value={options.ballScale} onChange={(e)=>update('ballScale',+e.target.value)} className="block w-full"/></label><label>Texto<input type="range" min=".8" max="1.5" step=".1" value={broadcast.textScale} onChange={(e)=>updateBroadcast('textScale',+e.target.value)} className="block w-full"/></label></div><div className="flex flex-wrap gap-3 text-xs">{[['showTrails','rastro'],['showBounceMarks','impactos'],['showNames','nomes'],['reducedMotion','movimento reduzido'],['highContrast','alto contraste'],['noFlashes','sem flashes']].map(([key,label])=><label key={key}><input type="checkbox" checked={key in broadcast?broadcast[key]:options[key]} onChange={(e)=>(key in broadcast?updateBroadcast:update)(key,e.target.checked)}/> {label}</label>)}</div></div>;
}
