import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Copy, Play, Plus, Trash2, Pencil, FlaskConical, UserRound, Archive } from 'lucide-react';
import { useCareer } from '@/careers/useCareer.js';

const positionLabel = (value) => value === 'esquerda' ? 'Esquerda' : 'Direita';
const styleLabel = (value = '') => value.charAt(0).toUpperCase() + value.slice(1);

export default function CareerManager() {
  const navigate = useNavigate();
  const { careers, loading, error: providerError, selectCareer, createCareer, renameCareer, duplicateCareer, archiveCareer, deleteCareer } = useCareer();
  const [showCreate, setShowCreate] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ saveName: '', playerName: '', courtSide: 'direita', playStyle: 'equilibrado', careerType: 'normal' });

  const run = async (fn) => { try { setError(''); return await fn(); } catch (e) { setError(e.message || 'Operação não concluída.'); } };
  const create = () => run(async () => {
    if (!form.playerName.trim()) throw new Error('Informe o nome esportivo do jogador.');
    const payload = { ...form, saveName: form.saveName.trim() || `${form.playerName} — ${positionLabel(form.courtSide)}` };
    await createCareer(payload); setShowCreate(false); navigate('/game');
  });
  const play = (id) => run(async () => { await selectCareer(id); navigate('/game'); });
  const rename = (career) => run(async () => { const name = window.prompt('Novo nome da carreira:', career.save_name); if (name?.trim()) await renameCareer(career.id, name); });
  const duplicate = (career) => run(() => duplicateCareer(career.id, { careerType: 'experiment' }));
  const archive = (career) => run(async () => { if (window.confirm(`Arquivar “${career.save_name}”?`)) await archiveCareer(career.id); });
  const remove = (career) => run(async () => { if (window.confirm(`Excluir definitivamente “${career.save_name}”?`)) await deleteCareer(career.id); });
  const visibleCareers = careers.filter((career) => !career.archived);

  return <div className="min-h-screen bg-background text-foreground p-4 md:p-8"><div className="max-w-5xl mx-auto">
    <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8"><div><p className="text-primary font-bold tracking-[0.25em] text-xs">PADEL LEGACY OFFLINE</p><h1 className="text-3xl md:text-5xl font-black tracking-tight mt-1">Escolha sua carreira</h1><p className="text-muted-foreground mt-2">Cada save possui jogador e progresso independentes.</p></div><button onClick={() => setShowCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary text-primary-foreground px-5 py-3 font-bold"><Plus className="h-5 w-5" /> Nova carreira</button></header>
    {(error || providerError) && <div className="mb-5 rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-sm">{error || providerError}</div>}
    {loading ? <p>Carregando saves locais...</p> : visibleCareers.length === 0 ? <div className="glass rounded-2xl p-10 text-center"><UserRound className="h-12 w-12 text-primary mx-auto mb-4" /><h2 className="text-xl font-bold">Nenhuma carreira criada</h2><p className="text-muted-foreground mt-2">Crie seu primeiro jogador para iniciar um novo universo.</p><button onClick={() => setShowCreate(true)} className="mt-6 rounded-xl bg-primary text-primary-foreground px-5 py-3 font-bold">Criar primeira carreira</button></div> : <div className="grid md:grid-cols-2 gap-4">{visibleCareers.map((career) => <article key={career.id} className="glass rounded-2xl p-5 border border-border/50"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold">{career.save_name}</h2>{career.career_type === 'experiment' && <span className="text-xs rounded-full bg-primary/15 text-primary px-2 py-1 inline-flex items-center gap-1"><FlaskConical className="h-3 w-3" /> Experimento</span>}</div><p className="text-muted-foreground mt-1">{career.player_name} · {positionLabel(career.court_side)} · {styleLabel(career.play_style)}</p></div><button onClick={() => play(career.id)} className="rounded-xl bg-primary text-primary-foreground p-3" title="Jogar"><Play className="h-5 w-5" /></button></div><div className="grid grid-cols-3 gap-3 mt-5 text-sm"><div><p className="text-muted-foreground text-xs">Data</p><p className="font-semibold">{career.career_date}</p></div><div><p className="text-muted-foreground text-xs">Ranking</p><p className="font-semibold">{career.ranking_position ? `#${career.ranking_position}` : '—'}</p></div><div><p className="text-muted-foreground text-xs">Último jogo</p><p className="font-semibold">{new Date(career.last_played_at).toLocaleDateString('pt-BR')}</p></div></div><div className="flex flex-wrap gap-2 mt-5 pt-4 border-t border-border/40"><button onClick={() => play(career.id)} className="inline-flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-4 py-2 text-sm font-semibold"><Play className="h-4 w-4" /> Jogar</button><button onClick={() => duplicate(career)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Copy className="h-4 w-4" /> Duplicar</button><button onClick={() => rename(career)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Pencil className="h-4 w-4" /> Renomear</button><button onClick={() => archive(career)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Archive className="h-4 w-4" /> Arquivar</button><button onClick={() => remove(career)} className="inline-flex items-center gap-2 rounded-lg border border-destructive/40 px-3 py-2 text-sm text-destructive"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>}
  </div>
  {showCreate && <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-2xl bg-card border p-6"><h2 className="text-2xl font-black">Nova carreira</h2><p className="text-muted-foreground text-sm mt-1">Um novo jogador e um novo mundo serão criados.</p><div className="space-y-4 mt-6"><label className="block text-sm font-medium">Nome esportivo<input value={form.playerName} onChange={(e) => setForm({...form, playerName:e.target.value})} className="mt-1 w-full rounded-xl border bg-background px-3 py-2" /></label><label className="block text-sm font-medium">Nome do save<input value={form.saveName} onChange={(e) => setForm({...form, saveName:e.target.value})} className="mt-1 w-full rounded-xl border bg-background px-3 py-2" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-medium">Lado<select value={form.courtSide} onChange={(e) => setForm({...form, courtSide:e.target.value})} className="mt-1 w-full rounded-xl border bg-background px-3 py-2"><option value="direita">Direita</option><option value="esquerda">Esquerda</option></select></label><label className="block text-sm font-medium">Estilo<select value={form.playStyle} onChange={(e) => setForm({...form, playStyle:e.target.value})} className="mt-1 w-full rounded-xl border bg-background px-3 py-2"><option value="equilibrado">Equilibrado</option><option value="controle">Controle</option><option value="agressivo">Agressivo</option><option value="defensivo">Defensivo</option></select></label></div><label className="block text-sm font-medium">Tipo<select value={form.careerType} onChange={(e) => setForm({...form, careerType:e.target.value})} className="mt-1 w-full rounded-xl border bg-background px-3 py-2"><option value="normal">Carreira principal</option><option value="experiment">Experimento</option></select></label></div><div className="flex justify-end gap-3 mt-6"><button onClick={() => setShowCreate(false)} className="rounded-xl border px-4 py-2">Cancelar</button><button onClick={create} className="rounded-xl bg-primary text-primary-foreground px-5 py-2 font-bold">Criar e jogar</button></div></div></div>}
  </div>;
}
