export const PAGE_INTRODUCTIONS = {
  '/game': { title: 'Painel da carreira', description: 'Resumo da sua situação, energia, compromissos e recomendações.', purpose: 'Use o painel para decidir a melhor ação do momento sem precisar procurar em várias páginas.', tip: 'Comece pelo cartão de próximo passo e confira o próximo compromisso.' },
  '/profile': { title: 'Perfil do atleta', description: 'Identidade, lado, estilo, atributos, nível e condição atual.', purpose: 'É a visão central para entender como seu atleta está evoluindo.', tip: 'Compare pontos fortes e atributos mais baixos antes de escolher o próximo treino.' },
  '/game/missions': { title: 'Objetivos e missões', description: 'Tutorial, metas diárias, semanais, mensais e sazonais.', purpose: 'As missões ensinam recursos, criam objetivos e recompensam ações reais.', tip: 'Siga apenas o passo atual do tutorial; etapas futuras ficam bloqueadas.' },
  '/character': { title: 'Aparência', description: 'Personalização visual e identidade do seu atleta.', purpose: 'Diferencia seu personagem sem alterar a evolução esportiva, salvo regra explícita.', tip: 'Confira a prévia antes de salvar as alterações.' },
  '/achievements': { title: 'Conquistas', description: 'Marcos permanentes, desafios especiais e feitos raros.', purpose: 'Registra objetivos que vão além das missões periódicas.', tip: 'Use como inspiração para metas de longo prazo.' },
  '/game/stats': { title: 'Estatísticas da carreira', description: 'Resultados, evolução e tendências do desempenho.', purpose: 'Os números mostram o que está funcionando e onde você precisa ajustar.', tip: 'Não avalie o atleta por uma única partida; observe tendências.' },
  '/game/legacy': { title: 'Legado', description: 'Títulos, recordes, marcos e impacto acumulado da trajetória.', purpose: 'Mostra como sua carreira será lembrada ao longo das temporadas.', tip: 'O legado cresce com consistência, não apenas com uma grande vitória.' },

  '/development': { title: 'Desenvolvimento', description: 'Hub de treinos, equipe técnica, instalações e equipamentos.', purpose: 'Reúne tudo que transforma planejamento em evolução do atleta.', tip: 'Equilibre evolução com energia e compromissos próximos.' },
  '/game/training': { title: 'Treinos', description: 'Escolha grupo, foco e intensidade para desenvolver atributos relacionados.', purpose: 'Treinos são a principal forma de evolução, mas consomem energia e geram fadiga.', tip: 'Veja a previsão completa antes de confirmar.' },
  '/training-center': { title: 'Centro de treinamento', description: 'Instalações e estruturas usadas na preparação do atleta.', purpose: 'Uma estrutura melhor pode aumentar a eficiência de treino e recuperação.', tip: 'Priorize melhorias compatíveis com suas necessidades atuais.' },
  '/coaches': { title: 'Treinadores', description: 'Profissionais, especialidades e benefícios para o desenvolvimento.', purpose: 'A equipe técnica ajuda a acelerar pontos fortes ou corrigir fraquezas.', tip: 'Compare especialidade, custo e duração antes de contratar.' },
  '/game/inventory': { title: 'Equipamentos', description: 'Itens que você possui e quais estão ativos.', purpose: 'O inventário permite organizar e equipar recursos disponíveis.', tip: 'Leia os efeitos antes de trocar o item ativo.' },
  '/game/shop': { title: 'Loja', description: 'Equipamentos e itens disponíveis para compra.', purpose: 'Permite investir em melhorias, mantendo controle do orçamento.', tip: 'No início, preserve recursos para inscrições e recuperação.' },

  '/team-hub': { title: 'Dupla e relações', description: 'Hub de parceiros, propostas, relações públicas e torcida.', purpose: 'Sua carreira depende do atleta e também das conexões construídas.', tip: 'Comece pelas propostas de parceria quando ainda estiver sem dupla.' },
  '/partners': { title: 'Minha dupla e propostas', description: 'Compare candidatos, aceite propostas e acompanhe sua parceria atual.', purpose: 'Lado, estilo, nível e entrosamento influenciam o desempenho da dupla.', tip: 'Compatibilidade pode ser mais importante que escolher apenas o maior overall.' },
  '/relationships': { title: 'Relacionamentos', description: 'Relações com atletas e personagens importantes da carreira.', purpose: 'Boas relações podem abrir oportunidades e reduzir conflitos.', tip: 'Mudanças frequentes de parceiro podem ter consequências.' },
  '/press': { title: 'Imprensa', description: 'Entrevistas, perguntas e repercussão pública.', purpose: 'Suas respostas influenciam reputação, narrativa e relações.', tip: 'Considere o contexto antes de responder.' },
  '/fans': { title: 'Fãs e torcidas', description: 'Popularidade, apoio e reações do público.', purpose: 'Mostra o alcance da sua carreira além do ranking esportivo.', tip: 'Resultados e postura pública podem alterar o apoio.' },

  '/competitions': { title: 'Competições', description: 'Hub de torneios, calendário, partidas, ranking e temporada.', purpose: 'Aqui sua preparação se transforma em resultados oficiais.', tip: 'Confira calendário e energia antes de escolher um evento.' },
  '/tournaments': { title: 'Torneios', description: 'Competições disponíveis, requisitos, prazos e premiações.', purpose: 'Torneios geram experiência, dinheiro, reputação e ranking.', tip: 'Só inscrições confirmadas permitem jogar; evite datas sobrepostas.' },
  '/game/calendar': { title: 'Calendário', description: 'Agenda de treinos, recuperações, inscrições, partidas e eventos.', purpose: 'Um bom planejamento evita conflitos e cansaço antes das competições.', tip: 'Reserve recuperação antes de torneios importantes.' },
  '/matches': { title: 'Partidas', description: 'Acompanhe jogos narrados, placar, táticas e resultados.', purpose: 'É onde atributos, parceiro, energia e decisões táticas se combinam.', tip: 'Velocidade e modo de narração não alteram o resultado.' },
  '/ranking': { title: 'Ranking', description: 'Classificações de atletas, duplas e outras categorias disponíveis.', purpose: 'Mostra sua evolução competitiva e o caminho para eventos maiores.', tip: 'Consistência costuma valer mais que buscar eventos avançados cedo demais.' },
  '/game/season': { title: 'Temporada', description: 'Objetivos, desempenho acumulado e calendário anual.', purpose: 'Ajuda a avaliar a carreira em médio prazo, não apenas o último jogo.', tip: 'Compare o progresso atual com as metas da temporada.' },
  '/world-tour/live': { title: 'Circuito ao vivo', description: 'Acompanhe partidas e resultados do mundo do jogo.', purpose: 'Permite observar rivais e estrelas sem interferir na sua própria partida.', tip: 'Use para entender tendências e adversários do circuito.' },

  '/world': { title: 'Mundo do padel', description: 'Hub de notícias, mercado, atletas, clubes, comunidade e história.', purpose: 'O circuito continua evoluindo e gera oportunidades ao redor da sua carreira.', tip: 'Explore aos poucos; nem todo evento exige uma ação imediata.' },
  '/journal': { title: 'Notícias', description: 'Resultados, mudanças de dupla e acontecimentos do circuito.', purpose: 'Dá contexto às mudanças do mundo e à trajetória dos rivais.', tip: 'Use como informação; nem toda notícia exige uma decisão.' },
  '/world-events': { title: 'Eventos mundiais', description: 'Acontecimentos que alteram atletas, clubes e o circuito.', purpose: 'Explica mudanças que podem criar oportunidades ou novos desafios.', tip: 'Confira a data e as entidades envolvidas.' },
  '/world-market': { title: 'Mercado mundial', description: 'Atletas, valores, disponibilidade e movimentações do circuito.', purpose: 'Ajuda a planejar futuras parcerias e acompanhar rivais.', tip: 'Sistema avançado: compare interesse e compatibilidade, não só ranking.' },
  '/weather': { title: 'Clima', description: 'Condições climáticas e possíveis efeitos nos eventos.', purpose: 'Quando ativo, o clima pode influenciar preparação e estratégia.', tip: 'Confira a previsão antes de compromissos relevantes.' },
  '/athletes': { title: 'Atletas', description: 'Base de jogadores reais e fictícios do circuito.', purpose: 'Permite pesquisar parceiros, rivais, estilos e trajetórias.', tip: 'Use filtros de lado, nível e disponibilidade.' },
  '/clubs': { title: 'Clubes', description: 'Estruturas, reputação e oportunidades oferecidas pelos clubes.', purpose: 'Clubes podem influenciar treinamento, eventos e conexões.', tip: 'Compare instalações, localização e benefícios.' },
  '/community': { title: 'Comunidade', description: 'Atividades e interações da comunidade do jogo.', purpose: 'Amplia a sensação de um universo vivo e compartilhado.', tip: 'Consulte novidades sem perder o foco da carreira.' },
  '/social': { title: 'Rede social', description: 'Publicações, repercussão e presença digital do atleta.', purpose: 'A exposição pode influenciar fãs, reputação e oportunidades.', tip: 'Uma postagem pode ter efeitos diferentes conforme o contexto.' },
  '/encyclopedia': { title: 'Enciclopédia', description: 'Regras, conceitos, sistemas e termos do jogo.', purpose: 'Permite rever explicações sem reiniciar o tutorial.', tip: 'Use a busca quando encontrar um termo desconhecido.' },
  '/history': { title: 'História do padel', description: 'Registros históricos, temporadas e acontecimentos importantes.', purpose: 'Contextualiza sua trajetória dentro de um universo maior.', tip: 'Consulte quando quiser conhecer a evolução do esporte.' },
  '/hall-of-fame': { title: 'Hall da Fama', description: 'Atletas e carreiras que alcançaram feitos históricos.', purpose: 'Representa objetivos máximos para uma trajetória longa.', tip: 'Compare os feitos necessários para entrar entre as lendas.' },

  '/management': { title: 'Gestão', description: 'Hub de finanças e ferramentas administrativas avançadas.', purpose: 'Ajuda a manter a carreira sustentável e os dados organizados.', tip: 'Ferramentas administrativas devem ser usadas com cuidado.' },
  '/game/economy': { title: 'Economia', description: 'Saldo, receitas, despesas, premiações e compromissos.', purpose: 'Manter uma reserva evita que custos bloqueiem seus planos.', tip: 'Não comprometa grande parte do saldo no início.' },
  '/admin': { title: 'Administração', description: 'Ferramentas avançadas para gerenciamento e diagnóstico.', purpose: 'Ajuda a revisar sistemas quando houver necessidade técnica.', tip: 'Evite alterações sem entender o impacto.' },
  '/database': { title: 'Banco de dados', description: 'Consulta de entidades e dados internos disponibilizados pelo jogo.', purpose: 'Permite diagnosticar conteúdo e integridade das informações.', tip: 'Esta é uma área avançada; não altere dados sem necessidade.' },
};

export function getPageIntroduction(pathname) {
  if (!pathname) return null;
  if (pathname.startsWith('/clubs/')) return PAGE_INTRODUCTIONS['/clubs'];
  return PAGE_INTRODUCTIONS[pathname] || null;
}
