export const TUTORIAL_VERSION = 4;

const step = (id, objectiveType, title, route, chapter, completionType = 'open_and_interact', extra = {}) => ({ id, objectiveType, title, explanation: extra.explanation || `Conheça ${title.toLowerCase()} e entenda como isso afeta sua carreira.`, whyItMatters: extra.whyItMatters || 'Este sistema faz parte do ciclo de evolução da carreira.', route, actionLabel: extra.actionLabel || 'Abrir', chapter, phase: chapter, completionType, targetTab: extra.targetTab || null, targetElement: extra.targetElement || null, requirements: extra.requirements || [], reward: extra.reward || { xp: 20, coins: 35 } });

export const TUTORIAL_CHAPTERS = Object.freeze([
  { id: 'identity', title: 'Identidade e carreira', unlockAfter: null },
  { id: 'development', title: 'Desenvolvimento', unlockAfter: 'profile-reviewed' },
  { id: 'team', title: 'Dupla e relações', unlockAfter: 'first-training' },
  { id: 'competition', title: 'Competições', unlockAfter: 'partner-selected' },
  { id: 'world', title: 'Mundo do jogo', unlockAfter: 'first-match' },
  { id: 'management', title: 'Gestão e legado', unlockAfter: 'world-rankings' },
]);

export const TUTORIAL_STEPS = [
  step('career-created','visit_career','Conheça o painel','/game','Identidade e carreira','confirm_understanding',{actionLabel:'Começar',reward:{xp:20,coins:50}}),
  step('athlete-named','set_player_name','Dê um nome ao atleta','/game/missions','Identidade e carreira','perform_action'),
  step('side-selected','choose_court_side','Escolha mão dominante e lado','/game/missions','Identidade e carreira','perform_action'),
  step('style-selected','choose_play_style','Escolha o estilo de jogo','/game/missions','Identidade e carreira','perform_action'),
  step('profile-reviewed','review_profile','Revise o perfil do atleta','/profile','Identidade e carreira','confirm_understanding'),
  step('development-hub','visit_development','Abra Desenvolvimento','/development','Desenvolvimento'),
  step('attributes-known','review_attributes','Conheça seus atributos','/profile','Desenvolvimento','confirm_understanding'),
  step('training-groups','review_training_groups','Entenda os grupos de treino','/game/training','Desenvolvimento','confirm_understanding'),
  step('first-training','complete_training','Faça o primeiro treino','/game/training','Desenvolvimento','domain_event',{reward:{xp:50,coins:75}}),
  step('energy-understood','understand_energy','Entenda energia e fadiga','/game/training','Desenvolvimento','confirm_understanding'),
  step('first-recovery','use_recovery','Faça uma recuperação','/game/training','Desenvolvimento','domain_event'),
  step('equipment-known','visit_inventory','Conheça os equipamentos','/game/inventory','Desenvolvimento'),
  step('appearance-known','visit_character','Conheça a aparência','/character','Desenvolvimento'),
  step('team-hub','visit_team_hub','Abra Dupla e relações','/team-hub','Dupla e relações'),
  step('offers-reviewed','review_partner_offer','Revise propostas de dupla','/partners?view=offers&source=tutorial','Dupla e relações','open_and_interact'),
  step('compatibility-known','review_compatibility','Compare compatibilidade','/partners?view=offers&source=tutorial','Dupla e relações','confirm_understanding'),
  step('partner-selected','select_partner','Escolha sua primeira dupla','/partners?view=offers&source=tutorial','Dupla e relações','domain_event',{reward:{xp:60,coins:100}}),
  step('chemistry-known','review_chemistry','Entenda o entrosamento','/partners','Dupla e relações','confirm_understanding'),
  step('relationships-known','visit_relationships','Conheça relacionamentos','/relationships','Dupla e relações'),
  step('press-known','visit_press','Conheça a imprensa','/press','Dupla e relações'),
  step('competitions-hub','visit_competitions','Abra Competições','/competitions','Competições'),
  step('tournaments-known','visit_tournaments','Conheça os torneios','/tournaments','Competições'),
  step('calendar-conflicts','review_calendar_conflicts','Verifique conflitos de agenda','/game/calendar','Competições','confirm_understanding'),
  step('tournament-registered','join_tournament','Inscreva-se em um torneio','/tournaments','Competições','domain_event',{requirements:['has-partner'],reward:{xp:100,coins:150}}),
  step('match-started','start_match','Inicie uma partida','/matches','Competições','domain_event'),
  step('match-modes','review_match_modes','Conheça Texto, 2D e pontos-chave','/matches','Competições','confirm_understanding'),
  step('match-tactics','change_match_tactic','Altere a tática da dupla','/matches','Competições','domain_event'),
  step('match-speed','change_match_speed','Altere a velocidade','/matches','Competições','domain_event'),
  step('first-match','play_matches','Conclua sua primeira partida','/matches','Competições','domain_event',{reward:{xp:100,coins:150}}),
  step('ranking-known','visit_ranking','Consulte o ranking','/ranking','Competições'),
  step('news-known','visit_journal','Abra as notícias','/journal','Mundo do jogo'),
  step('market-known','visit_world_market','Conheça o Mercado Mundial','/world-market','Mundo do jogo'),
  step('athletes-known','visit_athletes','Conheça outros atletas','/athletes','Mundo do jogo'),
  step('events-known','visit_world_events','Entenda eventos mundiais','/world-events','Mundo do jogo'),
  step('world-rankings','review_world_circuit','Conheça o circuito global','/world','Mundo do jogo','confirm_understanding'),
  step('finances-known','visit_economy','Entenda receitas e despesas','/game/economy','Gestão e legado'),
  step('shop-known','visit_shop','Conheça a loja','/game/shop','Gestão e legado'),
  step('item-equipped','equip_item','Equipe um item','/game/inventory','Gestão e legado','domain_event'),
  step('achievements-known','visit_achievements','Conheça as conquistas','/achievements','Gestão e legado'),
  step('history-known','visit_history','Consulte o histórico','/history','Gestão e legado'),
  step('legacy-known','visit_legacy','Conheça seu legado','/game/legacy','Gestão e legado'),
  step('autonomy','finish_tutorial','Comece a carreira livre','/game','Gestão e legado','perform_action',{actionLabel:'Ir para o painel',reward:{xp:80,coins:150}}),
];

export const TUTORIAL_MISSION_CATALOG = TUTORIAL_STEPS.map((tutorialStep, index) => ({
  id: `tutorial-${tutorialStep.id}`,
  title: tutorialStep.title,
  description: tutorialStep.explanation,
  why_it_matters: tutorialStep.whyItMatters,
  action_label: tutorialStep.actionLabel,
  mission_type: 'tutorial',
  objective_type: tutorialStep.objectiveType,
  target_count: 1,
  xp_reward: Number(tutorialStep.reward?.xp || 0),
  coins_reward: Number(tutorialStep.reward?.coins || 0),
  tutorial_order: index + 1,
  tutorial_chapter: tutorialStep.chapter,
  tutorial_route: tutorialStep.route,
  target_tab: tutorialStep.targetTab,
  target_element: tutorialStep.targetElement,
  completion_type: tutorialStep.completionType,
  requirements: tutorialStep.requirements,
}));

export const CORE_GAME_LOOP = ['Planejar', 'Treinar', 'Administrar energia', 'Escolher parceiro', 'Competir', 'Receber resultados', 'Evoluir', 'Subir no ranking'];
export const GLOSSARY = { Atributo:'Habilidade do atleta.',Energia:'Recurso gasto em treinos e partidas.',Fadiga:'Cansaço acumulado.',Confiança:'Momento mental do atleta.',Entrosamento:'Coordenação da dupla.',Reputação:'Reconhecimento da carreira.',Ranking:'Posição competitiva.',Experiência:'Progresso usado para subir de nível.',Potencial:'Margem de evolução.',Estilo:'Perfil tático do atleta.',Lado:'Posição preferencial na dupla.',Calendário:'Planejamento da carreira.',Temporada:'Ciclo competitivo anual.',Circuito:'Torneios e rankings globais.',Inscrição:'Entrada confirmada em torneio.',Premiação:'Recompensas competitivas.',Patrocinador:'Contrato comercial.',Legado:'Impacto duradouro da carreira.' };
