import { sampleReplay } from '../fixtures/sampleReplay.js';
import { SpectatorStore } from './SpectatorStore.js';
import { evaluateWorldMatchImportance } from './WorldMatchImportanceEvaluator.js';
import { chooseWorldReplayType, enforceWeeklyReplayBudget } from './WorldReplayPolicy.js';
import { MatchSimulationLock,MemoryMatchLockStore } from './MatchSimulationLock.js';
import { SpectatorReservationManager } from './SpectatorReservationManager.js';
import { SpectatorMatchService } from './SpectatorMatchService.js';
import { SpectatorSettings } from './SpectatorSettings.js';
const unsupported={isSupported:()=>false};
export async function runPadelSpectatorWorldTest(){const store=new SpectatorStore(unsupported);const lock=new MatchSimulationLock(new MemoryMatchLockStore());const saves=[];const library={save:async(replay,context)=>{saves.push({replay,context});return{saved:true};},load:async()=>structuredClone(sampleReplay)};const service=new SpectatorMatchService({library,lock,store});
const common={match_id:'common-1',tournament_level:'Silver',round:'r32',player_ids:['a','b']};const commonBotMatchStoredAsResult=chooseWorldReplayType(common,evaluateWorldMatchImportance(common,{}),{})==='result';
const important={match_id:'crown-final',tournament_id:'crown',tournament_name:'Crown Madrid',tournament_level:'Crown',round:'final',player_ids:['one','two'],ranking_positions:[1,3],status:'scheduled'};let simulations=0,persisted=0;const options={simulate:async()=>{simulations++;return{result:'A',score:'6-4 6-3',replay:structuredClone(sampleReplay)};},persistOfficial:async()=>{persisted++;}};const [live,concurrent]=await Promise.all([service.process('career-a',important,options),service.process('career-a',important,options)]);const importantMatchReplayGenerated=live.result.replay_type==='full'&&saves.length===1;const simulationExecutedOnce=simulations===1&&persisted===1&&concurrent.executed===false;
await store.save('career-a',{followed_player_ids:['followed']});const recommendations=await service.recommend('career-a',[{...common,match_id:'followed-match',player_ids:['followed','x']}]);const followedPlayerRecommended=recommendations[0]?.importance.reasons.includes('atleta seguido');
const reservations=new SpectatorReservationManager(store);await reservations.reserve('career-a',{match_id:'future',status:'scheduled',date:'2028-01-02'});const reservationHandled=(await reservations.due('career-a','2028-01-02')).length===1;
const before=simulations;const completed=await service.openCompleted('career-a',{match_id:'done',status:'completed',result:'B',score:'6-2'});const completedMatchNotResimulated=completed.type==='result'&&simulations===before;
await store.save('career-a',{spectator_settings:{hide_results_before_watching:true}});const state=await store.load('career-a');const spoilerModeWorking=state.spectator_settings.hide_results_before_watching&&!state.spoiler_revealed_match_ids.includes('done');
const budget=enforceWeeklyReplayBudget(Array.from({length:20},(_,i)=>({importance:{score:100-i},replay_type:'full'})),{weekly_full_replay_limit:2,weekly_summary_limit:3});const worldStorageLimitRespected=budget.filter((x)=>x.replay_type==='full').length===2&&budget.filter((x)=>x.replay_type==='summary').length===3;
await store.save('career-b',{followed_player_ids:['other']});const careersIsolated=(await store.load('career-a')).followed_player_ids.includes('followed')&&!(await store.load('career-b')).followed_player_ids.includes('followed');const result={commonBotMatchStoredAsResult,importantMatchReplayGenerated,followedPlayerRecommended,reservationHandled,simulationExecutedOnce,completedMatchNotResimulated,spoilerModeWorking,worldStorageLimitRespected,careersIsolated};return{ok:Object.values(result).every(Boolean),...result};}
if(typeof window!=='undefined')window.PadelSpectatorWorldTest={run:runPadelSpectatorWorldTest};
