import { useEffect, useRef, useState } from 'react';
import { defaultSpritePack } from '@/gameplay/replay/sprites/defaultSpritePack.js';
import { resolveSpriteFrame } from '@/gameplay/replay/sprites/SpriteResolver.js';
import { PlayerSpriteRenderer } from '@/gameplay/replay/sprites/PlayerSpriteRenderer.js';
import { createPlayerVisualProfile } from '@/gameplay/replay/sprites/PlayerVisualProfile.js';
const directions = ['N','NE','E','SE','S','SW','W','NW']; const angles = { E:0,SE:Math.PI/4,S:Math.PI/2,SW:3*Math.PI/4,W:Math.PI,NW:-3*Math.PI/4,N:-Math.PI/2,NE:-Math.PI/4 };
export default function SpritePreview() { const canvasRef = useRef(null); const [animation, setAnimation] = useState('forehand'); const [direction, setDirection] = useState('E'); const [speed, setSpeed] = useState(1); const [debug, setDebug] = useState(true); const [team, setTeam] = useState(0);
  useEffect(() => { const canvas = canvasRef.current; const ctx = canvas.getContext('2d'); const renderer = new PlayerSpriteRenderer({ manifest: defaultSpritePack, procedural: true }); const player = { id: 'preview-player', name: 'Preview', state: animation, angle: angles[direction], teamIndex: team }; const profile = createPlayerVisualProfile(player, team, `preview-${team}`); let frame; const started = performance.now(); const draw = (now) => { ctx.clearRect(0,0,canvas.width,canvas.height); ctx.fillStyle = '#173d31'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.strokeStyle = 'rgba(255,255,255,.2)'; ctx.beginPath(); ctx.moveTo(0,260); ctx.lineTo(canvas.width,260); ctx.stroke(); const sprite = resolveSpriteFrame(defaultSpritePack, animation, angles[direction], (now-started)*speed, 'high'); ctx.save(); ctx.translate(240,240); ctx.scale(3,3); renderer.draw(ctx, player, profile, sprite, { scale: 1, debug }); ctx.restore(); ctx.fillStyle='#fff'; ctx.font='14px monospace'; ctx.fillText(`${animation} · ${direction} · frame ${sprite.frameIndex}${sprite.impact ? ' · IMPACTO' : ''}`,16,24); frame=requestAnimationFrame(draw); }; frame=requestAnimationFrame(draw); return () => cancelAnimationFrame(frame); }, [animation,direction,speed,debug,team]);
  return <main className="min-h-screen bg-background text-foreground p-6"><div className="max-w-3xl mx-auto space-y-4"><h1 className="text-2xl font-black">Sprite Preview</h1><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><label className="text-xs">Animação<select className="block w-full bg-secondary p-2 rounded" value={animation} onChange={(e)=>setAnimation(e.target.value)}>{Object.keys(defaultSpritePack.animations).map((name)=><option key={name}>{name}</option>)}</select></label><label className="text-xs">Direção<select className="block w-full bg-secondary p-2 rounded" value={direction} onChange={(e)=>setDirection(e.target.value)}>{directions.map((name)=><option key={name}>{name}</option>)}</select></label><label className="text-xs">Velocidade<input className="block w-full" type="range" min=".25" max="2" step=".25" value={speed} onChange={(e)=>setSpeed(+e.target.value)}/></label><label className="text-xs">Uniforme<select className="block w-full bg-secondary p-2 rounded" value={team} onChange={(e)=>setTeam(+e.target.value)}><option value="0">Dupla A</option><option value="1">Dupla B</option></select></label><label className="text-xs flex items-center gap-2"><input type="checkbox" checked={debug} onChange={(e)=>setDebug(e.target.checked)}/> pivô/debug</label></div><canvas ref={canvasRef} width="480" height="320" className="w-full max-w-[480px] rounded-xl border border-border bg-transparent"/><p className="text-sm text-muted-foreground">Pack procedural autoral · camadas corpo/cabelo/uniforme/raquete · fundo transparente disponível ao remover o preenchimento de preview.</p></div></main>; }
